### ISSUE TITLE
Web 计算usersig  js库 出错

### ISSUE THREAD

**Issue by RanX12** [tencentyun/TRTCSDK#100]
【Web】- Web计算usersig失败

【当前现象】：Web使用示例Demo中的js库计算usersig失败
【集成包】："trtc-js-sdk": "4.3.1"
【SDKAppID】：1400290949
【机型】：Mac OS 10.12.6
【是否必现】：必现
【日志或者截图】：
lib-generate-test-usersig.min.js:formatted:8171 Uncaught Error: have should not go down
    at lib-generate-test-usersig.min.js:formatted:8171
    at f (lib-generate-test-usersig.min.js:formatted:8171)
    at bo.Ao._processChunk (lib-generate-test-usersig.min.js:formatted:8171)
    at So (lib-generate-test-usersig.min.js:formatted:8171)
    at Object.deflateSync (lib-generate-test-usersig.min.js:formatted:8171)
    at e.value (lib-generate-test-usersig.min.js:formatted:8171)
    at e.value (lib-generate-test-usersig.min.js:formatted:8171)
    at e.value (lib-generate-test-usersig.min.js:formatted:8171)
    at HTMLButtonElement.<anonymous> (lib-generate-test-usersig.min.js:formatted:8171)
    at HTMLButtonElement.dispatch (lib-generate-test-usersig.min.js:formatted:8171)

**Comment by MasterXS** [comment]
@anderlu any thoughts?

**Comment by RanX12** [comment]
我这个是放到线上去了的，但是线上跟我开发平台是一样的

**Comment by RanX12** [comment]
线上的测试环境

**Comment by anderlu** [comment]
请问是什么浏览器？

**Comment by RanX12** [comment]
Chrome

**Comment by anderlu** [comment]
按照demo的文档运行是否有问题？ 我们这边相同环境下没有重现上述异常，另外lib-generate-test-usersig.min.js 只用于demo体验，线上环境需要通过部署后台服务进行usersig的签发。

**Comment by RanX12** [comment]
嗯嗯，我后台是Ruby，但是没有这个API，所以我就想着先用lib-generate-test-usersig.min.js来计算usersig

**Comment by RanX12** [comment]
开发环境按照demo的文档运行没有问题。

**Comment by anderlu** [comment]
![image](https://user-images.githubusercontent.com/1832616/70589693-4ec56a00-1c0b-11ea-87a1-c2750523cc2c.png)
lib-generate-test-usersig.min.js 需要严格按照这个示例代码来使用

**Comment by RanX12** [comment]
我是用的这个代码，我自己写了个ruby计算你们腾讯云TRTC的API，现在不用了Demo的lib-generate-test-usersig.min.js

**Comment by MrTentacle** [comment]
老哥 您用ruby或者JS写过腾讯TRTC的API鉴权方面的代码吗 求副本 参考一下~ OTZ
他们那个解散房间功能的鉴权 sha1算法用了三个参数好像 小弟能力有限搞不定 就被迫用云函数用了生成的node.js代码
结果推上去用了一下 发现解散房间这个云函数相应非常慢延迟在2秒到十几秒不等 T-T


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.Ran"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 下午3:13
收件人:&nbsp;"tencentyun/TRTCSDK"<TRTCSDK@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/TRTCSDK] Web 计算usersig  js库 出错 (#100)




我是用的这个代码，我自己写了个ruby计算你们腾讯云TRTC的API，现在不用了Demo的lib-generate-test-usersig.min.js

**Comment by RanX12** [comment]
API鉴权方面的代码?我只写了生成了usersig的代码。。

**Comment by suonian** [comment]
服务端计算 usersig 参考这里 https://cloud.tencent.com/document/product/647/17275#Server

**Comment by RanX12** [comment]
嗯嗯，这里面只有一些主流语言的API

**Comment by MrTentacle** [comment]
多谢 感激不尽 OTZ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 上午10:47
收件人:&nbsp;"tencentyun/TRTCSDK"<TRTCSDK@noreply.github.com&gt;;
抄送:&nbsp;"Tentacles"<410607115@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/TRTCSDK] Web 计算usersig  js库 出错 (#100)




服务端计算 usersig 参考这里 https://cloud.tencent.com/document/product/647/17275#Server
