### ISSUE TITLE
【Android】-【6.8.7969】 SDK 增加视频过程中拍照的功能

### ISSUE THREAD

**Issue by sodarfish** [tencentyun/TRTCSDK#101]
【现象】实时音视频过程中，无法触发拍照

【需求】： 在实时音视频的过程中，让用户可以点击拍照，即触发Camera的takePicture动作。 

【问题】：目前由于SDK占用了Camera，导致SDK外部的代码没有权限再去操作Camera,  SDK也没有暴露出Camera对象出来，导致无法实现拍照。

【期望】：把Camera对象通过SDK暴露出来； 或者封装一个takePicture方法给开发者。

**Comment by suonian** [comment]
您好，感谢反馈。这个特性我们正在实现中。

**Comment by kuen229** [comment]
6.9.8321版本已经实现snapshotVideo接口，可以用来截取视频画面
