### ISSUE TITLE
能否提供腾讯云TRTC 的sdk的适合vs2013工具下导入编译成功的sdk的大包

### ISSUE THREAD

**Issue by hbb-haobeibei** [tencentyun/TRTCSDK#102]
能否提供腾讯云TRTC 的sdk的适合vs2013工具下导入编译成功的sdk的大包

**Comment by kamisBB** [comment]
C++版本 or  C#？  在vs2013 导入有什么问题？

**Comment by whalehe** [comment]
可以按照这个模板提issue，https://github.com/tencentyun/TRTCSDK/issues/53

如有代码修改，需要您贴下代码，方便我们定位您的问题，然后解决您遇到的问题。
