### ISSUE TITLE
【web】-【4.3.2】【问题简述，远端流视频不显示，只显示一个播放按钮的背景】

### ISSUE THREAD

**Issue by huangyumei418** [tencentyun/TRTCSDK#106]
【当前现象】
当监听到远端进房时，播放远端流视频，目前在浏览器上运行一切正常，但打包为APP时远端的视频界面只显示一个播放按钮的东西（运行环境为http）

【集成包】
TRTC精简版

【机型】
小米8屏幕指纹版

【复现概率】
必现

【相关附件】
![微信图片编辑_20191223160904](https://user-images.githubusercontent.com/56687835/71344882-bcc04880-259e-11ea-8bb8-b4b70299d684.jpg)

**Comment by huangyumei418** [comment]
已在应用信息开启摄像头录音拍照等权限，本地流画面在APP是可以展现的，但远端则一直是这个页面，能听到声音

**Comment by Rychou** [comment]
你好，请问是什么浏览器及版本号是多少？可以执行下这个 [WebRTC 能力检测](https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html)，若执行未通过，则说明相应版本浏览器尚未完全支持WebRTC能力

**Comment by ctrlands** [comment]
大兄弟，我遇到相同的情况了，请问您最后怎么解决的啊？
