### ISSUE TITLE
紧急问题

### ISSUE THREAD

**Issue by Zpsgithub** [tencentyun/TRTCSDK#108]
大神帮我看看 该传都传了  进入视频通话闪退 -100018

**Comment by suonian** [comment]
您好，麻烦按照模版提供详细信息。
闪退贴一下堆栈信息

**Comment by suonian** [comment]
这个错误信息是 userSig 校验失败。参考[错误码](https://cloud.tencent.com/document/product/647/32257)
可以在[实时音视频控制台](https://console.cloud.tencent.com/trtc/usersigtool)检测 userSig 是否正确

**Comment by suonian** [comment]
重复问题
