### ISSUE TITLE
【Android/iOS】-【6.5.7272】【问题简述，如进房失败，提示错误码xxxx】

### ISSUE THREAD

**Issue by Zpsgithub** [tencentyun/TRTCSDK#109]
【当前现象】
如进房失败，提示错误码 进房失败get tinyid error -100018

【集成包】
TRTC精简版 / 专业版Professional / 企业版Enterprise

【SDKAppID】
1400XXXXXX

【房间号】
123456

【useID】
userNameA

【问题时间段】
2019-09-01 16:23~16:55

【机型】
如iPhone 7 Plus

【之前版本有无此问题】
如6.4之前没有，6.6有

【复现概率】
必现 / 偶现(如有大约概率请标明)

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 在 ... 回调中调用 ...
4. 在 ... 回调中调用 ...
5. 出现 Bug

【Demo 复现途径】
可复现  / 不可复现
1. 点击 ...
2. 进入 ..
3. 等待 ...
4. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by suonian** [comment]
这个错误信息是 userSig 校验失败。参考[错误码](https://cloud.tencent.com/document/product/647/32257)
可以在[实时音视频控制台](https://console.cloud.tencent.com/trtc/usersigtool)检测 userSig 是否正确
