### ISSUE TITLE
demo中MAX_USER 设置为7是为什么

### ISSUE THREAD

**Issue by shingohu** [tencentyun/TRTCSDK#11]
RT

**Comment by kuen229** [comment]
这个是demo堆叠模式UI的限制，demo实现得比较简单，写死了7个视频view，可以修改UI实现去掉这个限制

**Comment by shingohu** [comment]
@kuen229 看文档说视频通话模式支持1000人,想问下,demo中用到了9宫格,不清楚这里创建超过9个视频view会有什么问题？比如20-30个这样,或者说关于这个有没有一个限制或者最佳建议
