### ISSUE TITLE
您好，关于安卓音视频通话问题

### ISSUE THREAD

**Issue by Zpsgithub** [tencentyun/TRTCSDK#110]
能成功进入房间，但是看不到对方画面，听不到对方声音？是什么问题

**Comment by tao-pu** [comment]
感谢您的反馈
麻烦确认：
1. 是否是同一个sdkappid
2. 是否进入同一个房间
3. 是否对方和你使用的userid重复
4. 对方是否开启音频推流
5. 本端是否调用了muteRemoteAudio

弱排除上述问题，麻烦提供双端的log，及问题详细说明和复现步骤。

**Comment by whalehe** [comment]
可以按照这个模板提issue，https://github.com/tencentyun/TRTCSDK/issues/53

如有代码修改，需要您贴下代码，方便我们定位您的问题，然后解决您遇到的问题。
