### ISSUE TITLE
【Android】Android 音视频 呼叫接听的实现

### ISSUE THREAD

**Issue by Zpsgithub** [tencentyun/TRTCSDK#111]
大佬好，我也在做视频一对一聊天，想问问你呼叫接听这个是怎么实现的，这个demo只能直接进入房间的

**Comment by crazywenza** [comment]
你可以去看看TIMSDK

**Comment by whalehe** [comment]
目前我们的场景化方案已经出来，可以参考这个视频通话：https://cloud.tencent.com/document/product/647/42045
