### ISSUE TITLE
【Android】-【6.5.7272】【问题简述，系统音量TRTCSystemVolumeTypeAuto模式下，在切换过程中，无法播放声音】

### ISSUE THREAD

**Issue by ouyangfeng** [tencentyun/TRTCSDK#112]
【当前现象】
场景：停止接受对方视频流 自己开始推视频流 同时用SoundPool播放一个语音 会出现 播不出来的情况

经实际验证  系统音量TRTCSystemVolumeTypeAuto下 模式发生切换导致的，如果改成TRTCSystemVolumeTypeMedia就没有问题，但是这个TRTCSystemVolumeTypeAuto模式在线上环境已经经过用户验证 所以还不敢贸然切到TRTCSystemVolumeTypeMedia模式

【集成包】
专业版Professional 

【SDKAppID】
1400118932

【机型】
任意Android机型

【之前版本有无此问题】
一直有

【复现概率】
必现

【复现途径】
1. A推流B接受
2. 切换成 B推流A接受，此刻同时用SoundPool播放一个语音
3. 语音无法播出 或者只能听见最后两个字
4. 出现 Bug

【Demo 复现途径】
可复现  / 不可复现
1. A推流B接受
2. 切换成 B推流A接受，此刻同时用SoundPool播放一个语音
3. 语音无法播出 或者只能听见最后两个字
4. 出现 Bug

**Comment by realing** [comment]
您好，播放短音频建议使用 SDK 的 API  ： playAudioEffect
