### ISSUE TITLE
【Windows】-【6.5.7272】【最低配电脑要求】

### ISSUE THREAD

**Issue by 836257514** [tencentyun/TRTCSDK#113]
想知道一下贵产品
观看1080P + 640X480
且同时推640X480时
帧率保持在15
需要的最低配电脑要求

**Comment by kamisBB** [comment]
你好，非常感谢您反馈的问题， 可参考测试数据

![image](https://user-images.githubusercontent.com/13995207/71790471-a240a180-306b-11ea-99ed-8abb93d205d0.png)
