### ISSUE TITLE
最新版 QQ浏览器 无法视频

### ISSUE THREAD

**Issue by borgzhong** [tencentyun/TRTCSDK#114]
使用 android 最新版 QQ浏览器 (9.9, 10.0)无法视频了，开启点击允许后，无音视频，部分手机可以在顶部看到调用了一下摄像头就结束了。

**Comment by Rychou** [comment]
你好，请执行下 [WebRTC能力检测](https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html)，看看执行结果，若执行不通过，则说明对应版本浏览器尚未支持WebRTC全部能力。
