### ISSUE TITLE
官方demo web端 不发送音视频

### ISSUE THREAD

**Issue by LilongLihongfei** [tencentyun/TRTCSDK#115]

**Comment by LilongLihongfei** [comment]
官方demo （web端 和小程序端视频通话  小程序上看不到web端音视频画面和声音）
官方demo （web端 和Android端视频通话  Android端看不到web端音视频画面和声音）

**Comment by Rychou** [comment]
你好，请提供下浏览器信息和版本号信息。并执行下这个 [WebRTC能力检测测试](https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html) 看看执行结果。

**Comment by LilongLihongfei** [comment]
可以了 我这太电脑驱动有点问题 谢谢
