### ISSUE TITLE
【Windows10 c#】-【6.7】【“ManageLiteAV!ManageLiteAV.ITRTCCloud+StatisticsDelegate::Invoke”类型的已垃圾回收委托进行了回调】

### ISSUE THREAD

**Issue by jingsong-liu** [tencentyun/TRTCSDK#117]
【当前现象】
退出房间后重新进房间，C# SDK抛出异常

【集成包】
TRTC精简版 

【SDKAppID】
1400XXXXXX

【房间号】
123456

【useID】
userNameA

【问题时间段】
2019-09-01 16:23~16:55

【机型】
PC

【之前版本有无此问题】
一直有

【复现概率】
偶现(如有大约概率50%)

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 在 ... 回调中调用 ...
4. 在 ... 回调中调用 ...
5. 出现 Bug

【相关附件】
![image](https://user-images.githubusercontent.com/10648096/72040281-03be7580-32e3-11ea-9af2-b69e11deb2fb.png)

**Comment by Pmjin** [comment]
你好，非常感谢您反馈的问题，我们已经收到类似的反馈，目前已经确定问题并已经修复，最近会发布TRTC 6.9版本，这个版本已经修复该问题，麻烦升级一下，感谢
