### ISSUE TITLE
windows版本TRTCCloud有源码吗

### ISSUE THREAD

**Issue by dragonimp** [tencentyun/TRTCSDK#12]
TRTCCloud的源码是在哪里的？只有.h文件吗？

win10下运行demo提示ucrtbased.dll找不到，建议readme提醒一下，可以从windows 10的sdk下找到，放到bin目录。

**Comment by dragonimp** [comment]
demo安装版的源码也没在这里吗？

**Comment by dragonimp** [comment]
另外，你们还有一个LiteAVDemo(CSharp)的demo项目，是不是也差不多干的这个的，能不能整合一下啊。

**Comment by kamisBB** [comment]
@dragonimp 
问题一： TRTCCloud的源码是在哪里的？只有.h文件吗？

答复： TRTCCloud是我们团队提供简单、稳定的实时音视频通话和连麦直播能力的SDK，你可以在我们SDK基础上快速组装出自己的产品，目前暂时是不开源。

-------------------------------------------------------------------------------------------------------------------

问题二：win10下运行demo提示ucrtbased.dll找不到，建议readme提醒一下，可以从windows 10的sdk下找到，放到bin目录。

答复：ucrtbased.dll 是系统工具的文件，缺失了所有vsxxx（如vs20115）里面执行的项目都不能直接运行，而不是TRTCDemo.vcxproj工程配置问题。解决方案请您参考以下两种方案解决：
https://blog.csdn.net/so_geili/article/details/53009680
https://jingyan.baidu.com/article/1e5468f96a8048484861b711.html

-------------------------------------------------------------------------------------------------------------------

问题三：demo安装版的源码也没在这里吗？

答复：demo安装版的源码因内部产品规划原因还没开源，后续开源会在readme里公布的，请您后续留意window/readme的更新。

-------------------------------------------------------------------------------------------------------------------

问题四：另外，你们还有一个LiteAVDemo(CSharp)的demo项目，是不是也差不多干的这个的，能不能整合一下啊。

答复：您好，C#的版本还在规划中，SDK接口还需要彻底稳定下来，比如我们近期就发现部分客户提出了C++原生接口必须要支持dll动态加载能力，这个在设计支持疏忽了，正在调整。
等 API 完全稳定后（预期3月底），C#会进行相应的包装。
