### ISSUE TITLE
【Windows】-【6.5.7272】【是否开启硬编码解码】 

### ISSUE THREAD

**Issue by 836257514** [tencentyun/TRTCSDK#120]
请问贵产品在windows端推流和拉流，有无开启硬件加速的功能。
cpu占用很高

**Comment by tao-pu** [comment]
widows端暂时还不支持开启硬编解，在后续版本计划会支持，感谢您的反馈，望持续关注。

**Comment by 836257514** [comment]
@tao-pu 你好，请问具体什么时候会支持硬件加速的解码功能呢。
