### ISSUE TITLE
微信小程序组件包异常导致无法正常播放

### ISSUE THREAD

**Issue by ht-sauce** [tencentyun/TRTCSDK#121]
【当前现象】
无法正常视频
个人已经解决该问题。原因在于小程序的组件中的cover-image部分没有正常的隐藏导致loading等图片展示在视频上面，使得视频人员无法看到视频内容

【集成包】
微信小程序组件sdk

【SDKAppID】
无

【房间号】
无

【useID】
无

【问题时间段】
2020-01-15 14:40~14:48

【机型】
小米6

【之前版本有无此问题】
没有

【复现概率】
必现

【复现途径】
可以参考官方demo，官方demo也无法正常进行小程序的视频沟通

**Comment by sskingss** [comment]
这个应该是由于同层渲染的问题导致的，请问是微信的版本是多少呢？

**Comment by anderlu** [comment]
小程序同层模式引起的问题，目前组件已经修复，可以使用最新版组件
