### ISSUE TITLE
【Web】-【4.3.1】【TRTC.checkSystemRequirements().then((result) => 异常】

### ISSUE THREAD

**Issue by RanX12** [tencentyun/TRTCSDK#127]
【当前现象】
在Firefox浏览器获取苹果系统权限时，权限不管是否已经打开，都会执行
 alert('Your browser is not compatible with TRTC');
但是音视频可以正常工作的，如果不支持TRTC的话，音视频是不是也应该不会正常工作呢？

【集成包】
TRTC精简版 

【之前版本有无此问题】
 暂时不知道

【复现概率】
必现

【复现途径】
1. 用Firefox浏览器打开
2. 出现

【Demo 复现途径】
可复现 
1. 用Firefox浏览器打开
2. 出现

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by MasterXS** [comment]
不支持firefox，checkSystemRequirements() 异常表明当前环境不支持。
