### ISSUE TITLE
【Web】-【4.3.4】【屏幕分享时选择麦克风设备无效】

### ISSUE THREAD

**Issue by xro-maestera** [tencentyun/TRTCSDK#128]
【当前现象】
推送带有音频流的屏幕分享流时（即 `{ screen: true, audio: true }`），`LocalStream.switchDevice()` 方法切换麦克风设备不起作用，实测会固定选择系统默认麦克风设备。摄像头视频流则正常。

【集成包】
WebRTC

【机型】
macOS 10.15.3 + Chrome 80.0.3987.87

【之前版本有无此问题】
应该一直存在，未测试

【复现概率】
必现

**Comment by Rychou** [comment]
@xro-maestera 你好，目前 SDK 屏幕分享不支持切换麦克风设备。
