### ISSUE TITLE
【Android】onRemoteUserLeaveRoom收不到回调

### ISSUE THREAD

**Issue by llllonger** [tencentyun/TRTCSDK#129]
android的一对一的语聊中，当一方因为异常情况（比如抛异常直接结束界面等），对方的onRemoteUserLeaveRoom有时候收不到回调，对方就一直显示然后听不到声音。
测试过一些情况下，正常是一分半可以收到对方离开房间的回调onRemoteUserLeaveRoom。

onRemoteUserLeaveRoom这个回调的话一定会走吗，有什么情况下不会收到？这个跟房间有关系吗？如果另外一个人掉线的话是什么状况呢？

**Comment by tao-pu** [comment]
感谢您的反馈，这个回调是一定会有的
如果有发现异常，麻烦提供下log
我们内部自查相关逻辑看下

**Comment by whalehe** [comment]
这个回调进房退房重要的回调，可以排查下是不是网络原因没有走到。如有再遇到，可以附带相关日志，方便排查您遇到的问题。
