### ISSUE TITLE
Android横竖屏旋转怎么设置本地和远程画面

### ISSUE THREAD

**Issue by nickxy** [tencentyun/TRTCSDK#13]
switch (rotation) {
            case Surface.ROTATION_0:
                videoRotation = TRTCCloudDef.TRTC_VIDEO_ROTATION_0;
                resolutionMode = TRTCCloudDef.TRTC_VIDEO_RESOLUTION_MODE_PORTRAIT;
                break;
            case Surface.ROTATION_90:
                videoRotation = TRTCCloudDef.TRTC_VIDEO_ROTATION_90;
                resolutionMode = TRTCCloudDef.TRTC_VIDEO_RESOLUTION_MODE_LANDSCAPE;
                break;
            case Surface.ROTATION_180:
                videoRotation = TRTCCloudDef.TRTC_VIDEO_ROTATION_180;
                resolutionMode = TRTCCloudDef.TRTC_VIDEO_RESOLUTION_MODE_PORTRAIT;
                break;
            case Surface.ROTATION_270:
                videoRotation = TRTCCloudDef.TRTC_VIDEO_ROTATION_270;
                resolutionMode = TRTCCloudDef.TRTC_VIDEO_RESOLUTION_MODE_LANDSCAPE;
                break;
        }

        if(trtcCloud == null){
            return;
        }
        trtcCloud.setLocalViewRotation(videoRotation);
        encParam.videoResolutionMode = resolutionMode;
        trtcCloud.setVideoEncoderParam(encParam);
这样的设置是不是不对？

**Comment by kuen229** [comment]
如果activity方向固定只设置videoResolutionMode就可以了，不需要设置setLocalViewRotation
encParam.videoResolutionMode = resolutionMode;
trtcCloud.setVideoEncoderParam(encParam);

**Comment by nickxy** [comment]
我的场景是横竖屏切换会旋转屏幕，竖屏设置TRTC_VIDEO_RESOLUTION_MODE_PORTRAIT，横屏设置成
TRTC_VIDEO_RESOLUTION_MODE_LANDSCAPE。
encParam.videoResolutionMode = resolutionMode;
trtcCloud.setVideoEncoderParam(encParam);
设置这两个好像不行吧。如果设置成activity不旋转，我把手机横着那不是我看到后台的画面也会横着，不能转过来。
