### ISSUE TITLE
【web】-【4.3.2】【音视频版本API如何选择？】

### ISSUE THREAD

**Issue by huangyumei418** [tencentyun/TRTCSDK#130]
本人项目打算运用音视频，实现视频通话功能，一对一视频，以及群聊视频。项目前端基于VUE开发，之后采用hbuilder打包为APP。这样的模式下我需要采用哪个版本的API最为合适？

**Comment by Rychou** [comment]
@huangyumei418 尽量使用最新版本，可以用 [WebRTC 能力检测] 来检验目标浏览器是否支持 WebRTC
