### ISSUE TITLE
【web】-【 v4.3.5 】【ios 看不到本地画面，错误getUserMedia Error】

### ISSUE THREAD

**Issue by newfan** [tencentyun/TRTCSDK#131]
【当前现象】
看不到本机摄像头画面，远端画面显示黑屏

【机型】
iPhone 7 Plus

【复现概率】
必现 

【复现途径】
官方demo 

【相关附件】

![1581424443(1)](https://user-images.githubusercontent.com/14345536/74237172-e2034480-4d0d-11ea-8826-0e2efd212a41.png)

**Comment by newfan** [comment]
错误信息:
getUserMedia Error observed typeError:undefined is not an object (evaluating navigatror.mediaDevices.getUserMedia

**Comment by Rychou** [comment]
@newfan 请问是什么浏览器？浏览器是否跑过：[WebRTC 能力检测](https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html)

**Comment by newfan** [comment]
> @newfan 请问是什么浏览器？浏览器是否跑过：[WebRTC 能力检测](https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html)

在微信中，确认了，是兼容问题。
