### ISSUE TITLE
【WEB】-【4.3.5/4.3.6】【远端流unsubscribe后，重新subscribe，在macOS下Safari浏览器会出现远端流视频播放正常但是没有声音现象，Chrome下正常】

### ISSUE THREAD

**Issue by hezhongchen09** [tencentyun/TRTCSDK#132]
【当前现象】
远端流unsubscribe后，重新subscribe，在macOS下Safari浏览器会出现远端流视频播放正常但是没有声音现象，Chrome下正常

【集成包】
trtc-js-sdk 4.3.5/4.3.6

【SDKAppID】
1400316391

【房间号】
1210

【useID】
本端userId：student_7075_大跃
远端userId：student_7067_大宝

【问题时间段】
2020-02-18 13:00~13:05

【机型】
macOS Safari 版本13.0.4 (15608.4.9.1.3)

【复现概率】
必现

【复现途径】
1. 大跃订阅大宝，大跃能听到大宝的声音

<img width="769" alt="0000011" src="https://user-images.githubusercontent.com/11245938/74706819-eb7f3600-5252-11ea-90ef-94a2f6cd8086.png">

2. 大跃取消订阅大宝
<img width="1248" alt="0000022" src="https://user-images.githubusercontent.com/11245938/74706885-1ec1c500-5253-11ea-8854-9b344dad5454.png">

3. 大跃重新订阅大宝，大跃听不到大宝的声音
<img width="592" alt="0000033" src="https://user-images.githubusercontent.com/11245938/74706983-6e07f580-5253-11ea-98a1-092d23e48b26.png">

**Comment by Rychou** [comment]
你好，我这边看监控查了一下，发现重新订阅后下行是正常收到音频流的，你那边检查下是否音频流是否是静音状态。

另外也在 safari 下跑一下这个能力测试，看看结果：https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html

![image](https://user-images.githubusercontent.com/25195267/74796232-ed083700-5302-11ea-9b56-8fdc60735a38.png)

**Comment by hezhongchen09** [comment]
但是Chrome是能听到声音的，下面是Safari截图

**Comment by hezhongchen09** [comment]
> 你好，我这边看监控查了一下，发现重新订阅后下行是正常收到音频流的，你那边检查下是否音频流是否是静音状态。
> 
> 另外也在 safari 下跑一下这个能力测试，看看结果：https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html
> 
> ![image](https://user-images.githubusercontent.com/25195267/74796232-ed083700-5302-11ea-9b56-8fdc60735a38.png)

但是Chrome同样操作是可以听到声音的，下面是safari测试截图
<img width="779" alt="88888888" src="https://user-images.githubusercontent.com/11245938/74798662-4f643600-5309-11ea-8bf6-b59dc92d9cd8.png">

**Comment by Rychou** [comment]
那就是对应版本的 safari 未完全支持 webrtc  相关能力

**Comment by Rychou** [comment]
是最新版本的 safari 吗？

**Comment by hezhongchen09** [comment]
> 是最新版本的 safari 吗？

版本13.0.4 (15608.4.9.1.3)

**Comment by Rychou** [comment]
如果是最新版本的 safari 还是没跑通能力测试，这就是 safari 能力支持的问题，我们这边处理不了的。

**Comment by hezhongchen09** [comment]
大宝端音频流本来是静音的，但是大跃端订阅后，会打开音频，下面两图分别是大跃、大宝两端的事件截图
<img width="446" alt="99999999" src="https://user-images.githubusercontent.com/11245938/74799438-7de31080-530b-11ea-92e1-5abd9d668d87.png">
<img width="452" alt="1010101010" src="https://user-images.githubusercontent.com/11245938/74799458-8b989600-530b-11ea-8db8-f5bd519f2bcd.png">

**Comment by hezhongchen09** [comment]
> 如果是最新版本的 safari 还是没跑通能力测试，这就是 safari 能力支持的问题，我们这边处理不了的。

经过测试，把新版Safari的实验功能“WebRTC Unified Plan”关掉就OK了
<img width="927" alt="222222222221" src="https://user-images.githubusercontent.com/11245938/74911870-882f0880-53f8-11ea-9d26-2397c48bcf41.png">

**Comment by RanX12** [comment]
您好，我也遇到同样的问题了，但是我这里是一直听不到声音，并且警告：
[Warning] [19:17:31] <WARN> [s|lyf2*2]  <video> play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
[Warning] [19:20:01] <WARN> [*s|lyf*1] main <video> play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
[Warning] [19:29:53] <WARN> [s|lyf2*2]  <video> play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
[Warning] [19:29:53] <WARN> [*s|rina*3] main <video> play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
[Warning] [19:38:40] <WARN> [s|lyf2*2]  <video> play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
[Warning] [19:38:45] <WARN> [*s|rina*3] main <video> play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
[Warning] [19:38:59] <WARN> [*s|rina*3] main <video> play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
[Warning] [19:39:01] <WARN> [s|lyf2*2]  <video> play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
我关了 WebRTC Unified Plan 之后还是有这样的问题，您有遇到过吗？请问是怎么解决的呢？

**Comment by hezhongchen09** [comment]
> 您好，我也遇到同样的问题了，但是我这里是一直听不到声音，并且警告：
> [Warning] [19:17:31] [s|lyf2_2] play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2) [Warning] [19:20:01] [_s|lyf_1] main play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2) [Warning] [19:29:53] [s|lyf2_2] play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
> [Warning] [19:29:53] [_s|rina_3] main play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
> [Warning] [19:38:40] [s|lyf2_2] play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2) [Warning] [19:38:45] [_s|rina_3] main play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2) [Warning] [19:38:59] [_s|rina_3] main play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2) [Warning] [19:39:01] [s|lyf2_2] play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
> 我关了 WebRTC Unified Plan 之后还是有这样的问题，您有遇到过吗？请问是怎么解决的呢？

你这个问题我这没遇到过

**Comment by MasterXS** [comment]
> 您好，我也遇到同样的问题了，但是我这里是一直听不到声音，并且警告：
> [Warning] [19:17:31] [s|lyf2_2] play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2) [Warning] [19:20:01] [_s|lyf_1] main play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2) [Warning] [19:29:53] [s|lyf2_2] play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
> [Warning] [19:29:53] [_s|rina_3] main play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
> [Warning] [19:38:40] [s|lyf2_2] play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2) [Warning] [19:38:45] [_s|rina_3] main play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2) [Warning] [19:38:59] [_s|rina_3] main play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2) [Warning] [19:39:01] [s|lyf2_2] play() error: AbortError: The operation was aborted. (application-6a683271f64768fcc1da.js, line 2)
> 我关了 WebRTC Unified Plan 之后还是有这样的问题，您有遇到过吗？请问是怎么解决的呢？

play() abort 问题不会影响播放问题，只要后续还有 audio/video player is starting playing 说明音视频都会正常播放。

Safari 下 取消订阅然后再重新订阅无声音问题，应该是 Safari unified-plan的兼容性问题。Safari 下暂时不要 取消订阅然后又重新订阅，我们继续调研这个问题
