### ISSUE TITLE
【iOS】-【6.5.7272】【设置userID为中文，发现id为为乱码形式】

### ISSUE THREAD

**Issue by zhanghengios** [tencentyun/TRTCSDK#133]
【当前现象】
在iOS端，设置userID为中文，发现id为为乱码形式。但是在安卓端和win，网页端设置userID为中文，都没有问题。因为我们项目有需求，使用中文的userID，所以希望得到帮助。

【集成包】
TRTC精简版

**Comment by tao-pu** [comment]
您好，感谢您的建议
请问是iOS收到的userid通知是乱码，还是iOS设置中文userid，在其他端是乱码
SDK对UserID的建议是使用数字、英文大小写、下划线，尽量不要使用特殊符号和非英文符号

**Comment by hezhongchen09** [comment]
> 您好，感谢您的建议
> 请问是iOS收到的userid通知是乱码，还是iOS设置中文userid，在其他端是乱码
> SDK对UserID的建议是使用数字、英文大小写、下划线，尽量不要使用特殊符号和非英文符号

您好，请问这个问题有解决方法吗？

**Comment by hezhongchen09** [comment]
> 【当前现象】
> 在iOS端，设置userID为中文，发现id为为乱码形式。但是在安卓端和win，网页端设置userID为中文，都没有问题。因为我们项目有需求，使用中文的userID，所以希望得到帮助。
> 
> 【集成包】
> TRTC精简版

请问一下您怎么解决的？

**Comment by zhanghengios** [comment]
> 请问一下您怎么解决的？
这个版本sdk不支持，只能考虑其他办法。
我是在sdk使用userId，先转码了，使用的是16进制转码（如果你不考虑window端，我建议优先使用url转码），然后在显示地方解码下就行了

**Comment by hezhongchen09** [comment]
> > 请问一下您怎么解决的？
> > 这个版本sdk不支持，只能考虑其他办法。
> > 我是在sdk使用userId，先转码了，使用的是16进制转码（如果你不考虑window端，我建议优先使用url转码），然后在显示地方解码下就行了

感谢
