### ISSUE TITLE
【WEB】-【4.3.6】无法在移动端上自动播放远端视频源，只有声音

### ISSUE THREAD

**Issue by ctrlands** [tencentyun/TRTCSDK#134]
【当前现象】

使用web的demo通过cordova打包成apk后，在给予相机是音频权限后，本地端视频页面正常，远程端视屏源无法自动播放，处于PAUSED状态，音频声音正常，当处于pause状态时，执行stream.resume()依旧无法正常显示远程端视屏源。stream.resume()这个方法应该在什么时候调用，如何调用，烦请说明或者修复一下
【集成包】
TRTC精简版 

【复现概率】
必现
【相关附件】
![lADPBE1XZDwXST_NBvrNAws_779_1786](https://user-images.githubusercontent.com/29942027/74835280-f243a100-5357-11ea-9eee-e5714e524149.jpg)

**Comment by ctrlands** [comment]
通过stream.on("player-state-changed")事件监听发现，web端sdk在pc页面正常显示，cordova打包成apk后event.status = 'paused' event.reason = 'mute'，why?

**Comment by ctrlands** [comment]
目前猜测是因为底层webview不支持h264的原因

**Comment by 16306** [comment]
问题解决了吗?我刚也碰到了这个问题

**Comment by ctrlands** [comment]
> 问题解决了吗?我刚也碰到了这个问题

目前没有，可能是webview不支持h264编解码，所以只有声音，无画面，应该通过混合开发的方式不太好，cordova打包是用的系统底层的webview，不同机型webview有差异

**Comment by MasterXS** [comment]
android 上系统差异化比较大，使用前请通过 TRTC.checkSystemRequirements()检测当前环境是否支持TRTC。某些机型上，基本通过了检测也不一定能够正常通话，因为WebView或浏览器内核跟系统存在适配问题。建议移动端上使用 native SDK 或小程序。
