### ISSUE TITLE
【Mac/Windows】-【最新版】【开启桌面共享后直播流一直在上行】

### ISSUE THREAD

**Issue by RayGyoe** [tencentyun/TRTCSDK#136]
【当前现象】
使用win&mac版本，开启桌面共享后，停止共享后我发现sdk还一直在上行声音

【集成包】
TRTC

【SDKAppID】
1400102153

【房间号】
43611

【useID】
3

【问题时间段】
all

【机型】
all
【之前版本有无此问题】
all

【复现概率】
必现

【复现途径】
1. 我后台配置了自动开启旁路直播。直播控制台一直能看到共享流在线，并且有声音

【Demo 复现途径】
你们来验证

**Comment by tao-pu** [comment]
您好，SDK支持同时上行辅路和主路摄像头
如果需要关闭主路，即stopLocalPreview

**Comment by RayGyoe** [comment]
就是调用了stopLocalPreview 看云直播这个视频共享还在录制

**Comment by kamisBB** [comment]
你好，“【当前现象】
使用win&mac版本，开启桌面共享后，停止共享后我发现sdk还一直在上行声音”  声音/主路/辅路的开关都有单独接口控制的。
