### ISSUE TITLE
【Android】-【6.8.7959】【偶现】TRTC语音聊天的过程中来了qq电话，之后没有声音了

### ISSUE THREAD

**Issue by llllonger** [tencentyun/TRTCSDK#137]
TRTC语音聊天的时候，一方突然来了qq电话，但是没有接听这个qq电话，这时候突然听不到对方的声音了，后面qq电话挂断后也听不到对方的声音了，这是有什么地方冲突吗？需要怎么解决？偶先的情况

**Comment by realing** [comment]
请问这个问题是某些特定机型才会出问题。还是说是一个普遍问题？

**Comment by whalehe** [comment]
可以按照这个模板提issue，https://github.com/tencentyun/TRTCSDK/issues/53

如有代码修改，需要您贴下代码，方便我们定位您的问题，然后解决您遇到的问题。
