### ISSUE TITLE
【Web】-【4.3.6】【Live模式下，千人以上还需要单独接入旁路直播吗？】

### ISSUE THREAD

**Issue by luozan** [tencentyun/TRTCSDK#138]
1. 提交工单答复说不旁路直播只能300人，万人低延迟直播文档里又写的Live支持万人以上。哪个正确？

2. Live模式计费又是怎样的呢？

**Comment by MasterXS** [comment]
live 低延时大房间可无需旁路直播。计费标准请通过工单咨询，github仅进行技术支持，谢谢理解。
