### ISSUE TITLE
【Android/iOS】-【6.8.7969】【自定义采集】

### ISSUE THREAD

**Issue by pdyw** [tencentyun/TRTCSDK#139]
【当前现象】
视频自定义采集，用纹理方式,纹理大小1280x720(16:9)，接收端收到的分辨率是1280x720,但是可见画面是9:16。腾讯编码器将原16:9画面，居中裁剪9:16了

设置编码代码
 TRTCCloudDef.TRTCVideoEncParam encParam = new TRTCCloudDef.TRTCVideoEncParam();
      
        encParam.videoResolution = TRTCCloudDef.TRTC_VIDEO_RESOLUTION_1280_720;
        encParam.videoFps = quality.outputFps;
        encParam.videoBitrate = quality.bitrateMin;
        encParam.videoResolutionMode = TRTCCloudDef.TRTC_VIDEO_RESOLUTION_MODE_LANDSCAPE;
        trtcCloud.setVideoEncoderParam(encParam);

发送代码
```java
        TRTCCloudDef.TRTCVideoFrame videoFrame = new TRTCCloudDef.TRTCVideoFrame();
        videoFrame.texture = new TRTCCloudDef.TRTCTexture();
        videoFrame.texture.textureId = textureId;
        videoFrame.texture.eglContext14 = eglContext;
        videoFrame.width = 1280;
        videoFrame.height = 720;
        videoFrame.pixelFormat = TRTCCloudDef.TRTC_VIDEO_PIXEL_FORMAT_Texture_2D;
        videoFrame.bufferType = TRTCCloudDef.TRTC_VIDEO_BUFFER_TYPE_TEXTURE;

        videoFrame.rotation=TRTCCloudDef.TRTC_VIDEO_ROTATION_0;
```

本地截屏
![screen](https://user-images.githubusercontent.com/17918462/75343825-3c86ce00-58d4-11ea-8c00-bcacbb9b89d3.png)

渲染画面 glReadPixels 读取
![582718730476](https://user-images.githubusercontent.com/17918462/75343872-54f6e880-58d4-11ea-9116-c072823dddd2.png)

接收画面
![Screenshot_20200226_200516_com tencent liteav demo](https://user-images.githubusercontent.com/17918462/75344080-c6369b80-58d4-11ea-8995-998b0c55e59b.jpg)

16:9画面被居中裁剪9:16了

**Comment by pdyw** [comment]
TRTCVideoEncParam.videoResolutionMode
TRTCVideoFrame.rotation. 
这两个方法无法改变被裁剪命运

**Comment by kuen229** [comment]
你好，请升级到7.0.8670再试一下
