### ISSUE TITLE
小程序和WEB SDK互通的几个BUG 

### ISSUE THREAD

**Issue by cjd6568358** [tencentyun/TRTCSDK#140]
1.WEB SDK不支持火狐浏览器吗?用了你们的最新SDK和测试demo网址都提示不支持
https://trtc-1252463788.file.myqcloud.com/web/demo/official-demo/index.html?_ga=1.230154972.152242139.1553669308
2.同一房间号 同一ID用户 小程序先进入房间,WEB就无法进入,WEB SDK报错,但是WEB先进入房间,小程序可以正常进入,WEB端提示被踢出
3.小程序端开启关闭麦克风和视频,WEB端会收到该用户的进入房间和退出房间的事件

**Comment by cjd6568358** [comment]
更新下第三点:只要当小程序端麦克风和摄像头都关闭时就会触发WEB SDK的退出房间事件

**Comment by cjd6568358** [comment]
WEB SDK 4.3.8,
小程序最新基础库版本

**Comment by MasterXS** [comment]
1. Web SDK 不支持 firefox，仅支持 Chrome/Safari，可通过 TRTC.checkSystemRequirements() 来判断当前环境是否支持 TRTC
2. 同一个房间内不允许同一个userId 同时登录
3. Web 端的 peer-join/leave 目前不是真正意义上用户进退房通知，若业务层需要房间成员管理，可先考虑集成 Web IM 服务。

**Comment by Cecils** [comment]
> 1.WEB SDK不支持火狐浏览器吗?用了你们的最新SDK和测试demo网址都提示不支持
> https://trtc-1252463788.file.myqcloud.com/web/demo/official-demo/index.html?_ga=1.230154972.152242139.1553669308
> 2.同一房间号 同一ID用户 小程序先进入房间,WEB就无法进入,WEB SDK报错,但是WEB先进入房间,小程序可以正常进入,WEB端提示被踢出
> 3.小程序端开启关闭麦克风和视频,WEB端会收到该用户的进入房间和退出房间的事件

小程序 和 web 互通， web端收到的监听信息不准确 。 小程序关闭摄像头， web端会收到 stream-removed 事件

**Comment by MasterXS** [comment]
> > 1.WEB SDK不支持火狐浏览器吗?用了你们的最新SDK和测试demo网址都提示不支持
> > https://trtc-1252463788.file.myqcloud.com/web/demo/official-demo/index.html?_ga=1.230154972.152242139.1553669308
> > 2.同一房间号 同一ID用户 小程序先进入房间,WEB就无法进入,WEB SDK报错,但是WEB先进入房间,小程序可以正常进入,WEB端提示被踢出
> > 3.小程序端开启关闭麦克风和视频,WEB端会收到该用户的进入房间和退出房间的事件
> 
> 4.3.8版本
> 小程序 和 web 互通， web端收到的监听信息不准确 。 小程序关闭摄像头， web端会收到 stream-removed 事件 ， 小程序端的禁音，监听不到 。

Web SDK 中，stream-added/updated/removed 事件是 远端流 RemoteStream 的生命周期事件，业务逻辑只要正常处理远端流生命周期事件就好，不要根据远端流的生命周期事件去推断远端用户的具体行为，因为各端的具体操作接口并非完全一致。
