### ISSUE TITLE
【Web】-【4.3.1】【远端流 subscribe 成功之后，safari 11 及以上版本浏览器播放远端流视频正常，音频无法播放，必现，Chrome浏览器正常】

### ISSUE THREAD

**Issue by RanX12** [tencentyun/TRTCSDK#142]
【当前现象】
远端流 subscribe 成功之后，safari 11 及以上版本浏览器播放远端流视频正常，音频无法播放，必现，Chrome浏览器正常，浏览器提示警告：
![image](https://user-images.githubusercontent.com/46048444/75409686-68499880-5954-11ea-87a3-b5baf3a81673.png)

【集成包】
TRTC 4.3.1 

【SDKAppID】
1400290949

【房间号】
894399103

【useID】
admin*4，rx*1

【问题时间段】
一直是这样

【之前版本有无此问题】
不知

【复现概率】
必现 

【复现途径】
1. 使用 safari 11 及以上版本与Chrome浏览器进行Web音视频
2. safar 浏览器在 使用 subscribe 订阅远端用户成功之后，进行播放
3. safari 浏览器即可出现 视频播放正常，音频无法播放Bug

【Demo 复现途径】
可复现  
1. 使用 safari浏览器和 chrome 浏览器，
2. 双方进入房间，点击加入房间
3. 等待加入 并推流成功之后，
4. 出现  视频播放正常，音频无法播放Bug

【相关附件】
这是在 https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html 测试截图：
![image](https://user-images.githubusercontent.com/46048444/75410635-7f3dba00-5957-11ea-98f1-315afba6feb7.png)
我在代码中有进行输出 音量大小：
![image](https://user-images.githubusercontent.com/46048444/75410741-d0e64480-5957-11ea-8384-4b6e6a8423dd.png)
但是在 safari 浏览器上没有打印出来：
![image](https://user-images.githubusercontent.com/46048444/75410795-01c67980-5958-11ea-8354-7fb6e3dcbfe3.png)
在 chrome 浏览器上可以播放并打印：
![image](https://user-images.githubusercontent.com/46048444/75410849-2ae70a00-5958-11ea-84f5-6ab7caabd331.png)

safari 11 及以上版本都是这种情况

**Comment by MasterXS** [comment]
请查看 stream.play() 后是否有异常，若有异常可尝试引导用户手动调用 stream.resume() 继续播放。

若是先前调用过 unsubscribe 然后再次 subscribe 的话，Safari本身有兼容性问题，可参见：https://github.com/tencentyun/TRTCSDK/issues/132
