### ISSUE TITLE
【小程序】-【6.5.7272】【小程序引入sdk组件报组件未找到，使用的是wepy的框架】

### ISSUE THREAD

**Issue by best2wazi** [tencentyun/TRTCSDK#143]
【当前现象】
小程序引入sdk组件报组件未找到，使用的是wepy的框架

![11582856295_ pic_hd](https://user-images.githubusercontent.com/21324548/75504540-b8d3fb00-5a13-11ea-828d-f8d19191bc7c.jpg)
![21582856304_ pic](https://user-images.githubusercontent.com/21324548/75504541-ba9dbe80-5a13-11ea-901c-a5439a527c82.jpg)

**Comment by snoobcn** [comment]
最后成功了吗。我们公司也有这个需求。是不是需要改编他们的组件为 wepy的组件

**Comment by best2wazi** [comment]
> 最后成功了吗。我们公司也有这个需求。是不是需要改编他们的组件为 wepy的组件
没有

**Comment by anderlu** [comment]
trtc-room是原生小程序组件，使用其他框架需要做相应的适配改造
