### ISSUE TITLE
【WEB】-【4.3.8】使用TBS X5内核的APP，在一台Android 5.1.1手机上出现“NotReadableError：could not start video source“

### ISSUE THREAD

**Issue by hezhongchen09** [tencentyun/TRTCSDK#146]
使用TBS X5内核的APP，在一台Android 5.1.1手机上出现“NotReadableError：could not start video source“，如下图：
![image](https://user-images.githubusercontent.com/11245938/75680837-59a10f80-5ccd-11ea-8815-f1c2ae54d892.png)

webrtc能力测试完全通过
![Screenshot_2020-03-02-21-47-56](https://user-images.githubusercontent.com/11245938/75682291-24e28780-5cd0-11ea-8ba2-b7949474f1ad.png)

......下图继续

![Screenshot_2020-03-02-21-48-14](https://user-images.githubusercontent.com/11245938/75682307-2c099580-5cd0-11ea-87a2-51a6a84e3cdc.png)

**Comment by MasterXS** [comment]
https://trtc-1252463788.file.myqcloud.com/web/docs/LocalStream.html#initialize
