### ISSUE TITLE
【Electron】-【6.9.138】【使用electron官方react脚手架出现c++断言失败】

### ISSUE THREAD

**Issue by pcgpcgpcg** [tencentyun/TRTCSDK#147]
【当前现象】
采用electron官方脚手架
https://github.com/electron-react-boilerplate/electron-react-boilerplate
通过npm install trtc-electron-sdk
出现无法识别.node文件的错误,手动加入node-loader后再次安装成功.
但是运行时,调用 this.rtcCloud.enterRoom(param, this.appScene)时候,出现
弹出窗口 Assertion failed.
具体见附图

【集成包】
TRTC精简版 
【SDKAppID】
1400291052

【房间号】
123456

【useID】
123456

【问题时间段】
2020-03-02 16:23~22:55

【机型】
windows 10 pro

【之前版本有无此问题】
没用过之前版本，用官方electron vue demo没问题

【复现概率】
必现 

【复现途径】
采用electron官方脚手架
https://github.com/electron-react-boilerplate/electron-react-boilerplate
通过npm install trtc-electron-sdk
出现无法识别.node文件的错误,手动加入node-loader后再次安装成功.
但是运行时,调用 this.rtcCloud.enterRoom(param, this.appScene)时候,出现
弹出窗口 Assertion failed.

【Demo 复现途径】
官方vue demo  正常

【相关附件】
![trtcelectron](https://user-images.githubusercontent.com/5022843/75734481-05c91180-5d33-11ea-81a1-aedd1570d2f7.JPG)

**Comment by james133** [comment]
我也遇到同样的问题，请问能否尽快给出解决办法

**Comment by pcgpcgpcg** [comment]
补充一下，用mac os 也是一样的错误

**Comment by c1avie** [comment]
> 补充一下，用mac os 也是一样的错误

应该是userId传成int型了，改成string字符串试试

**Comment by pcgpcgpcg** [comment]
是因为官方demo  调用store的时候有个陷阱，导致this里面的初始值被置空了
