### ISSUE TITLE
【Android/iOS】-【6.5.7272】android 进视频一分钟左右，上一个界面重建

### ISSUE THREAD

**Issue by yuanmaio** [tencentyun/TRTCSDK#148]
android 进视频一分钟左右，上一个界面重建

**Comment by kuen229** [comment]
您好，请升级到最新版本7.0再试一下。如果还有问题麻烦logcat过滤下当前应用的log，帮忙贴出来我们分析下，谢谢

**Comment by whalehe** [comment]
可以按照这个模板提issue，https://github.com/tencentyun/TRTCSDK/issues/53

如有代码修改，需要您贴下代码，方便我们定位您的问题，然后解决您遇到的问题。
