### ISSUE TITLE
【Electron】-【6.9.138】【引用.node文件时变成了我打包机器的路径】

### ISSUE THREAD

**Issue by jackple** [tencentyun/TRTCSDK#151]
【相关附件】
![image](https://user-images.githubusercontent.com/6183232/76062798-63728d80-5fc1-11ea-9edb-f6deba342f15.png)

**Comment by daihy8759** [comment]
用native-ext-loader

**Comment by jackple** [comment]
@daihy8759 试过还是不行, 可否发下具体配置, 目前我的解决方法是动态require

**Comment by daihy8759** [comment]
## webpack
```js
{
    test: /\.node$/,
    loader: 'native-ext-loader'
},
```
## package.json的配置

```js
"extraFiles": [
    {
         "from": "node_modules/trtc-electron-sdk/build/Release",
         "to": "node_modules/trtc-electron-sdk/build/Release"
    }
],
```
我试了是可以，但是启动的时候起始位置必须是程序目录，也是个头大的问题

**Comment by jackple** [comment]
@daihy8759 反过来倒是可以考虑下动态require，😄

**Comment by daihy8759** [comment]
后来我试了下，其实node-loader就可以，需要从启动的时候起始位置了，加上我那个package.json的配置就行了，动态require需要node_modules要打包进asar吧

**Comment by daihy8759** [comment]
还有一种方式是unpackasar配置原生模块的解压

**Comment by gxdvip** [comment]
> 还有一种方式是unpackasar配置原生模块的解压

这种方式也有问题
![外部打包trtc-electron-sdk](https://user-images.githubusercontent.com/2382401/77146655-85dacf80-6ac6-11ea-97a1-43eec168777e.png)
