### ISSUE TITLE
【iOS】-【6.9.8341】TRTCAppSceneLIVE下，switchRole 问题

### ISSUE THREAD

**Issue by dream4java** [tencentyun/TRTCSDK#152]
'TXLiteAVSDK_TRTC', '~> 6.9.8341' 版本：
在TRTCAppSceneLIVE 模式下，观看端 需要连麦 或者开启摄像头 使用函数
-(void)switchRole:(TRTCRoleType)role;   typedef NS_ENUM(NSInteger, TRTCRoleType) {
    TRTCRoleAnchor            =  20,   ///< 主播
    TRTCRoleAudience          =  21,   ///< 观众
};  切换 为 TRTCRoleAnchor 主播状态时 startLocalPreview 后 报 错误 重进房间出错，看了日志 类似有英文当前 Audience 忽略上传 音频 视频的提示，我随机写了 switchRole:0 ，反而正常了 实验了下 1-19都是正常的 到20就开始失败了

**Comment by tao-pu** [comment]
当前 Audience 忽略上传 音频 视频的提示
----
这个提示是warning级别错误，可以忽略。
您是连续调用 switchRole和startLocalPreview吗？这种情况是切角色还没成功时，调用startLocalPreview会报warning，此waring可以忽略，不影响切换角色后上行推流。
SDK内部切换主播成功后，会自动把数据push到云端。

**Comment by dream4java** [comment]
> ## 当前 Audience 忽略上传 音频 视频的提示
> 这个提示是warning级别错误，可以忽略。
> 您是连续调用 switchRole和startLocalPreview吗？这种情况是切角色还没成功时，调用startLocalPreview会报warning，此waring可以忽略，不影响切换角色后上行推流。
> SDK内部切换主播成功后，会自动把数据push到云端。

使用场景是这样的，在TRTCAppSceneLIVE 模式下，观看端 需要与主播 说话 或者开启摄像头视频，调用switchRole 为 TRTCRoleAnchor 时候， 其他人和主播端 都是看不到 该客户端的 声音 和摄像头数据的，switchRole 后 马上调用了 startLocalPreview，自己可以看到预览画面 可是其他人看不到，当我尝试 switchRole 写死了 0（0-19）的数字 ，发现其他观看端 和主播可以看到该端的视频 和语音，我想问这个sdk定义的枚举值 是否有问题

**Comment by whalehe** [comment]
SDK定义的枚举值：20表示主播，21表示观众，但是建议使用强枚举：参考文档：http://doc.qcloudtrtc.com/group__TRTCCloudDef__ios.html#ggad147b9b0249d0c2759cf1514c8978881acf014ed275bc2cd1f3056838e67f4333
