### ISSUE TITLE
【小程序】-【6.5.7272】【进房失败，组件报空指针】

### ISSUE THREAD

**Issue by slimvan** [tencentyun/TRTCSDK#153]
【当前现象】
如进房失败，提示错误码xxxx

【集成包】
TRTC精简版 / 专业版Professional / 企业版Enterprise

【SDKAppID】
1400XXXXXX

【房间号】
123456

【useID】
userNameA

【问题时间段】
2020-3-7

【机型】
全部机型

【之前版本有无此问题】
不确定

【复现概率】
必现

【复现途径】

设置好trtcConfig的各项参数后，报错如图，导致进房失败，页面空白。注释掉红框中的代码恢复正常

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等
![image](https://user-images.githubusercontent.com/17959299/76138554-5e2a4700-6084-11ea-9987-fe47d92c3837.png)
![image](https://user-images.githubusercontent.com/17959299/76138563-7ef29c80-6084-11ea-9358-05832418a9d0.png)

**Comment by anderlu** [comment]
初始化组件传入的参数 key 能否提供一下。

**Comment by slimvan** [comment]
不好意思，您指的是哪个key？

**Comment by anderlu** [comment]
![image](https://user-images.githubusercontent.com/1832616/77027953-86923980-69d2-11ea-9e51-3d82c1252e38.png)
非常抱歉，是指设置了哪些参数，我们需要重现一下，我们测试没有遇到这个问题。

**Comment by raomx** [comment]
> ![image](https://user-images.githubusercontent.com/1832616/77027953-86923980-69d2-11ea-9e51-3d82c1252e38.png)
> 非常抱歉，是指设置了哪些参数，我们需要重现一下，我们测试没有遇到这个问题。

能帮忙远程看一下吗？我微信号：dogdaydoglife，谢谢了

**Comment by anderlu** [comment]
只需要确认 trtcConfig传入的参数是和 demo的一致，如果是缺少 sdkappid是会有提示的。

**Comment by slimvan** [comment]
好的。暂时没出现这个问题了
