### ISSUE TITLE
【小程序】-【6.9 @ 2020.03.08】【进房失败，roomid、groupid数据类型问题】

### ISSUE THREAD

**Issue by apple1929** [tencentyun/TRTCSDK#155]
【当前现象】
获取roomsig失败
TRTC-ROOM enterRoom error 
* room joinRoom 进房失败

【集成包】
TRTC精简版

【SDKAppID】
1400320040

【房间号】
SNIDF36ESTJ

【useID】
测试用户

【问题时间段】
2020-03-08

【机型】
微信开发工具

【之前版本有无此问题】
新项目

【复现概率】
必现

【复现途径】
1. 调用https://official.opensso.tencent-cloud.com/v4/openim/jsonvideoapp?sdkappid=1400320040&identifier=测试用户&usersig=eJyrVgrxCdYrSy1SslIy0jNQ0gHzM1NS80oy0zLBws*2dr9YP-
2. 调用 room://cloud.tencent.com?sdkappid=1400320040&roomid=SNIDF36ESTJ&userid=测试用户&roomsig=%7B%7D
5. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等
[https://images.gitee.com/uploads/images/2020/0308/134620_68f6c386_5365417.jpeg](url)

**Comment by anderlu** [comment]
房间号目前不支持 string 类型

**Comment by xjr100419** [comment]
现在 还不支持string 类型么。那其他端 用了 string 类型怎么用
