### ISSUE TITLE
【前端】-【6.5.7272】【trtc-js-sdk包里面存在箭头函数，uglify压缩失败】

### ISSUE THREAD

**Issue by tinys** [tencentyun/TRTCSDK#156]
【当前现象】
trtc-js-sdk包里面存在箭头函数，uglify压缩失败

【集成包】
TRTC精简版

【SDKAppID】
1400XXXXXX

【房间号】
123456

【useID】
userNameA

【问题时间段】
2020-03-09 16:23~16:55

【机型】
构建问题

【之前版本有无此问题】

【复现概率】
必现 / 偶现(如有大约概率请标明)

【复现途径】
npm i  trtc-js-sdk

【Demo 复现途径】
查看从npm下载的包，里面存在箭头函数

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by MasterXS** [comment]
@anderlu any thoughts?

**Comment by anderlu** [comment]
请用支持es6 的压缩工具，建议使用terser
