### ISSUE TITLE
web部署服务器sdk报错

### ISSUE THREAD

**Issue by Isaac-chip** [tencentyun/TRTCSDK#157]
![image](https://user-images.githubusercontent.com/42114454/76203146-1c8acf00-6231-11ea-8be4-ae790d98bf45.png)
服务器链接:http://mp.aged.atianqi.com/yljh5/yltv/video_1.html?openid=1816e5a00f8d46cbb146b7825e996cde&iid=347

服务器是http协议 请问和协议有关嘛?

**Comment by MasterXS** [comment]
这是浏览器的安全限制，请务必使用 https:// 或 localhost访问
