### ISSUE TITLE
【小程序】-【6.5.7272】【直播模式下，观众如何切换手机听筒或外放播放声音？】

### ISSUE THREAD

**Issue by javacms** [tencentyun/TRTCSDK#158]
【当前现象】
小程序<trtc-room>组件属性scene=live开启直播模式，观众默认为手机外放播放声音，在<trtc-room>组件的trtc-room.js中看到有_toggleSoundMode方法切换soundMode为'ear'或'speaker'，但实际并未起效。
这个需要怎么操作？

**Comment by anderlu** [comment]
能否提供机型和微信版本信息？目前trtc-room 组件尚未提供player 切换声音播放类型的api，预计3月底提供api。
