### ISSUE TITLE
【WEb】-【6.5.7272】【问题简述，如进房失败，提示错误码"本地流发布失败 RtcError: please call join() before publish()"】

### ISSUE THREAD

**Issue by yeyue-wyb** [tencentyun/TRTCSDK#159]
【当前现象】
进房失败，提示错误码"本地流发布失败 RtcError: please call join() before publish()"，PC端发起视频邀请，手机端接到请求，并确认，pc端摄像头可以打开，没有弹出视频页面，控制台报错。

【集成包】
Tutorial: 基础音视频通话

【复现概率】
每次发起视频都不成功

【相关附件】
![image](https://user-images.githubusercontent.com/53936508/76379471-20caff80-638b-11ea-99c4-0bc898197b97.png)；
![image](https://user-images.githubusercontent.com/53936508/76379599-743d4d80-638b-11ea-9f51-b6f403f3f63e.png)；
![image](https://user-images.githubusercontent.com/53936508/76379645-9cc54780-638b-11ea-8ae8-c187c6df87c8.png)

**Comment by MasterXS** [comment]
上面这个错误表明应用代码业务逻辑有错误，在没有成功调用 Client.join() 的前提下调用了 Client.publish()自然会报错。请检查您的代码逻辑。
