### ISSUE TITLE
【web/electron】- 有计划使用 typescript 构建 sdk 么？

### ISSUE THREAD

**Issue by rxliuli** [tencentyun/TRTCSDK#162]
【当前现象】

目前使用 js 的 npm 包安装之后，在 ts 中使用相当不便，因为完全没有 `.d.ts` 定义，导致即便使用了 ts，也仍然需要查看文档才能知道各个 API 的参数和返回值，对于使用是极其不便的。对于 sdk 而言，使用 ts 对后期维护也有帮助。

**Comment by daihy8759** [comment]
确实，+1

**Comment by yangq1990** [comment]
trtc.d.ts 会在接下来的版本中提供，敬请关注

**Comment by rxliuli** [comment]
> trtc.d.ts 会在接下来的版本中提供，敬请关注

事实上，目前不得已之下吾辈已经复制/声明了超过 480 行的 .d.ts 类型定义了。。。（真的希望能尽快出一个官方全功能的版本，另外之后最好用 ts 重构，保持 .d.ts 与 jsdoc 的完全同步）#无奈

![image](https://user-images.githubusercontent.com/24560368/77024535-c6a0ee80-69c9-11ea-8616-76f3cc0ec5ae.png)

**Comment by rxliuli** [comment]
这是吾辈目前用到的，如果有人需要的话。。。

[trtc-electron-sdk.d.zip](https://github.com/tencentyun/TRTCSDK/files/4352332/trtc-electron-sdk.d.zip)

**Comment by daihy8759** [comment]
好生气，以为7.0.149加了d.ts就可用，结果。。。这东西发上来感觉都没认真测试。还是老老实实不升级，用自己写的。

**Comment by rxliuli** [comment]
> 好生气，以为 7.0.149 加了 d.ts 就可用，结果。。。这东西发上来感觉都没认真测试。还是老老实实不升级，用自己写的。

本来就是吾辈在项目里直接写的，能在吾辈用的 `6.9.138` 这个版本正常就行，这种私有的云服务谁会去为他们免费写这些东西呢？

**Comment by yangq1990** [comment]
> 好生气，以为7.0.149加了d.ts就可用，结果。。。这东西发上来感觉都没认真测试。还是老老实实不升级，用自己写的。

请问遇到了什么问题么？

// 开启 ES Module 融合模式 (esModuleInterop=true)
import * as trtc_namespace from 'trtc-electron-sdk';

// 引入TRTCCloud
const TRTCCloud = require('trtc-electron-sdk');

const rtcCloud: trtc_namespace.TRTCCloud = new TRTCCloud();
// 1.进房参数
let param: trtc_namespace.TRTCParams = new TRTCParams();
param.sdkAppId = 1400188366;
param.roomId = 136;
param.userId = "997129";
param.userSig = "";
param.privateMapKey = '';
param.businessInfo = '';
let role: trtc_namespace.TRTCRoleType = TRTCRoleType.TRTCRoleAnchor;
param.role = role;
param.streamId = '';
let scene: trtc_namespace.TRTCAppScene = TRTCAppScene.TRTCAppSceneVideoCall;
rtcCloud.enterRoom(param, scene);

请问这样不可以么

**Comment by yangq1990** [comment]
![image](https://user-images.githubusercontent.com/6194380/77134984-7a76ac80-6aa4-11ea-8ceb-d5922d4c14fd.png)

**Comment by daihy8759** [comment]
为什么要加trtc_namespace呢，我们会为更新一个定义，然后去改一遍代码吗，考虑下typescript用户

**Comment by daihy8759** [comment]
以我个人的观点，如果升级这个小版本导致用户代码会报错，都属于破坏性改动了。要么把这个定义发到@types/trtc-electron-sdk，避免影响客户的代码。楼上的d.ts不是写的挺好的吗，完善一下不行么

**Comment by rxliuli** [comment]
> 以我个人的观点，如果升级这个小版本导致用户代码会报错，都属于破坏性改动了。要么把这个定义发到 @types/trtc-electron-sdk，避免影响客户的代码。楼上的 d.ts 不是写的挺好的吗，完善一下不行么

之所以加 namespace 的原因是因为 trtc export 了两个文件，所以需要用 namespace 进行区分，另外吾辈本身就是 ts 用户，所以才会说“不得已”之下写了这么多 `.d.ts` 的

![image](https://user-images.githubusercontent.com/24560368/77137246-135af700-6aa8-11ea-8e3c-eb1a2889cd87.png)

**Comment by rxliuli** [comment]
吾辈目前这么使用还没报什么错误

![image](https://user-images.githubusercontent.com/24560368/77137316-5917bf80-6aa8-11ea-8214-62a7e72d6fb9.png)

**Comment by daihy8759** [comment]
> > 以我个人的观点，如果升级这个小版本导致用户代码会报错，都属于破坏性改动了。要么把这个定义发到 @types/trtc-electron-sdk，避免影响客户的代码。楼上的 d.ts 不是写的挺好的吗，完善一下不行么
> 
> 之所以加 namespace 的原因是因为 trtc export 了两个文件，所以需要用 namespace 进行区分，另外吾辈本身就是 ts 用户，所以才会说“不得已”之下写了这么多 `.d.ts` 的
> 
> ![image](https://user-images.githubusercontent.com/24560368/77137246-135af700-6aa8-11ea-8e3c-eb1a2889cd87.png)

我说的是官方发布的7.0.149

**Comment by yangq1990** [comment]
> 以我个人的观点，如果升级这个小版本导致用户代码会报错，都属于破坏性改动了。要么把这个定义发到@types/trtc-electron-sdk，避免影响客户的代码。楼上的d.ts不是写的挺好的吗，完善一下不行么

请问代码报什么错了，如果不想要代码提示，保留原来的写法就可以了。想要代码提示的，可以在声明时加上类型，这正是为了向前兼容，同时考虑到存量的js和ts开发者

**Comment by rxliuli** [comment]
> 以我个人的观点，如果升级这个小版本导致用户代码会报错，都属于破坏性改动了。要么把这个定义发到 @types/trtc-electron-sdk，避免影响客户的代码。楼上的 d.ts 不是写的挺好的吗，完善一下不行么

另外这很花时间，真的，很花时间。。。如果要保持同步（与国内的 sdk 同步。。。），就更难了

**Comment by daihy8759** [comment]
那为啥不一劳永逸的用ts呢。。

**Comment by rxliuli** [comment]
> 那为啥不一劳永逸的用 ts 呢。。

因为你不能说服全世界所有人都用 ts！

**Comment by yangq1990** [comment]
> 那为啥不一劳永逸的用ts呢。。

ts有他的优点，js也有很多优点啊。我们有在规划用ts重写，对于这种大型项目，还涉及到跨平台的，速度没那么快。目前已经有不少业务在用js接入了，所以我们要同时照顾到js和ts开发者，不能厚此薄彼，也不能顾此失彼。上周收到issue，我们本周就赶紧把 d.ts 加上，在加的过程中，还处理了不少细节问题，如果使用过程中有遇到具体的问题，欢迎继续就问题反馈，我们会第一时间响应处理

**Comment by daihy8759** [comment]
> > 以我个人的观点，如果升级这个小版本导致用户代码会报错，都属于破坏性改动了。要么把这个定义发到@types/trtc-electron-sdk，避免影响客户的代码。楼上的d.ts不是写的挺好的吗，完善一下不行么
> 
> 请问代码报什么错了，如果不想要代码提示，保留原来的写法就可以了。想要代码提示的，可以在声明时加上类型，这正是为了向前兼容，同时考虑到存量的js和ts开发者

确切来说是tslint报错
![image](https://user-images.githubusercontent.com/6057326/77137453-04287900-6aa9-11ea-9f61-26873fdb09a8.png)

**Comment by yangq1990** [comment]
> > > 以我个人的观点，如果升级这个小版本导致用户代码会报错，都属于破坏性改动了。要么把这个定义发到@types/trtc-electron-sdk，避免影响客户的代码。楼上的d.ts不是写的挺好的吗，完善一下不行么
> > 
> > 
> > 请问代码报什么错了，如果不想要代码提示，保留原来的写法就可以了。想要代码提示的，可以在声明时加上类型，这正是为了向前兼容，同时考虑到存量的js和ts开发者
> 
> 确切来说是tslint报错
> ![image](https://user-images.githubusercontent.com/6057326/77137453-04287900-6aa9-11ea-9f61-26873fdb09a8.png)

需要注意一个点：TRTCCloud 是 commonjs 模块（最开始的版本就是如此，我们升级要向前兼容，考虑到已接入用户的使用方式）
所以引入的时候是
```javascript
const TRTCCloud = require('trtc-electron-sdk');
```

如果想要类型提示
```javascript
import * as trtc_namespace from 'trtc-electron-sdk';
const rtcCloud: trtc_namespace.TRTCCloud = new TRTCCloud();
```

**Comment by daihy8759** [comment]
> > 好生气，以为 7.0.149 加了 d.ts 就可用，结果。。。这东西发上来感觉都没认真测试。还是老老实实不升级，用自己写的。
> 
> 本来就是吾辈在项目里直接写的，能在吾辈用的 `6.9.138` 这个版本正常就行，这种私有的云服务谁会去为他们免费写这些东西呢？

你没发你的版本之前，我也已经根据trtc.js里面的写的d.ts，只是想着官方的能保证API的同步，不想折腾

**Comment by yangq1990** [comment]
> > > 以我个人的观点，如果升级这个小版本导致用户代码会报错，都属于破坏性改动了。要么把这个定义发到@types/trtc-electron-sdk，避免影响客户的代码。楼上的d.ts不是写的挺好的吗，完善一下不行么
> > 
> > 
> > 请问代码报什么错了，如果不想要代码提示，保留原来的写法就可以了。想要代码提示的，可以在声明时加上类型，这正是为了向前兼容，同时考虑到存量的js和ts开发者
> 
> 确切来说是tslint报错
> ![image](https://user-images.githubusercontent.com/6057326/77137453-04287900-6aa9-11ea-9f61-26873fdb09a8.png)

需要注意一个点：TRTCCloud 是 commonjs 模块（最开始的版本就是如此，我们升级要向前兼容，考虑到已接入用户的使用方式）
所以引入的时候是

```javascript
const TRTCCloud = require('trtc-electron-sdk');
const rtcCloud = new TRTCCloud()
```
如果想要类型提示
```javascript
// 开启 ES Module 融合模式 (esModuleInterop=true)
import * as trtc_namespace from 'trtc-electron-sdk';
const rtcCloud: trtc_namespace.TRTCCloud = new TRTCCloud();
```

**Comment by rxliuli** [comment]
> > > > 以我个人的观点，如果升级这个小版本导致用户代码会报错，都属于破坏性改动了。要么把这个定义发到 @types/trtc-electron-sdk，避免影响客户的代码。楼上的 d.ts 不是写的挺好的吗，完善一下不行么
> > > 
> > > 
> > > 请问代码报什么错了，如果不想要代码提示，保留原来的写法就可以了。想要代码提示的，可以在声明时加上类型，这正是为了向前兼容，同时考虑到存量的 js 和 ts 开发者
> > 
> > 
> > 确切来说是 tslint 报错
> > ![image](https://user-images.githubusercontent.com/6057326/77137453-04287900-6aa9-11ea-9f61-26873fdb09a8.png)
> 
> 需要注意一个点：TRTCCloud 是 commonjs 模块（最开始的版本就是如此，我们升级要向前兼容，考虑到已接入用户的使用方式）
> 所以引入的时候是
> 
> ```js
> const TRTCCloud = require('trtc-electron-sdk');
> const rtcCloud = new TRTCCloud()
> ```
> 
> 如果想要类型提示
> 
> ```js
> // 开启 ES Module 融合模式 (esModuleInterop=true)
> import * as trtc_namespace from 'trtc-electron-sdk';
> const rtcCloud: trtc_namespace.TRTCCloud = new TRTCCloud();
> ```

这。。。我们不是在说 Electron 的 sdk 么？

**Comment by rxliuli** [comment]
好吧，兼容却是没办法的呢 #笑哭

**Comment by daihy8759** [comment]
能用就行吧，毕竟不是刚需。优先sdk问题吧，比如
rtcCloud.setCurrentCameraDevice 
rtcCloud.getCurrentCameraDevice 
startLocalPreview
这个不是setCurrentCameraDevice不是立即生效的，得startLocalPreview然后setCurrentCameraDevice才行，文档都没体现，有时候切换摄像头黑屏，也不知道为啥

**Comment by yangq1990** [comment]
> 好吧，兼容却是没办法的呢 #笑哭

兼容本来就是一件不容易的事，要考虑存量的、增量的的各种诉求。而且我们的客户往往都是付了很多钱的，更要慎重，如果是免费的开源项目，我们完全可以看着不爽就来个 breaking change。。。所以还请各位开发者谅解，虽然说不破不立，可是破和立的空窗期谁来负责填呢？有序地逐步完善，我们认为是目前更稳妥和更适合的策略

**Comment by yangq1990** [comment]
> 能用就行吧，毕竟不是刚需。优先sdk问题吧，比如
> rtcCloud.setCurrentCameraDevice
> rtcCloud.getCurrentCameraDevice
> startLocalPreview
> 这个不是setCurrentCameraDevice不是立即生效的，得startLocalPreview然后setCurrentCameraDevice才行，文档都没体现，有时候切换摄像头黑屏，也不知道为啥

收到反馈，我这边同步给其他同学。建议一个issue一个主题哈，如果有新的问题，请开一个新的issue，避免问题遗漏

**Comment by daihy8759** [comment]
没提这些issue主要是对业务没有太大的影响，而且有些问题沟通起来确实困难，比如那个混流的issue还没给出是sdk的问题，你们也不会对issue打标记，说明是sdk的bug还是用户的问题。还有建议版本发布描述下解决了什么问题，新增了什么功能，现在对用户来说就是个黑洞。

**Comment by yangq1990** [comment]
> 没提这些issue主要是对业务没有太大的影响，而且有些问题沟通起来确实困难，比如那个混流的issue还没给出是sdk的问题，你们也不会对issue打标记，说明是sdk的bug还是用户的问题。还有建议版本发布描述下解决了什么问题，新增了什么功能，现在对用户来说就是个黑洞。

谢谢建议，我反馈下
