### ISSUE TITLE
【Web】-【官方demo】【踢人或者同用户重复登录返回了错误的信息】

### ISSUE THREAD

**Issue by JackyTianer** [tencentyun/TRTCSDK#163]
【当前现象】
使用官方提供的demo
https://trtc-1252463788.file.myqcloud.com/web/demo/official-demo/index.html
打开两个页面，输入相同的用户id,和房间号
进入后，发现并没有触发`client-banned`事件，而是触发了`error`事件
【房间号】
任意，只要保持一致即可

【useID】
任意，只要保持一致即可

【问题时间段】
任何事件

【机型】
Macbook Pro 2018;Chrome:80

【复现概率】
必现 

【Demo 复现途径】
可复现  
1. 进入demo地址
2. 用两个页面打开输入相同的用户id和房间号，观察第一个页面的websocket返回值，发现返回了
```
{cmd:8 content:{type:"logout"}}
```
3. 对比sdk源码，cmd 8中并没有处理logout类型，因此抛出事件error,不过这里也应该是type:"kick"才正确

**Comment by MasterXS** [comment]
同名用户同时登录是不允许的行为，是应用业务逻辑错误，此时可能会引发双方通话异常，房间内用户状态的管理请走IM SDK 或者其他信令机制。

**Comment by xiaosongxiaosong** [comment]
@MasterXS 他这个问题的意思是后台触发了 client-banned ，但是 SDK 中没有上报到 client 中，我使用   4.3.8 版本的 SDK 也有这个问题

![image](https://user-images.githubusercontent.com/2703455/77716218-9a641e00-7018-11ea-9deb-11b80ba136e9.png)

可以看到 sdk 的日志中 已经收到了 client-banned 事件，但是 client 并不会上报 client-banned 事件

调用代码：
```js
    this.client = TRTC.createClient({ mode: 'live', sdkAppId, userId, userSig });
    // some code
    this.client.on('client-banned', () => {
      RTC.errorLog(`RTC: client banned`);
      this.emitter.emit('rtc.kickedout');
    });
    this.client.on('error', errMsg => {
      RTC.errorLog(`RTC: client error observed, error code (${errMsg.getCode()}), ${errMsg}`);
      this.emitter.emit('rtc.error', errMsg);
    });
```

**Comment by MasterXS** [comment]
那是内部信令名字命名问题，它并不是真正的client banned。互踢是业务逻辑错误，这个要避免。
https://trtc-1252463788.file.myqcloud.com/web/docs/module-Event.html#.CLIENT_BANNED
需要房间内成员状态管理请使用 WebIM SDK

**Comment by xiaosongxiaosong** [comment]
@MasterXS  非常感谢抽时间回复！

我的理解是业务侧应该避免这种情况发生，但是没有办法能够保证这种情况不出现，此时SDK也应该上报事件，交给上层进行处理

而且看 client banned 的文档说明，这种情况下是会触发 client banned 事件上报的

因为我这边后端还在开发，后面回去主动调接口踢出用户，也就是文档中的第二种情况，不确定到时候这个事件是否能够正常上报

![image](https://user-images.githubusercontent.com/2703455/77726582-33a02e00-7033-11ea-90c2-2528859b9607.png)

**Comment by MasterXS** [comment]
> @MasterXS 非常感谢抽时间回复！
> 
> 我的理解是业务侧应该避免这种情况发生，但是没有办法能够保证这种情况不出现，此时SDK也应该上报事件，交给上层进行处理
> 
> 而且看 client banned 的文档说明，这种情况下是会触发 client banned 事件上报的
> 
> 因为我这边后端还在开发，后面回去主动调接口踢出用户，也就是文档中的第二种情况，不确定到时候这个事件是否能够正常上报
> 
> ![image](https://user-images.githubusercontent.com/2703455/77726582-33a02e00-7033-11ea-90c2-2528859b9607.png)

我们的后台信令服务器集群没有全局状态同步管理，若两个用户同时登录到一台服务器上那能够保证“client-banned”被触发，若登录到不同服务器上，后台集群状态就会异常，所以这时候可能会通过 on("error") 触发异常。

通过服务器端API能够移除指定用户 - https://cloud.tencent.com/document/product/647/40496
