### ISSUE TITLE
【WXMini】-【7.0 @ 2020.03.09】【进房失败】

### ISSUE THREAD

**Issue by goHaoliyou** [tencentyun/TRTCSDK#165]
【wxmini】-【 7.0 @ 2020.03.09】进房失败，调试模式显示有错误

【当前现象】：进双人通话，显示等待接通中...
【集成包】：TRTC 
【SDKAppID】：1400XXXXXX
【房间号】: 123456
【useID】：
【问题时间段】：新的版本
【机型】：米9
【之前版本有无此问题】：之前没有
【是否必现】：我必现
【复现方法】：
【日志或者描述、截图】：截图
![图片](https://user-images.githubusercontent.com/27000085/76637596-0610aa80-6586-11ea-95e0-b0e06ba7b0b3.png)
![图片](https://user-images.githubusercontent.com/27000085/76637627-0e68e580-6586-11ea-8d57-9e830cdf02eb.png)
![图片](https://user-images.githubusercontent.com/27000085/76637667-204a8880-6586-11ea-987f-634d2f943066.png)

**Comment by anderlu** [comment]
![image](https://user-images.githubusercontent.com/1832616/76718711-8c89df80-6772-11ea-825f-abc682b4ea66.png)
这个错误是 live puser 标签渲染失败了，可以尝试删除小程序重新打开。

**Comment by raomx** [comment]
我也是这种状态，但没有live-pusher渲染失败

**Comment by SaxonGao-SZ** [comment]
方便提供一下复现路径吗？

**Comment by RedMaxOo** [comment]
需要去小程序后台打开实时渲染音视频的组件

**Comment by anderlu** [comment]
https://cloud.tencent.com/document/product/647/32399 ， 你的小程序没有开通实时音视频能力，
![image](https://user-images.githubusercontent.com/1832616/82625886-eac2bb00-9c18-11ea-9f78-616446ebd3e7.png)
