### ISSUE TITLE
【Windows C#】-【6.9】【对方进入房间导致本方退出房间，exit reason: 2】

### ISSUE THREAD

**Issue by jingsong-liu** [tencentyun/TRTCSDK#166]
【当前现象】
对方进入房间导致本方退出房间，exit reason: 2

【集成包】
TRTC精简版

【SDKAppID】
1400238197

【问题时间段】
2020-03-15 23:10~23:55

【机型】
Windows PC X64

【复现概率】
必现

【复现途径】
1. 本方调用以userId1和Sign1的签名调用EnterRoom进入房间A，进房成功.
2. 对方调用以userId2和Sign2的签名调用EnterRoom进入房间B， 进房成功.
3. 对方调用ExitRoom退出房间B，退房成功.
4. 对方以userId2和Sign3的签名调用EnterRoom进入房间A，进房成功.
5. 出现 Bug: 本方**自动退出房间**, 收到onExitRoom回调, reason代码为2.
【Demo 复现途径】
不可复现

【相关附件】
**场景说明：**
 这是用户切换通话的场景，大概过程过程如下：
用户1-----进房间A-----------------------------------异常退出(reason:2)
用户2-----进房间B----退出房间B-----进房间A-----正常进入

**日志**
请搜索关键词`exit room: reason`
[log.txt](https://github.com/tencentyun/TRTCSDK/files/4334453/rsalog.151.txt)

**相关线索**
- TRTC文档中描述退房reason=2的意义是房间被解散，不清楚为什么会解散和什么情况下会解散，因为A全程没有离开过房间。
- trtc日志中有提到: kick out room by business

请尽快支持~

**Comment by jingsong-liu** [comment]
添加远端用户user2的日志：
[trtclogs.zip](https://github.com/tencentyun/TRTCSDK/files/4342964/trtclogs.zip)

说明：
这份日志采样于最近复现BUG的通话，并且我已经将远端的SDK升级到7.0版本，测试结果是依然出现同样的问题。

**Comment by tao-pu** [comment]
您好，感谢您的反馈。
我们先排查确认下，稍后答复

**Comment by tao-pu** [comment]
后台信息看到有调用解散房间的log，请问在您的业务逻辑中是否调用了这个REST API：
https://cloud.tencent.com/document/api/647/37088

**Comment by jingsong-liu** [comment]
非常感谢！刚刚询问过后台的同事，我们确实调用了解散房间的API。现在问题已经解决！

Best Regards

发件人: tao-pu<mailto:notifications@github.com>
发送时间: 2020年3月18日 23:27
收件人: tencentyun/TRTCSDK<mailto:TRTCSDK@noreply.github.com>
抄送: Song<mailto:song.lj@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [tencentyun/TRTCSDK] 【Windows C#】-【6.9】【对方进入房间导致本方退出房间，exit reason: 2】 (#166)


后台信息看到有调用解散房间的log，请问在您的业务逻辑中是否调用了这个REST API：
https://cloud.tencent.com/document/api/647/37088

―
