### ISSUE TITLE
【小程序】-【6.5.7272】【问题简述，推流端退后台，拉流端听不到声音】

### ISSUE THREAD

**Issue by yytm** [tencentyun/TRTCSDK#168]
【当前现象】
如进房失败，提示错误码xxxx

【集成包】
TRTC精简版 / 专业版Professional / 企业版Enterprise

【SDKAppID】
1400XXXXXX

【房间号】
123456

【useID】
userNameA

【问题时间段】
2019-09-01 16:23~16:55

【机型】
如iPhone 7 Plus

【之前版本有无此问题】
如6.4之前没有，6.6有

【复现概率】
必现 / 偶现(如有大约概率请标明)

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 在 ... 回调中调用 ...
4. 在 ... 回调中调用 ...
5. 出现 Bug

【Demo 复现途径】
可复现  / 不可复现
1. 点击 ...
2. 进入 ..
3. 等待 ...
4. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by tao-pu** [comment]
麻烦再详细描述下问题信息，是哪个平台iOS 或 Android
是小程序还是native，如果是小程序，请提供微信版本号
native app，请提供下log
6.5版本比较旧了，请升级最新版本验证问题是否依旧

**Comment by yytm** [comment]
小程序的，微信版本7.0.10，是偶现的，另外想问下这个推流端退后台拉流还能听到声音是如何实现的，小程序的原生组件能实现吗

**Comment by anderlu** [comment]
微信原生控制，目前小程序上层无法控制
