### ISSUE TITLE
H5端没有摄像头时，android端onUserEnter和onUserExit不会回调

### ISSUE THREAD

**Issue by liunewshine** [tencentyun/TRTCSDK#17]
当h5端有摄像头时一切正常，但是当h5端没有摄像头进房后，可以看见android端视频，但是android中的onUserEnter和onUserExit不会回调

**Comment by shengcui2018** [comment]
如果没有音视频数据上行，是没有onUserEnter和onUserExit的。

**Comment by liunewshine** [comment]
@shengcui2018 但实际上用户时加入房间成功的，这两个方式是用户进房和退房接口，不应该必须有音视频数据才调用才对。

**Comment by shengcui2018** [comment]
这里可以理解为音视频用户的进退房，目前没有单纯的房间进退回调。
