### ISSUE TITLE
【web】-【4.3.6】【自己编译了开发版本chromium浏览器，调用sdk提示不支持webrtc】

### ISSUE THREAD

**Issue by lionshan** [tencentyun/TRTCSDK#170]
【当前现象】
使用自己编译的chromium浏览器83版本，支持webrtc所有接口，但是环境检测无法通过，导致调用sdk失败。

【集成包】
TRTC精简版
【SDKAppID】
1400286718

【房间号】
任意

【useID】
userNameA

【问题时间段】

【机型】
window10

【之前版本有无此问题】
都有

【复现概率】
必现 

【复现途径】
使用自己的编译的谷歌浏览器调用demo或者环境检测demo 

【Demo 复现途径】

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

请问有没有地方取消sdk的环境检测，为什么支持webrtc但是检测的时候无法通过

**Comment by MasterXS** [comment]
这说明你自己编译出来的 chromium 不支持 WebRTC + h264编解码，请更新 chromium 的编译选项，参考：

is_official_build = true
proprietary_codecs = true
ffmpeg_branding = "Chrome"

**Comment by lionshan** [comment]
使用您提供的参数重新编译了浏览器，测试https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html这个页面全部通过了，可是测试在线https://trtc-1252463788.file.myqcloud.com/web/demo/official-demo/index.html?_ga=1.53797228.572779130.1568709703  这个demo还是出现了报错，getUserMedia error observed。请问trtc对于原生的getUserMedia进行复写后还需要哪些支持吗？怎么才能编译出可以使用的浏览器支持音视频的sdk呢？

**Comment by MasterXS** [comment]
是什么error？OverContraintsError? 请检查是否授予了页面访问权限。TRTC 直接使用 getUserMedia 接口访问摄像头，demo 中会先获取 camera/microphone deviceId, 请检查 deviceId 是否为空。
建议把chromium本地缓存数据清理干净再试。

**Comment by lionshan** [comment]
![31584684626_ pic_hd](https://user-images.githubusercontent.com/27806310/77141604-7c4a6b00-6ab8-11ea-9733-d300e835cdde.jpg)

**Comment by lionshan** [comment]
我自己编译的浏览器手动设置允许摄像机和麦克风后可以正常使用，但是奇怪的是默认是弹窗询问，使用官网demo的时候却不会弹窗，只会直接报错上图。请问您知道什么原因吗，使用测试网页的时候就会正常弹窗询问。

**Comment by MasterXS** [comment]
不弹窗那肯定是浏览器有异常。我建议你从头开始编译一个新版本，把 out 整个目录删掉重新编译。

**Comment by lionshan** [comment]
好的，感谢
