### ISSUE TITLE
【微信小程序demo】-【打不开摄像头】

### ISSUE THREAD

**Issue by raomx** [tencentyun/TRTCSDK#171]
【MacOS】-【10.14.6】打不开摄像头，debug状态enableCamera为false，调整为true也打不开

【当前现象】：提示“群组 ID 非法，请检查群组 ID 是否填写正确。, groupID:1222”
【集成包】：运行微信小程序demo
【SDKAppID】：1400333938
【机型】：MacOS 10.14.6
【之前版本有无此问题】：一直都是这种状态
【是否必现】：必现

**Comment by raomx** [comment]
能帮忙远程看一下吗？我微信号：dogdaydoglife，谢谢了

**Comment by anderlu** [comment]
桌面端小程序？
