### ISSUE TITLE
【iOS】-【6.6】【进房失败】

### ISSUE THREAD

**Issue by LaoWangInNear** [tencentyun/TRTCSDK#173]
【当前现象】
进房失败，在此方法中回掉（- (void)onError:(TXLiteAVError)errCode errMsg:(nullable NSString )errMsg extInfo:(nullable NSDictionary)extInfo {}）

【集成包】
TRTC精简版

【SDKAppID】
1400158389

【房间号】
0319100029

【useID】
bn2b_user_pdairportxy001

【问题时间段】
2020-03-18 ～ 2020-03-19 两天之间

【机型】
iPad Pro 2019款（12.9）

【之前版本有无此问题】
之前没有这个问题，iOS系统升级到13.3之后出现的

【复现概率】
目前必现
【复现途径】

[[TRTCCloud sharedInstance] enterRoom:params appScene:TRTCAppSceneVideoCall];
2.代理回调- (void)onError:(TXLiteAVError)errCode errMsg:(nullable NSString )errMsg extInfo:(nullable NSDictionary)extInfo {}
【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by whalehe** [comment]
您好，可以用最新版本试试，另外最好附上全量日志，方便我们看下上下文，定位和解决您的问题
