### ISSUE TITLE
【小程序】-【6.5.7272】【小程序事件没有回调】

### ISSUE THREAD

**Issue by slimvan** [tencentyun/TRTCSDK#174]
【当前现象】
如进房失败，提示错误码xxxx

【集成包】
TRTC精简版 / 专业版Professional / 企业版Enterprise

【SDKAppID】
1400XXXXXX

【房间号】
123456

【useID】
userNameA

【问题时间段】
2019-09-01 16:23~16:55

【机型】
如iPhone 7 Plus

【之前版本有无此问题】
如6.4之前没有，6.6有

【复现概率】
必现 / 偶现(如有大约概率请标明)

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 在 ... 回调中调用 ...
4. 在 ... 回调中调用 ...
5. 出现 Bug

【Demo 复现途径】

进房成功，但是在enterRoom之前注册的监听事件都无效。

 let trtcRoomContext = this.selectComponent('#trtc-room')
      let EVENT = trtcRoomContext.EVENT

      if (trtcRoomContext) {
        // 发布本地音频流和视频流
        trtcRoomContext.publishLocalVideo()
        trtcRoomContext.publishLocalAudio()

        // 监听远端用户的视频流的变更事件
        trtcRoomContext.on(EVENT.REMOTE_VIDEO_ADD, (event) => {
          // 订阅（即播放）远端用户的视频流
          let userID = event.data.userID
          let streamType = event.data.streamType// 'main' or 'aux'            
          trtcRoomContext.subscribeRemoteVideo({ userID: userID, streamType: streamType })
        })

        // 监听远端用户的音频流的变更事件
        trtcRoomContext.on(EVENT.REMOTE_AUDIO_ADD, (event) => {
          // 订阅（即播放）远端用户的音频流
          let userID = event.data.userID
          trtcRoomContext.subscribeRemoteAudio(userID)
        })

        trtcRoomContext.on(EVENT.LOCAL_LEAVE, (event) => {
          console.log('* room LOCAL_LEAVE', event)
        })
        trtcRoomContext.on(EVENT.ERROR, (event) => {
          console.log('* room ERROR', event)
        })

        // 进入房间
        trtcRoomContext.enterRoom({ roomID: parseInt(_this.data.room_number) }).catch((res) => {
          console.error('room joinRoom 进房失败:', res)
        })

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by anderlu** [comment]
demo里面， enterRoom之前的监听事件都是有效的，可以看一下demo如何处理

**Comment by ezewu** [comment]
我也出现这问题，是偶现的，你解决了吗？
