### ISSUE TITLE
【web/小程序】-【6.5.7272】【同时mute视频和音频，会退出流】

### ISSUE THREAD

**Issue by RedMaxOo** [tencentyun/TRTCSDK#175]
【当前现象】
小程序和web端进入同一个会议，小程序mute掉语音和视频后，会从online端成员列表消失；
如果web端mute掉语音和视频，小程序端也会从成员列表中消失，但其实参会人还在会议里。

github提供的DEMO里可以复现。

【集成包】
TRTC精简版

【SDKAppID】
1400XXXXXX  

【房间号】
123456

【useID】
userNameA

【问题时间段】
2019-09-01 16:23~16:55

【机型】
如iPhone 7 Plus

【之前版本有无此问题】
如6.4之前没有，6.6有

【复现概率】
必现 / 偶现(如有大约概率请标明)

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 在 ... 回调中调用 ...
4. 在 ... 回调中调用 ...
5. 出现 Bug

【Demo 复现途径】
可复现  / 不可复现
1. 点击 ...
2. 进入 ..
3. 等待 ...
4. 出现 Bug

**Comment by zhengmenghuang** [comment]
这是个问题 会被用户挑战

**Comment by sc-vem** [comment]
这个问题是正常的。小程序关麦和关摄像头，web端是会触发退房的，只能通过IM来进行而外的状态维护；web端关闭摄像头和麦克风是直接退房的，没有在房间里且关闭麦克风摄像头的状态。
