### ISSUE TITLE
【Android】-【6.8.8003】【偶现】【问题简述，视频流获取超时，视频黑屏】

### ISSUE THREAD

**Issue by feigefeima** [tencentyun/TRTCSDK#176]
【当前现象】
如进房失败，提示错误码xxxx

【集成包】
TRTC精简版 / 

【SDKAppID】
1400329499

【房间号】
1005790

【useID】
D358

【问题时间段】
2010年3月20日 16:00~16:05

【机型】
机顶盒 4.4.4

【复现概率】
 偶现(1/20)

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 显示指定id界面，其他页面隐藏
4. 出现 Bug

**Comment by whalehe** [comment]
您好，偶现问题，是否有相应Log或者复现步骤。方便我们定位您的问题。
