### ISSUE TITLE
【Electron】-【7.0.146】【打包完trtc-electron-sdk.node 路径报错，显示的是开发环境的路径】

### ISSUE THREAD

**Issue by gxdvip** [tencentyun/TRTCSDK#177]
【当前现象】
trtc-electron-sdk 

【集成环境】
win10 32位;
node v12.16.1;
node-gyp v6.1.0;
vc++ 2015
electron 8.1.1 + vue-cli 4.2.3 + trtc-electron-sdk 7.0.146
打包工具 vue-cli-plugin-electron-builder 1.4.6

【之前版本有无此问题】
有

【复现概率】
必现

【复现途径】
1. 创建vue项目, 配置开发环境
// 创建vue项目
vue create trtc-test

// 安装 electron
yarn add electron -D

// 安装 trtc-electron-sdk
yarn add trtc-electron-sdk -S

2. 打包配置
// 安装打包工具
vue add electron-builder

// /vue.config.js 加入
module.exports = {
...

  chainWebpack: config => {
    config.module
      .rule('node')
      .test(/\.node$/)
      .use('node-loader')
      .loader('node-loader')
      .end()
  },
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        appId: 'com.tencent.live.test',
        productName: '直播测试',
        copyright: 'Copyright © 2020',
        win: {
          target: [
            {
              target: 'nsis',
              arch: [
                'ia32'
              ]
            }
          ]
        },
        nsis: {
          oneClick: false,
          allowElevation: true,
          allowToChangeInstallationDirectory: true,
          createDesktopShortcut: true,
          createStartMenuShortcut: true,
          shortcutName: '直播测试'
        }
      }
    }
  }

...
}

3. 测试代码
// /src/views/Home.vue
...

 mounted () {
    const param = new TRTCParams()
    param.sdkAppId = ’‘ // 需要从腾讯云实时音视频产品获取
    param.roomId = 110
    param.userId = '999'
    param.userSig = ’‘ // 需要后台生成
    param.role = TRTCRoleType.TRTCRoleAudience // 观众
    param.privateMapKey = ''
    param.businessInfo = ''
    this.rtcCloud.enterRoom(param, TRTCAppScene.TRTCAppSceneLIVE)
 },

...

4. 打包运行
5. 出现 Bug
![直接打包trtc-electron-sdk](https://user-images.githubusercontent.com/2382401/77155019-d0187c80-6ad7-11ea-8a68-d2e0e1efb3f6.png)

**Comment by daihy8759** [comment]
node-loader只能用做开发环境，我写篇文章给你 ：https://www.dhy8759.com/blog/J3tokzMPg/

**Comment by gxdvip** [comment]
> node-loader只能用做开发环境，我写篇文章给你 ：https://www.dhy8759.com/blog/J3tokzMPg/

朋友，文章链接打不开

**Comment by daihy8759** [comment]
> > node-loader只能用做开发环境，我写篇文章给你 ：https://www.dhy8759.com/blog/J3tokzMPg/
> 
> 朋友，文章链接打不开

你在国外吗？

**Comment by gxdvip** [comment]
> > > node-loader只能用做开发环境，我写篇文章给你 ：https://www.dhy8759.com/blog/J3tokzMPg/
> > 
> > 
> > 朋友，文章链接打不开
> 
> 你在国外吗？

链接依旧打不开，我在国内。在开发环境没问题，重点是打包后trtc_electron_sdk.node 的路径问题。
`
// trtc.js
const trtc = require('../build/Release/trtc_electron_sdk.node');
`
上面这段代码，用webpack 打包 就变成打包电脑的路径，在其他电脑安装就有问题。

因为webpack 会自动排除 node_modules目录，electron 的asar 包里压根没有.node文件，在其他电脑安装自然找不到这个文件。

这时候我马上想到让webpack 不排除 trtc-electron-sdk 包，但是就会报 not instanceof的错误（见附件）。
![外部打包trtc-electron-sdk](https://user-images.githubusercontent.com/2382401/77253818-ec631780-6c97-11ea-9590-04191ad7980f.png)

在腾讯云提工单，让我用官方demo的方式打包，demo 就是普通的html + js 没用webpack，而我用vue-cli 工程化的形式开发的，目前我是临时用动态require解决的，很想知道用vue 或 react 工程化的朋友是如何解决的。莫非大家都没用工程化开发也没遇到这个问题？

**Comment by daihy8759** [comment]
不知道你的网络啥问题，我都是就是react+webpack+ts的项目，按我发的链接描述就是正常打包的。

**Comment by daihy8759** [comment]
我给你复制过来，你按我的方法参照性修改
### 安装合适的native loader
```shell
yarn add native-ext-loader -D
```

### webpack环境配置
```js
{
    test: /\.node$/,
    loader: 'native-ext-loader',
    options: {
        emit: false,
        rewritePath: process.env.NODE_ENV !== 'production' ? undefined : './',
    }
}
```

### electron-builder 打包配置(package.json)
```json
"build": {
        "files": [
            "dist/**/*",
            "!node_modules"
        ],
        "extraFiles": [
            {
                "from": "node_modules/trtc-electron-sdk/build/Release",
                "to": "."
            }
        ]
}
```

**Comment by gxdvip** [comment]
> 我给你复制过来，你按我的方法参照性修改
> 
> ### 安装合适的native loader
> ```shell
> yarn add native-ext-loader -D
> ```
> 
> ### webpack环境配置
> ```js
> {
>     test: /\.node$/,
>     loader: 'native-ext-loader',
>     options: {
>         emit: false,
>         rewritePath: process.env.NODE_ENV !== 'production' ? undefined : './',
>     }
> }
> ```
> 
> ### electron-builder 打包配置(package.json)
> ```json
> "build": {
>         "files": [
>             "dist/**/*",
>             "!node_modules"
>         ],
>         "extraFiles": [
>             {
>                 "from": "node_modules/trtc-electron-sdk/build/Release",
>                 "to": "."
>             }
>         ]
> }
> ```

太感谢了，我试试

**Comment by gxdvip** [comment]
@daihy8759 这个方法好使，再次感谢

**Comment by bbc-594** [comment]
@gxdvip  你好，我也是使用的vue-cli-plugin-electron-builder，请问你的配置能让我看看吗，我配了半天总是失败

**Comment by MovingbricksInIT** [comment]
@gxdvip 你好我按照你的方式在window 是好用的 但是在mac 上就不行了  又什么方式吗

**Comment by gxdvip** [comment]
@MovingbricksInIT 可能还是路径问题，当时我的解决办法是
```
#win32
{
      from: 'node_modules/trtc-electron-sdk/build/Release',
      to: '.'
}

#mac
asarUnpack = [
    'trtc_electron_sdk.node'
]
```

由于6月份我公司直播项目终止，不知这个办法是否还有效，或者有更好的办法。

**Comment by MovingbricksInIT** [comment]
@gxdvip  首先非常感谢您的回复，昨天发现确实是路径的问题 根据您的代码做了修改
const nativePath = function() {
	let path = ''
	os.platform() === 'win32' ? path = './' : path = '../Resources'
	return path
}

{
  test: /\.node$/,
  use: {
	  loader: "native-ext-loader",
	  options: {
		  emit: false,
		  rewritePath: process.env.NODE_ENV !== 'production' ? undefined : nativePath(),
	  }
      }
  },
  
  "win": {
       "extraFiles": [
        {
          "from": "node_modules/agora-electron-sdk/build/Release/",
          "to": "./",
          "filter": [
            "**/*"
          ]
        }
      ]
  }
  
  "mac": {
      "extraFiles": [
        {
          "from": "node_modules/agora-electron-sdk/build/Release/",
          "to": "./Resources"
        }
      ]
    },
    
    
    再次表示感谢，祝您生活愉快
