### ISSUE TITLE
【Electron】-【6.9.138】文档错误  监听停止屏幕分享的事件名

### ISSUE THREAD

**Issue by rxliuli** [tencentyun/TRTCSDK#179]
【当前现象】
文档错误，源码中的监听停止屏幕分享的事件是 `onScreenCaptureStoped`，但文档中写的是 `onScreenCaptureStopped`，不看源码根本不知道。。。改一下咯

【集成包】
企业版Enterprise

【相关附件】
文档错误定位：https://trtc-1252463788.file.myqcloud.com/electron_sdk/docs/TRTCCallback.html#event:onScreenCaptureStopped

**Comment by suonian** [comment]
这里确实是`onScreenCaptureStopped`，demo源码已经更新过了。麻烦您看下最新的。

**Comment by rxliuli** [comment]
也就是说 sdk 的源码错了而非文档错误？

**Comment by suonian** [comment]
sdk源码是指哪个？
之前是sdk抛回调的时候写错了，新版本修复做了一个兼容：`onScreenCaptureStoped`、`onScreenCaptureStopped`都抛出来。

**Comment by rxliuli** [comment]
哦，做了兼容处理啊，行吧
