### ISSUE TITLE
接入React-Native项目报错

### ISSUE THREAD

**Issue by Wjy1005** [tencentyun/TRTCSDK#18]
duplicate symbol _TXC_getIntFromBuffer in:
    /Users/king/TRTC/ios/TRTC/TXLiteAVSDK_Professional.framework/TXLiteAVSDK_Professional(TXMP4Writer.o)
    /Users/king/TRTC/ios/TRTC/TXLiteAVSDK_Professional.framework/TXLiteAVSDK_Professional(RTMPUtil.o)
duplicate symbol _TXC_getSampleRateIndex in:
    /Users/king/TRTC/ios/TRTC/TXLiteAVSDK_Professional.framework/TXLiteAVSDK_Professional(TXMP4Writer.o)
    /Users/king/TRTC/ios/TRTC/TXLiteAVSDK_Professional.framework/TXLiteAVSDK_Professional(RTMPUtil.o)
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

RN:0.55.4
Xcode:9.4.1

**Comment by shengcui2018** [comment]
看下Xcode Build Settings中是否关闭了 Dead Code Stripping.

**Comment by Wjy1005** [comment]
> 看下Xcode Build Settings中是否关闭了 Dead Code Stripping.

我查看了下，debug模式是NO，改为YES之后报错：
Undefined symbols for architecture x86_64:
  "_res_9_getservers", referenced from:
      -[TXCStreamUploader getDNSServers] in TXLiteAVSDK_TRTC(TXCStreamUploader.o)
  "_res_9_ninit", referenced from:
      -[TXCStreamUploader getDNSServers] in TXLiteAVSDK_TRTC(TXCStreamUploader.o)
  "_res_9_ndestroy", referenced from:
      -[TXCStreamUploader getDNSServers] in TXLiteAVSDK_TRTC(TXCStreamUploader.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by shengcui2018** [comment]
请参考这篇文档添加依赖库 https://cloud.tencent.com/document/product/454/7876#2.E3.80.81.E6.B7.BB.E5.8A.A0framework

1. libz.tbd
2. libc++.tbd
3. libresolv.tbd
4. libsqlite3.tbd
5. Accelerate.framework
