### ISSUE TITLE
【小程序】-【6.5.7272】【音视频进行云端混流，收到成功提示后无法获取混流视频】

### ISSUE THREAD

**Issue by ecoyrage** [tencentyun/TRTCSDK#180]
【当前现象】
A与B的实时音视频进行云端混流之后，返回成功，无法找到混流后的视频，回调地址仍然收到两个独立的视频地址

【SDKAppID】
1400333185

【房间号】
278612291

【useID】
99fa94647cf5dd93ec468eb49490f0fb

【问题时间段】
2020-03-23 10:01~10:03

【复现概率】
必现 

【复现途径】
1. 调用 http://fcgi.video.qcloud.com/common_acces API
2. 两个streamId :1400333185_278612291_940b76db0a4ba7bbf1c102dd45835c55_main,
1400333185_278612291_99fa94647cf5dd93ec468eb49490f0fb_main
3.接口返回success ，回调收到两个未混流的视频文件

**Comment by tonyjiafan** [comment]
混流是在服务端处理的话，好像需要配置一个share的地址
${Config.SDK_APPID}_{rtcConfig.Room_Id}_share-{rtcConfig.Anchor_Id}_main";
并且配置画面布局，并返回！

**Comment by anderlu** [comment]
小程序目前不支持混流，应该是终端混流
