### ISSUE TITLE
【Web】-【4.3.10】client 的 client-banned 事件无法触发 

### ISSUE THREAD

**Issue by xiaosongxiaosong** [tencentyun/TRTCSDK#183]
【当前现象】
使用相同的用户名进入同一房间, SDK 日志显示有接受到 client-banned 事件，但是 client 的 client-banned 事件没有上报

【复现概率】

必现

【Demo 复现途径】

1. 打开两个标签，输入相同的用户名和房间号
2. 先进入房间的用户未提示 “您已被踢出房间”

【相关附件】
事件监听部分代码：
```js
    this.client_.on('error', err => {
      console.error(err);
      alert(err);
      location.reload();
    });
    this.client_.on('client-banned', err => {
      console.error('client has been banned for ' + err);
      if (!isHidden()) {
        alert('您已被踢出房间');
        location.reload();
      } else {
        document.addEventListener('visibilitychange', () => {
          if (!isHidden()) {
            alert('您已被踢出房间');
            location.reload();
          }
        }, false);
      }
    });
```
SDK 日志：
![image](https://user-images.githubusercontent.com/2703455/77719435-3180a400-7020-11ea-842f-39084c71e654.png)
页面错误提示：
![image](https://user-images.githubusercontent.com/2703455/77719457-40675680-7020-11ea-834f-cc02f2c1c319.png)

**Comment by MasterXS** [comment]
https://github.com/tencentyun/TRTCSDK/issues/163
