### ISSUE TITLE
【小程序】WXMini 设置层级错误

### ISSUE THREAD

**Issue by qq861229715** [tencentyun/TRTCSDK#184]
【当前现象】
小程序设置层级错误，应该是z-index

![image](https://user-images.githubusercontent.com/34129948/77765610-75ec5e00-7079-11ea-9de8-0b4799af3a6b.png)

【集成包】
TRTC精简版 / 专业版Professional / 企业版Enterprise

【SDKAppID】
1400XXXXXX

【房间号】
123456

【useID】
userNameA

【问题时间段】
2019-09-01 16:23~16:55

【机型】
如iPhone 7 Plus

【之前版本有无此问题】
如6.4之前没有，6.6有

【复现概率】
必现 / 偶现(如有大约概率请标明)

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 在 ... 回调中调用 ...
4. 在 ... 回调中调用 ...
5. 出现 Bug

【Demo 复现途径】
可复现  / 不可复现
1. 点击 ...
2. 进入 ..
3. 等待 ...
4. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by anderlu** [comment]
已修复
