### ISSUE TITLE
【Web】-【H5】【demo未能跑通】

### ISSUE THREAD

**Issue by jojoname** [tencentyun/TRTCSDK#185]
【当前现象】
按照说的改了dist\debug\GenerateTestUserSig.js的SDKAPPID和SECRETKEY启动登录
登录失败：Rest Api need sdkappid

【SDKAppID】
1400342015

【房间号】
123456

【useID】
userNameA

【复现概率】
必现 / 偶现(如有大约概率请标明)

【相关附件】
![image](https://user-images.githubusercontent.com/37427564/77816258-5b0efd80-70fc-11ea-80ac-9146601addf0.png)

**Comment by jojoname** [comment]
还有用了web端体验建群提示
createGroup error: {"message":"参数非法，请根据错误描述检查请求是否正确。","code":10004}

**Comment by anderlu** [comment]
请检查sdkappid 是否正确，已经相应的实时音视频服务是否为可用的状态。

**Comment by jojoname** [comment]
已经知道了错那了感谢
