### ISSUE TITLE
【Web】-【4.3.10】【同一个 useId 在不同浏览器进房，不会触发 client-banned 事件】

### ISSUE THREAD

**Issue by asingingfish** [tencentyun/TRTCSDK#186]
【当前现象】
同一个 useId 在不同浏览器进房，client 实例不会触发 client-banned，但日志显示 “Received event: [ client-banned ]”，然后触发了 Error 事件，返回的错误代码是 0x4041

【集成包】
TRTC精简版 Web 平台

【SDKAppID】
1400334849

【房间号】
2147478045

【useID】
0_EbymWfLCgrpN_7055435

【问题时间段】
2020-02-25 至今

【机型】
所有平台

【之前版本有无此问题】
4.3.8 同样有这个问题

【复现概率】
必现

【复现途径】
1. 在一个浏览器中进入房间
2. 在另一个浏览器中使用同样的 userId 进入同样的房间
3. 第一个浏览器中连接关闭，触发 Error 事件

【Demo 复现途径】
可复现

【相关附件】
![log](https://user-images.githubusercontent.com/14145640/77878849-dce16100-728b-11ea-952a-4ff2774d9371.jpg)

**Comment by MasterXS** [comment]
同名用户同时登录是业务逻辑错误，这种情况下可能会引发双方通话异常。client-banned或error事件上报都是符合预期行为。若需要房间内用户状态管理，请使用WebIM SDK

**Comment by asingingfish** [comment]
client-banned 和 error 明显是两个不同的事件类型，而且按**文档**描述，同名用户登录是会触发 client-banned 事件的。

**还是希望将已经收到的 client-banned 通知在 client 对象上 fire 出来**

**Comment by MasterXS** [comment]
> client-banned 和 error 明显是两个不同的事件类型，而且按**文档**描述，同名用户登录是会触发 client-banned 事件的。
> 
> **希望可以按照文档将已经收到的 client-banned 通知在 client 对象上 fire 出来**

https://trtc-1252463788.file.myqcloud.com/web/docs/module-Event.html#.CLIENT_BANNED

![image](https://user-images.githubusercontent.com/8175839/77997560-35832d80-7362-11ea-856e-4e5b2dbcc645.png)
日志里的"client-banned logout"不是互踢通知，是后台集群异常。我们文档里强调了 - 同名用户同时登录是业务逻辑错误，此时双方都有可能出现通话异常。所以，一定要避免这种行为。

**Comment by asingingfish** [comment]
这样的话，是不是把 `client-banned` 事件的触发原因去掉"同名登录" 比较好？

另外，关于 `client-banned` 事件，还有一个问题：

目前服务端的两个 API (`DismissRoom` 和 `RemoveUser`) 调用后都会触发 `client-banned`，客户端仅凭 `client-banned` 事件信息区分**解散房间**还是**踢人**就变得十分困难，某些业务场景下是需要进行这些区分的

**Comment by MasterXS** [comment]
> 这样的话，是不是把 `client-banned` 事件的触发原因去掉"同名登录" 比较好？

同名用户同时登录是业务逻辑错误，业务层应该尽量避免。如果业务做好了规避，实际运行中client-banned就只跟服务器端RESTAPI解散房间和踢人相关。

> 
> 另外，关于 `client-banned` 事件，还有一个问题：
> 
> 目前服务端的两个 API (`DismissRoom` 和 `RemoveUser`) 调用后都会触发 `client-banned`，客户端仅凭 `client-banned` 事件信息区分**解散房间**还是**踢人**就变得十分困难，某些业务场景下是需要进行这些区分的

目前后台暂无区分 client-banned 是因为 DismissRoom 还是 RemoveUser，后续我们会考虑让后台优化下这段逻辑。

**Comment by asingingfish** [comment]
> 目前后台暂无区分 client-banned 是因为 DismissRoom 还是 RemoveUser，后续我们会考虑让后台优化下这段逻辑。

好的，请尽快优化。可否在近期版本优化？
