### ISSUE TITLE
怎么获取房间开始至结束时间以及房间内用户用时

### ISSUE THREAD

**Issue by borgzhong** [tencentyun/TRTCSDK#189]
查边官网文档，没有找到API可以获取房间开始至结束时间以及房间内用户用时

**Comment by whalehe** [comment]
您好，调用enterRoom接口后，您会收到来自 TRTCCloudListener 中的 onEnterRoom(result) 回调：

- 如果加入成功，result 会是一个正数（result > 0），表示加入房间所消耗的时间，单位是毫秒（ms）。

- 如果加入失败，result 会是一个负数（result < 0），表示进房失败的错误码。

具体可以参考API：http://doc.qcloudtrtc.com/group__TRTCCloudListener__android.html#abf0525c3433cbd923fd1f13b42c416a2
