### ISSUE TITLE
要实现一个视频客服系统，能否给个思路？

### ISSUE THREAD

**Issue by liunewshine** [tencentyun/TRTCSDK#19]
现在的实时音视频功能太过简单，都是需要双方手动加入房间。
【用户A(android)】呼叫 【客服B(windows）】，怎样才能让客服B收到提醒并且接听呢？并且某一方挂断，另外一方自动挂断呢？

**Comment by shengcui2018** [comment]
呼叫部分可以使用IMSDK等完成，客服收到呼叫消息后发送房间号给A，双房进入同一房间即可。房间号可由业务服务器下发或者每个座席固定一个房间号。通话结束后也可以同样处理。
