### ISSUE TITLE
【Electron】-【7.0】新版本有什么不兼容更新么？

### ISSUE THREAD

**Issue by rxliuli** [tencentyun/TRTCSDK#190]
【当前现象】
目前 release 只写了修复了什么 bug，那么大版本更新导致的 break change 在哪里看呢？这里吾辈主要想知道的是 **6.9 => 7.0** 的破坏性更新

【集成包】
TRTC 企业版Enterprise

![image](https://user-images.githubusercontent.com/24560368/78319231-508bb280-7599-11ea-986d-b17e7f8a60c6.png)

**Comment by gansidui** [comment]
新新版主要是内部的一些bugfix及优化，不存在兼容性问题，直接升级即可。
