### ISSUE TITLE
【iOS】-【6.5.7272】【项目要向下适配到8.0，TRTC最低支持9.0，我该怎么处理】

### ISSUE THREAD

**Issue by yinsexuejing** [tencentyun/TRTCSDK#191]
【当前现象】
ios 8.0~>ios9.0系统的机型应用启动闪退。项目要向下适配到8.0，TRTC最低支持9.0，我该怎么处理。

【集成包】
TRTC精简版

【SDKAppID】
1400236396

【复现概率】
必现

**Comment by whalehe** [comment]
https://cloud.tencent.com/document/product/647/32173，SDK目前要求iOS 9.0 以上的 iPhone 或者 iPad 真机。暂时不支持8.0，建议升级系统
