### ISSUE TITLE
【web】-【80.0.3987.162】【web跟安卓手机小程序连接偶现黑屏】

### ISSUE THREAD

**Issue by lhguo** [tencentyun/TRTCSDK#192]
【当前现象】
web跟安卓手机小程序连接偶现黑屏
业务场景：web只推音频流，小程序推音视频流。

【集成包】
TRTC精简版

【SDKAppID】
1400329619

【房间号】
6559

【useID】
152046690330625

【问题时间段】
2020-04-03 10:30~11:30

【机型】
HUAWEI P30   
型号 ELE-AL00  
安卓版本 10

【之前版本有无此问题】
未知

【复现概率】
40%

【复现途径】
双放来回进入视频房间，小程序偶尔会报开启摄像头失败

【Demo 复现途径】
未发现

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by zhengmenghuang** [comment]
小程序端黑屏概率特别高 怎么搞 这个东西根本没法用啊

**Comment by whalehe** [comment]
您好，可以更新到我们最新版本，看下是否还有这个问题，另外提供一份日志，是我们快速定位您的问题的关键。

**Comment by zhengmenghuang** [comment]
> 您好，可以更新到我们最新版本，看下是否还有这个问题，另外提供一份日志，是我们快速定位您的问题的关键。

已经替换成最新的最新的7.3的sdk，目前感觉良好，黑屏现象复现率很小。

同时调用trtc-room的方式也改进了，进入房间后延迟开启摄像头和麦克风。这个改进也极大的提高了视频的稳定性。
![image](https://user-images.githubusercontent.com/29627098/85991861-a3ed8f80-ba26-11ea-9b2d-4f0a1aae08ea.png)
