### ISSUE TITLE
【Android】-【6.7.7754】【问题简述，多人视频,进房失败，视频界面卡死】

### ISSUE THREAD

**Issue by alextyloo** [tencentyun/TRTCSDK#195]
【当前现象】
  用户A B C 正常进入房间
  用户A  大退杀进程方式 退出，再次点击上一次房间号进入房间
 B 和 C 用户 未监听到用户A 进入
 且视频界面有卡死现象
【集成包】
TRTC/ 企业版Enterprise

【SDKAppID】
1400242259

【房间号】
17370

【useID】
DR000522

【问题时间段】
2020-04-11 19:00~21:36

【机型】
 

【之前版本有无此问题】

【复现概率】
必现 

【复现途径】

【Demo 复现途径】

【相关附件】

**Comment by whalehe** [comment]
您好，可以升级到最新7.1版本SDK，看有无此问题，如果还有问题，帮附上日志，以便我们快速定位问题。
