### ISSUE TITLE
【Windows】-【7.2】【ManageLiteAV.xml文件从4912行起乱码】

### ISSUE THREAD

**Issue by dujianxin** [tencentyun/TRTCSDK#199]
【当前现象】
ManageLiteAV.xml文件从4912行起乱码

【相关附件】
![image](https://user-images.githubusercontent.com/15842774/79733436-b4e39b80-8327-11ea-982b-f7c845a71be7.png)

**Comment by whalehe** [comment]
您好，可以更新到我们的最新版。

**Comment by dujianxin** [comment]
未修复，7.4.0.9204版本6728行仍为乱码
