### ISSUE TITLE
是否会提供服务器端api管理房间？

### ISSUE THREAD

**Issue by liunewshine** [tencentyun/TRTCSDK#20]
为了防止某些用户不手动退出房间，导致时长占用过多。
服务器端需要监听房间列表，自动剔除长时间占用流量的用户，强制解散房间等功能，是否有计划提供以上api呢？

**Comment by shengcui2018** [comment]
目前需要在客户端实现相关逻辑，服务器接口方案需要一段时间，多谢反馈。
