### ISSUE TITLE
【Web】-【4.3.13 】【Web的是否支持美颜效果】

### ISSUE THREAD

**Issue by linxiangqian** [tencentyun/TRTCSDK#202]
【当前现象】：web版本的是否支持美颜和滤镜效果呐？？

**Comment by MasterXS** [comment]
暂不提供该功能。

**Comment by linxiangqian** [comment]
> 暂不提供该功能。
未来有计划支持嘛？？ 我看有一个平台 《声网》 就支持 WEB 端的美颜。

https://docs.agora.io/cn/Audio%20Broadcast/API%20Reference/web/interfaces/agorartc.stream.html#setbeautyeffectoptions

**Comment by anderlu** [comment]
已支持 https://web.sdk.qcloud.com/trtc/webrtc/doc/zh-cn/tutorial-28-advanced-beauty.html
