### ISSUE TITLE
【Android】-【7.2.8927】【logcat一直打印AudioTrack: isLongTimeZoreData zoer date time XX Seconds】

### ISSUE THREAD

**Issue by JingweiWang** [tencentyun/TRTCSDK#203]
【当前现象】
logcat一直打印AudioTrack: isLongTimeZoreData zoer date time XX Seconds

【集成包】
TRTC精简版

![image](https://user-images.githubusercontent.com/10261452/80590030-cf1b2900-8a4d-11ea-9f79-6500c2a982a6.png)

貌似没有录音权限就会打这行log，这里官方是否可以优化一下。
并且如果没有录音权限，静听通话后，通话状态错乱且无法关闭免提。

**Comment by whalehe** [comment]
您好，AudioTrack: isLongTimeZoreData zoer date time XX Seconds,这个是手机系统层的日志，不是TRTC相关日志

**Comment by JingweiWang** [comment]
@whalehe 你们太不负责了，去看看你们自己的so库代码。。。

[TXCTraeAudioEngine.cpp, OnQueryPcmToPlay, 1176]:AudioCenter: 【TXSDK-TRAE-LOG】 OnQueryPcmToPlay, isMute:1, Should print every 20 seconds

![image](https://user-images.githubusercontent.com/10261452/81252024-6b998880-9057-11ea-93ad-843f7c59ea7f.png)

**Comment by whalehe** [comment]
您好，TXCTraeAudioEngine.cpp相关TAG，这个是我们的日志，后续会精简这些日志，AudioTrack相关TAG: isLongTimeZoreData zoer date time XX Seconds确实是系统层的日志，已经确认过了

**Comment by JingweiWang** [comment]
如果没有录音权限，接听通话后，通话状态错乱且无法关闭免提。
那这个问题呢? @whalehe

**Comment by WayneSimon** [comment]
> 您好，TXCTraeAudioEngine.cpp相关TAG，这个是我们的日志，后续会精简这些日志，AudioTrack相关TAG: isLongTimeZoreData zoer date time XX Seconds确实是系统层的日志，已经确认过了

我也遇到了这些打印信息，在finish掉activity后仍然在打印这些，如何才能关闭对应的任务呢

**Comment by WayneSimon** [comment]
我也遇到了这些打印信息，在finish掉activity后仍然在打印这些，如何才能关闭对应的任务呢

**Comment by myj420** [comment]
这是小米手机系统改的audiotrack加的日志 只有小米手机出现了 ri

**Comment by soolaugust** [comment]
mark for this problem
