### ISSUE TITLE
ios Demo都运行不起来。。。。。

### ISSUE THREAD

**Issue by IIIOS** [tencentyun/TRTCSDK#204]
failed to emit precompiled header '/Users/denny/Library/Developer/Xcode/DerivedData/TRTCScenesDemo-evzoxlrfesihaffohqusidimtesu/Build/Intermediates.noindex/PrecompiledHeaders/trtcScenes-Bridging-Header-swift_3CZ2W5FFARS18-clang_16A5PSEIJTJG3.pch' for bridging header '/Users/denny/Desktop/TXLiteAVSDK_TRTC_iOS_7.2.8932/TRTCScenesDemo/TRTCScenesDemo/trtcScenes-Bridging-Header.h'

**Comment by whalehe** [comment]
您好，可以参考页面的运行步骤：https://github.com/tencentyun/TRTCSDK/tree/master/iOS/TRTCScenesDemo
