### ISSUE TITLE
【iOS】-【7.2.8927】【多次点击进房退房后，会出现进房后自动退房问题】

### ISSUE THREAD

**Issue by Aromxyz** [tencentyun/TRTCSDK#205]
【当前现象】
双人视频通话，多次点击拨号进房，挂断退房，大概5-6次后会出现自动退房问题

【集成包】
TRTC精简版

【SDKAppID】
1400318786

【房间号】
842

【useID】
20488948

【问题时间段】
不限

【机型】
iPhone 8 Plus

【之前版本有无此问题】
都有

【复现概率】
偶现(如有大约概率请标明)

【复现途径】
1. 主动调用 enterRoom API
2. 主动调用 exitRoom API
3. 重复上诉操作，会出现最后进房后我们没有主动调用exitRoom，SDK自动调用exitRoom.

【Demo 复现途径】
可复现  / 不可复现
1. 点击 ...
2. 进入 ..
3. 等待 ...
4. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等
[自动退房.txt](https://github.com/tencentyun/TRTCSDK/files/4562234/default.txt)

**Comment by whalehe** [comment]
您好，可以更新到我们最新版本7.4，看下是否还有这个问题。
