### ISSUE TITLE
【Web】-【4.3.14】【运行RTC Web demo脚本错误getUserMedia error】

### ISSUE THREAD

**Issue by z-lionel** [tencentyun/TRTCSDK#207]
【当前现象】
从腾讯云开发辅助，快速跑通demo，下载web版本，填入SDKAPPID，SECRETKEY，打开index.html页面的时候报错如下，无法正常显示视频
  <ERROR> [s|user_58569198]  getUserMedia error observed [object OverconstrainedError]
failed to initialize local stream - [object OverconstrainedError]

【集成包】
TRTC精简版

【SDKAppID】
1400364259

【房间号】
demo默认

【useID】
demo默认

【问题时间段】
随时

【机型】
Chrome浏览器

【之前版本有无此问题】
未知

【复现概率】
必现 

【复现途径】
1. 下载demo，点击进入房间，就会出该报错，页面没有显示视频 

【Demo 复现途径】
可复现  
1. 点击 进入房间
2. 出现 Bug

**Comment by z-lionel** [comment]
在demo页面里面的发现：
TRTC.getCameras,  TRTC.getMicrophones
拿到的的摄像头和麦克风列表列表，返回的deviceId都是空

**Comment by z-lionel** [comment]
发现在mac的谷歌的浏览器下面，没有提示是否允许使用摄像头。
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

**Comment by ywh1103** [comment]
这个问题解决了吗？我现在也遇到这个问题了。safair上是正常可以开启摄像头的，Chrome就不会提示开启摄像头，而且控制台还报错

**Comment by EasinYao** [comment]
chrome浏览器因异常而获取不到cameraId和microphoneId导致的报错，sdk已解决并更新。

**Comment by EasinYao** [comment]
> 发现在mac的谷歌的浏览器下面，没有提示是否允许使用摄像头。
> UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

chrome浏览器因异常而获取不到cameraId和microphoneId导致的报错，sdk已解决并更新。

**Comment by EasinYao** [comment]
> 这个问题解决了吗？我现在也遇到这个问题了。safair上是正常可以开启摄像头的，Chrome就不会提示开启摄像头，而且控制台还报错

问题已解决。

**Comment by ywh1103** [comment]
是怎么解决的呢

**Comment by z-lionel** [comment]
> 这个问题解决了吗？我现在也遇到这个问题了。safair上是正常可以开启摄像头的，Chrome就不会提示开启摄像头，而且控制台还报错

刚想回复，就回复解决了，我是通过自己封装的 navigator.mediaDevices.enumerateDevices获取设备列表

**Comment by z-lionel** [comment]
> 是怎么解决的呢

应该是你更新sdk就可以了

**Comment by ywh1103** [comment]
ok
