### ISSUE TITLE
【Android/iOS】-【6.5.7272】【直播模式，是否支持文字交流】

### ISSUE THREAD

**Issue by alextyloo** [tencentyun/TRTCSDK#209]
【当前现象】

直播模式，是否支持文字交流

**Comment by gansidui** [comment]
直播文字是啥意思？可以使用IMSDK来做聊天

**Comment by whalehe** [comment]
您好，TRTC互动直播，支持一边直播，一边文字交流，可以目前TRTCScenesDemo中LiveRoom是支持的，具体参考代码：https://github.com/tencentyun/TRTCSDK/tree/master/Android/TRTCScenesDemo/trtcliveroomdemo
