### ISSUE TITLE
麦克风权限关闭，没有错误回调

### ISSUE THREAD

**Issue by shingohu** [tencentyun/TRTCSDK#21]
Android版本6.3.7089, 关闭麦克风权限，startLocalAudio,没有onError回调,但是摄像头权限关闭时,有onError回调,另外摄像头权限关闭返回的错误码是1301,感觉跟文档上说的也不一样

**Comment by kuen229** [comment]
> Android版本6.3.7089, 关闭麦克风权限，startLocalAudio,没有onError回调,但是摄像头权限关闭时,有onError回调,另外摄像头权限关闭返回的错误码是1301,感觉跟文档上说的也不一样

@shingohu 目前移动端摄像头错误没那么细，目前是打开失败后统一返回1301错误码，不区分原因。麦克风打开失败回调有点问题，还在修复中，预计6.4版本fix

**Comment by kuen229** [comment]
> @kuen229 老大,出来回答下问题啊,着急上线
> 第二个问题 muteLocalAudio(true) muteLocalVideo(true) 同时屏蔽掉后,其它用户收到这个用户离开房间的回调,开启其中一个后,有重新进入了房间

目前用户的房间状态是和用户的音视频数据上行有关，音频和视频都不上行后，会认为不在房间了，这里需要业务做下处理

**Comment by kuen229** [comment]
6.4.7108版本已修复权限回调问题
