### ISSUE TITLE
【Web】-【 4.3.14】【本地已发布的localstream调用muteVideo / unmuteVideo / muteAudio / ummuteAudio， 监听事件没有触发回调 】

### ISSUE THREAD

**Issue by z-lionel** [tencentyun/TRTCSDK#211]
【当前现象】
如题，当开关音视频的时候，unmute-video 和 unmute-audio事件都没有触发

【集成包】
TRTC精简版

【SDKAppID】
1400XXXXXX

【房间号】
demo默认

【useID】
demo默认

【问题时间段】
随时

【机型】
chrome浏览器

【之前版本有无此问题】
未知

【复现概率】
必现 

【复现途径】
1. muteVideo  unmutVideo 
2.视频会开关
3.事件mute-video  unmute-video没有触发

【Demo 复现途径】
可复现

**Comment by z-lionel** [comment]
请教下，开关本地的localstream是mute-audio, mute-video没有回调的吗？

**Comment by whalehe** [comment]
您好，可以更新到我们最新版本，看下是否还有这个问题。

**Comment by JHWanliPeng** [comment]
> 您好，可以更新到我们最新版本，看下是否还有这个问题。

web sdk 远端流 unmute-video 事件正常 mute-video 没有触发。 mute-audio unmute-audio 都正常
