### ISSUE TITLE
【Android】-【7.2.8927】【开启应用后第一次通话设置听筒播放有几率失败】

### ISSUE THREAD

**Issue by JingweiWang** [tencentyun/TRTCSDK#212]
【当前现象】
开启应用后第一次通话设置听筒播放有几率失败。
mTRTCCloud.setAudioRoute(TRTCCloudDef.TRTC_AUDIO_ROUTE_EARPIECE);
设置后仍从扬声器播放对端声音。

【集成包】
TRTC精简版

【复现概率】
偶现(4/10)

**Comment by whalehe** [comment]
您好，是在部分机型上么？还是所有机器上，如果是部分机型上，方便告知下我们机型详细信息么？

**Comment by JingweiWang** [comment]
> 您好，是在部分机型上么？还是所有机器上，如果是部分机型上，方便告知下我们机型详细信息么？

小米10 小米6 都有复现

**Comment by whalehe** [comment]
您好，目前TRTC 7.3版本已发布，可以更新下试试，还有无此问题

**Comment by JingweiWang** [comment]
> 您好，目前TRTC 7.3版本已发布，可以更新下试试，还有无此问题

仍有此问题 @whalehe

**Comment by yifguan** [comment]
Hi，7.5 SDK已经发布并修复了该问题，可以更新试试

**Comment by JingweiWang** [comment]
> Hi，7.5 SDK已经发布并修复了该问题，可以更新试试

好的，7.5.9307暂时没有再复现了。谢谢
