### ISSUE TITLE
【Web】-【4.3.8】【本地流setAudioVolume  设置播放音量大小无效】

### ISSUE THREAD

**Issue by GeXuanHong** [tencentyun/TRTCSDK#213]
【当前现象】
推送本地屏幕分享流（包含麦克风音轨）, setAudioVolume(0.0) 静音后，观看仍能听到麦克风声音

【包版本】
4.3.8

【机型】
chrome

【之前版本有无此问题】
一直都有

【复现概率】
必现

【复现途径】
1.  推送本地屏幕分享流
2. 调用 setAudioVolume API  设置为静音
3. 设置无效，仍有音量

【相关附件】
![image](https://user-images.githubusercontent.com/30696708/81539681-2ea8fb00-93a3-11ea-831b-f96bdcdfe46c.png)

**Comment by whalehe** [comment]
您好，可以更新到我们最新版本，看下是否还有这个问题。

**Comment by anderlu** [comment]
setAudioVolume 只对播放音量进行调整，不想让远端听到可以用 muteAudio
