### ISSUE TITLE
【Android】-【7.2.8927】【挂断通话后无法释放音频通路】

### ISSUE THREAD

**Issue by JingweiWang** [tencentyun/TRTCSDK#214]
【当前现象】
挂断通话后无法释放音频通路，导致其他app无法正常播放音乐，必须杀掉本app

【集成包】
TRTC精简版

【复现概率】
必现

**Comment by whalehe** [comment]
您好，挂断通话，有销毁TRTCCloud实例么？

**Comment by JingweiWang** [comment]
没有，请问是每次通话后必须销毁TRTCCloud么？文档中并没有提及此操作

**Comment by whalehe** [comment]
退房后，需要销毁TRTCCloud实例，API文档中的基础方法：https://cloud.tencent.com/document/product/647/32267#.E5.9F.BA.E7.A1.80.E6.96.B9.E6.B3.95
