### ISSUE TITLE
【小程序】-【6.5.7272】【1对1聊天，退房后还有声音，】

### ISSUE THREAD

**Issue by rxy8023** [tencentyun/TRTCSDK#215]
【当前现象】
1对1聊天，退房后还有声音，

【集成包】
TRTC精简版 / 专业版Professional / 企业版Enterprise

【SDKAppID】
1400348636

【房间号】
123456

【useID】
userNameA

【问题时间段】
2019-09-01 16:23~16:55

【机型】
红米👀0pro

【之前版本有无此问题】
如6.4之前没有，6.6有

【复现概率】
偶现

【复现途径】
退出房间后，还可以听到对方说话

【Demo 复现途径】
可复现  / 不可复现
1. 点击 ...
2. 进入 ..
3. 等待 ...
4. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by rxy8023** [comment]
一方先进房，触发退房后另外一方进房，此时进房用户收到「远端用户进房」，退房的用户还有声音

**Comment by sc-vem** [comment]
这边的测试是没有出现这个问题的，如果可以的话麻烦复现一下，不排除是系统版本和微信版本不兼容的问题，可以通过系统升级解决

**Comment by rxy8023** [comment]
> 这边的测试是没有出现这个问题的，如果可以的话麻烦复现一下，不排除是系统版本和微信版本不兼容的问题，可以通过系统升级解决

是bus没有回收导致的，已经提了一个骗人

**Comment by iweisi** [comment]
> > 这边的测试是没有出现这个问题的，如果可以的话麻烦复现一下，不排除是系统版本和微信版本不兼容的问题，可以通过系统升级解决
> 
> 是bus没有回收导致的，已经提了一个pr

请问这个问题要怎么解决，api有事件可以处理吗？
