### ISSUE TITLE
【iOS】-【7.2.8932】【1v1视频中，对方杀掉进程后，iOS端收不到任何回调】

### ISSUE THREAD

**Issue by kerwin1232** [tencentyun/TRTCSDK#218]
【当前现象】
1v1视频中，对方杀掉进程后，此时iOS端收不到任何回调,  1分钟左右后收到远端离开房间回调
【集成包】
TRTC精简版

【SDKAppID】
1400354488

【机型】
iOS所有机型

【复现概率】
必现 

【复现途径】
1. 可通话的两台设备（其中1台iOS）
2. 进行视频通话
3. 视频中杀掉另一台设备的APP进程
4. 出现 Bug

【Demo 复现途径】
可复现 
1. 可通话的两台设备（其中1台iOS）
2. 进行视频通话
3. 视频中杀掉另一台设备的APP进程
4. 出现 Bug

**Comment by AbySwifter** [comment]
目前对于杀掉进程的情况暂时没有处理，您的情况我这边会反馈到相关人员。谢谢
