### ISSUE TITLE
【微信小程序】支持浮框或者后台不退房，继续语音聊天么

### ISSUE THREAD

**Issue by Allen-su** [tencentyun/TRTCSDK#219]
【微信小程序】支持小程序浮框或者后台运行时不退房，继续语音聊天么，要怎么操作？
  因为在语音聊天时，可能要出来回复下微信，或者看些微信内的其它内容，可以么

**Comment by Allen-su** [comment]
测试发现 android 端是支持的，主要是 ios 端不支持

**Comment by anderlu** [comment]
这个需要微信侧支持，组件支持不了。
