### ISSUE TITLE
【iOS】-【 7.2.8932】【问题简述，结束通话后，状态栏异常】

### ISSUE THREAD

**Issue by kerwin1232** [tencentyun/TRTCSDK#221]
【当前现象】
iOS 13.4 ，非刘海屏手机 ， 在结束通话后，状态栏闪动，服务商和电池不显示，只显示当前时间

【集成包】
TRTC精简版 
【SDKAppID】
1400354488

【机型】
非刘海屏 ，如iPhone 7 

【复现概率】
必现

【复现途径】
1. 开始视频通话
2. 接通后，点击结束通话
3.通话页面消失，状态栏发生改变
4. 出现 Bug

【Demo 复现途径】
1. 开始视频通话
2. 接通后，点击结束通话
3.通话页面消失，状态栏发生改变
4. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by whalehe** [comment]
您好，是否方便截图一个或者视频，描述状态栏异常的现象
