### ISSUE TITLE
小程序与web 1v1 视频通话，小程序端视频中，页面跳转，苹果机没问题，用安卓机，电脑端视频窗口会出现黑屏现象

### ISSUE THREAD

**Issue by webchina1** [tencentyun/TRTCSDK#222]
【当前现象】
如进房失败，提示错误码xxxx

【集成包】
TRTC精简版 / 专业版Professional / 企业版Enterprise

【SDKAppID】
1400XXXXXX

【房间号】
123456

【useID】
userNameA

【问题时间段】
2019-09-01 16:23~16:55

【机型】
如iPhone 7 Plus

【之前版本有无此问题】
如6.4之前没有，6.6有

【复现概率】
必现 / 偶现(如有大约概率请标明)

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 在 ... 回调中调用 ...
4. 在 ... 回调中调用 ...
5. 出现 Bug

【Demo 复现途径】
可复现  / 不可复现
1. 点击 ...
2. 进入 ..
3. 等待 ...
4. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by sc-vem** [comment]
这是正常的。不同系统的问题，安卓如果进入其他页面摄像头就会关闭所以黑屏，但是ios端会一直开着摄像头，所以只要不退房，进入其他页面ios端也会一直开启摄像头
