### ISSUE TITLE
【Web】-【在正常的直播间刷新页面后没有声音】

### ISSUE THREAD

**Issue by iyaq** [tencentyun/TRTCSDK#223]
【当前现象】
学生端接直播，从“进入直播”的按钮进入直播教室一切正常，如果在直播室页面刷新一下，页面摄像头、白板聊天都正常，只是没有声音    
刷新后报错：
` trtc.js:1 Uncaught (in promise) RtcError: NotAllowedError: play() failed because the user didn't interact with the document first.  `

【集成包】
TRTC精简版

【SDKAppID】
1400256114

【房间号】
19785318
【useID】
冷月凤清

【问题时间段】
刷新页面就是

【机型】
pc   chrome

【之前版本有无此问题】

【复现概率】
必现

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 在 ... 回调中调用 ...
4. 在 ... 回调中调用 ...
5. 出现 Bug

【Demo 复现途径】
可复现 
1. 点击 ...   进入直播
2. 进入 ..直播教室正常（有音视频、白板、聊天）
3. 刷新直播页 ...一切正常除了没有音频
4. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by zy1260863199-web** [comment]
麻烦提供以下复现时间段，听不到声音可以做一下webrtc的能力测试：https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html

**Comment by anderlu** [comment]
自动播放受限，建议按照这个文档处理。https://web.sdk.qcloud.com/trtc/webrtc/doc/zh-cn/tutorial-21-advanced-auto-play-policy.html
