### ISSUE TITLE
【Electron】-【6.5.7272】【问题简述，如进房失败，提示错误码 3301】

### ISSUE THREAD

**Issue by zyu** [tencentyun/TRTCSDK#224]
【当前现象】

mac 电脑
进房失败，提示错误码3301

 get  tinyid error

**Comment by SaxonGao-SZ** [comment]
请问是否设置了混流？

**Comment by whalehe** [comment]
您好，麻烦按照issue模板提下issue，另外提供一份日志，是我们快速定位您的问题的关键。
