### ISSUE TITLE
【web】-【6.5.7272】【发送自定义消息显示成功，实际上是失败的】

### ISSUE THREAD

**Issue by lrltop** [tencentyun/TRTCSDK#225]
【当前现象】
发送自定义消息，我把数据转换成json放到description字段里面，发送，回调显示是发送成功了，可是下次拉去消息的时候description字段为空，data和extension都是正常。不管是把转换后的字符串放到data或者description都是这个现象，难道是因为字段长度过长导致的这样吗？im文档也没说明这些规范，现在完全不知道是什么原因，回调都是返回的发送成功，实际上我刷新页面拉去消息的时候字段为空

【SDKAppID】
1400291595

【房间号】
123456

【useID】
plz560

【复现概率】
经常出现，偶尔会正常发送

【复现途径】
未知情况

【Demo 复现途径】
可复现

**Comment by whalehe** [comment]
您好，IM相关，可以在：https://github.com/tencentyun/TIMSDK 中的issue提问，然后附上一份日志，方便快速定位您的问题
