### ISSUE TITLE
【Android】-【7.2】【如果关闭硬件加速会导致无法渲染对方视频流】

### ISSUE THREAD

**Issue by WhiteorBlack** [tencentyun/TRTCSDK#226]
【当前现象】
如果设置 android:hardwareAccelerated="false",关闭硬件加速之后，会导致对方的视频流无法渲染，对方 TXCloudVideoView 为透明。

【集成包】
 专业版Professional 

【SDKAppID】
1400149528

我知道这个问题不应该视为BUG，但我还是希望能够在文档或 log 中给出提醒，或者解决这个问题。以免像我不够细心的开发者遇到这个问题而无从排查。

**Comment by vyunyilin** [comment]
非常感谢您的反馈，文档已更新
https://cloud.tencent.com/document/product/647/32175#.E9.85.8D.E7.BD.AE-app-.E6.9D.83.E9.99.90
