### ISSUE TITLE
【Web】4.3.14 版本存在回音

### ISSUE THREAD

**Issue by borgzhong** [tencentyun/TRTCSDK#228]
之前使用 4.3.5 版本，PC 浏览器及 ipad safair 浏览器都正常，但最近升级到 4.3.14 版本后，存在回音，即：每说一句话后。能清晰的听到自己的说话回音。请检查测试。

**Comment by borgzhong** [comment]
补充：测试到是由于语音视频对方使用了外放声音，然后系统将外放声音又经过麦克风传回来，故形成了回音，这种情况有没有什么办法可以减轻回音呢？

**Comment by chenkongming** [comment]
请问有没有解决呢

**Comment by borgzhong** [comment]
> 请问有没有解决呢

终于在 4.50 版本修正了回音问题，强烈建议更新
