### ISSUE TITLE
【electron】-【4.2.12】【enterRoom, params is not instanceof TRTCParams】

### ISSUE THREAD

**Issue by HelloDreamICome** [tencentyun/TRTCSDK#239]
【当前现象】
调用enterRoom方法报错   params is not instanceof TRTCParams

【集成包】
TRTC精简版 electron平台

【SDKAppID】
 1400328573

【房间号】
 222

【useID】
39edf022-7c6a-5ee7-9891-ef758feec5c1

【问题时间段】
2020-6-8~

【之前版本有无此问题】
 一直有

【复现概率】
 必现 

【复现途径】
 调用进入房间方法enterRoom

【Demo 复现途径】
可复现  
1. 点击 ...
2. 进入 ..
3. 等待 ...
4. 出现 Bug

【相关附件】
![image](https://user-images.githubusercontent.com/25941459/84014513-07971680-a9ad-11ea-9b42-804d17e2fc8e.png)

![image](https://user-images.githubusercontent.com/25941459/84014469-f1895600-a9ac-11ea-9933-844da35c3de3.png)

**Comment by HelloDreamICome** [comment]
![image](https://user-images.githubusercontent.com/25941459/84014685-4f1da280-a9ad-11ea-80a1-686de3e7d809.png)
这里判断一致过不了  但是已经是TRTCParams实例了

**Comment by king-ying** [comment]
您好，请问怎么解决的？我也遇到这个问题

**Comment by HelloDreamICome** [comment]
> 您好，请问怎么解决的？我也遇到这个问题
这个是哪个里面验证TRTCParams过不了导致的   后来给了个让过去的方案  
rtcCloud = new TRTCCloud(); 
param = new TRTCParams();
然后rtcCloud.rtcCloud.enterRoom(param.sdkAppId,param.roomId, param.userId,param.userSig, param.privateMapKey,param.businessInfo,param.role,param.userDefineRecordId,param.streamId,TRTCAppScene.TRTCAppSceneVideoCall);
里面参数都是TRTCParams的那些参数弄进去
