### ISSUE TITLE
这个项目跟移动直播SDK中的实时连麦-视频通话的定位区别

### ISSUE THREAD

**Issue by dragonimp** [tencentyun/TRTCSDK#24]
移动直播SDK中的实时连麦-视频通话：
https://cloud.tencent.com/document/product/454/13641

这里也有视频通话功能，两个定位差别在哪里？能力和技术实现是否有差异？

可否直接复用那个SDK的成果？那个SDK里面已经封装了dotnet clr的版本。

**Comment by 6e6e6e** [comment]
从两个方面来比较的话，简单说一下：
1. 技术实现层面
- RTC-Room 是基于 LiteAVSDK 的 RTMP over UDP 推拉流的方式封装的一层 API，在实现上属于七层的方式。底层是通过替换 TCP 为 UDP 来实现，将 RTMP 的的优点如流程简单、可靠性等都保留了，当然也保留了 RTMP 更适合于单向推流的特点。在用于通话时，实际就是双方各自推流+播放对方的流，遇到网络抖动时，因为 RTMP 原本可靠性的机制，会等待重发，因而在网络适应性上没有那么强大，经过多次优化后，在30%丢包下还能保证通话
- TRTC 是 LiteAV 框架中利用的私有的 UDP 协议进行的通话，在实现上属于四层的方式。TRTC 里使用了两块的通道，一部分是信令通道，用于对通话过程中的操作信令进行传递，一部分是数据通道，用于音视频数据传输，因为使用的是私有的 UDP，并且有信令通道上报实时的数据动态，在流控策略以及网络调优上，发挥的空间更大，目前可以做到 50% 丢包正常通话，70% 丢包下仍可保持语音

2. 业务层面上
- RTC-Room 直接利用了目前已有的 RTMP 推流方式，在实现上更简单，成本相对较低，但在通话业务层面，因为实现机制的原因，仅适合双人通话，针对多人通话的场景并不适合
- TRTC 在通话效果上更优，而且更适合多人通话的场景，几十个人同时通话也可以做到延时可控，效果可控，但相对来讲成本就会较高一点

**Comment by dragonimp** [comment]
就是trtc更好更贵…

那sdk接口不能统一起来么

**Comment by dragonimp** [comment]
看接口感觉是rtcroom封装了room的管理了
