### ISSUE TITLE
【Android】-【7.3.9138】【主播身份进入后台直播掉线】

### ISSUE THREAD

**Issue by ouyangyi01919** [tencentyun/TRTCSDK#240]
【当前现象】
以主播身份进入直播开启摄像头推流(也试过录屏推流),回到后台后不到一分钟就掉线了,观众端显示主播暂时不在线

【集成包】
TRTC精简版 

【SDKAppID】
1400384043

【房间号】
未知

【useID】
123

【问题时间段】
2020-06-10 22:17~22:18

【机型】
小米6

【复现概率】
必现 

【Demo 复现途径】
可复现  / 不可复现
1. 视频互动直播
2. 新建直播间,开始直播,观众端进入直播
3. 按home键回到后台
4. 出现 Bug,观众端看不到视频
[log.txt](https://github.com/tencentyun/TRTCSDK/files/4759250/log.txt)

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by whalehe** [comment]
您好，可以更新到最新的7.4版本，试试还有无此问题
