### ISSUE TITLE
TRTCSDK ; enterRoom, params is not instanceof TRTCParams

### ISSUE THREAD

**Issue by king-ying** [tencentyun/TRTCSDK#242]
_Originally posted by @king-ying in https://github.com/tencentyun/TRTCSDK/issues/239#issuecomment-641803144_

**Comment by SaxonGao-SZ** [comment]
请问是哪个平台？ 是 native 还是 electron ?

**Comment by whalehe** [comment]
您好，提issue麻烦按照issue模板提issue，方便我们快速定位您的问题
