### ISSUE TITLE
【iOS】-【latest】【TRTC小程序：同样条件下iOS端进房后没有远端，但安卓端却是正常的】

### ISSUE THREAD

**Issue by gy18505** [tencentyun/TRTCSDK#243]
【当前现象】
iOS 微信7.0.9以上版本，进房很正常无报错，但是只能看到自己，没有远端影像，提示正在等待。
看日志输出，没有任何关于“remote”的字样，估计是拉流出现问题。
P.S. 安卓端非常正常，完全没有上述问题。

【问题时间段】
2020-6-15

【机型】
iPhone 6

【之前版本有无此问题】
暂不清楚，目前只试过在7.0.9以上的微信版本，均有此问题

【复现概率】
必现

**Comment by gy18505** [comment]
好像是用户ID含有中文字符导致的

**Comment by whalehe** [comment]
您好，id最后用数字和字母组成。如还有问题，再探讨交流

**Comment by wkl007** [comment]
userID不能有中文！！！！这个问题坑了我5个小时！！！
