### ISSUE TITLE
【Electron】-【7.2.174】【在electron-vue中引入包失败】

### ISSUE THREAD

**Issue by acexyf** [tencentyun/TRTCSDK#249]
【当前现象】
在electron-vue中引入包失败

【环境】
Win10
Electron 2.0.4

【复现】
通过脚手架搭建环境
npm install -g vue-cli
vue init simulatedgreg/electron-vue my-project
然后安装
npm i trtc-electron-sdk --save-dev
在vue代码中引入
const TRTCCloud = require('trtc-electron-sdk');
就会出现报错

【相关附件】
Uncaught Error: Cannot open D:\projects\electron-vue-music\node_modules\trtc-electron-sdk\build\Release\trtc_electron_sdk.node: Error: A dynamic link library (DLL) initialization routine failed.
D:\projects\electron-vue-music\node_modules\trtc-electron-sdk\build\Release\trtc_electron_sdk.node

【联系我】
我是腾讯视频的开发者，请腾讯的工作人员看到问题尽快联系我2817259608@qq.com

**Comment by SaxonGao-SZ** [comment]
您好， 我来跟进。

**Comment by SaxonGao-SZ** [comment]
我不推荐直接使用 electron-vue 来创建项目，因为这个脚手架提供的 electron 版本太老了(2.x)， 而  sdk 至少需要Electron 4.0 版本才能运行（目前已经到了 9.x 版本）。

您可以参考我们 TRTCSimpleDemo 的项目构建方式：https://github.com/tencentyun/TRTCSDK/tree/master/Electron/TRTCSimpleDemo
另外在使用 Electron 开发过程中，您也可能遇到一些安装或打包的问题时可以查阅我们整理的《Electron 常见问题收录》https://cloud.tencent.com/developer/article/1616668

**Comment by acexyf** [comment]
Good

**Comment by acexyf** [comment]
Good
