### ISSUE TITLE
【Electron】-【】【点击进入开始上课，应用白屏】

### ISSUE THREAD

**Issue by Roadbook** [tencentyun/TRTCSDK#252]
【当前现象】
应用白屏，控制台提示devtools was disconnected from the page

【集成包】
TRTC精简版

**Comment by SaxonGao-SZ** [comment]
您好，请提供一下更详细的信息。

**Comment by zhaowenhao** [comment]
我在Mac系统使用VS Code的命令行跑项目时，遇到此类情况。
原因是MacOS10.15+系统在运行时需要明确授予摄像头和麦克风权限，而VS Code并不会去申请这些权限，所以一进入房间就直接崩溃报错。
解决办法：打开系统的命令终端，在命令终端中运行npm start启动项目，当进入房间时，会有弹框提示你授予摄像头和麦克风权限，你同意就可以了。

**Comment by gansidui** [comment]
> 我在Mac系统使用VS Code的命令行跑项目时，遇到此类情况。
> 原因是MacOS10.15+系统在运行时需要明确授予摄像头和麦克风权限，而VS Code并不会去申请这些权限，所以一进入房间就直接崩溃报错。
> 解决办法：打开系统的命令终端，在命令终端中运行npm start启动项目，当进入房间时，会有弹框提示你授予摄像头和麦克风权限，你同意就可以了。

目前在vscode上启动会出现权限问题导致崩溃，目前没找到解决方案。可是楼主问的不是这个问题吧？
