### ISSUE TITLE
【小程序】-【Version 7.3 @ 2020.06.01】【android 进入后台 出现浮窗 能否静音？】

### ISSUE THREAD

**Issue by zhengmenghuang** [tencentyun/TRTCSDK#253]
【小程序】-【Version 7.3 @ 2020.06.01】需要android 不管是浮窗还是进入后台都静音不推流

【当前现象】：android浮窗后，推流端依旧能推出声音但是不能推视频，接收端能听到声音
【SDKAppID】：1400217202
【房间号】: C202006240024
【useID】：ocP-15FTN-UPsHM5bmCGNpsXZi4s
【问题时间段】：all
【机型】：所有android
【之前版本有无此问题】：有
【是否必现】：必现
【复现方法】：无
【日志或者描述、截图】：无

------------------------------------------------------------------------------------------------------------------------------------------

希望ios端与android端功能对齐，进入后台默认静音，不推流。

**Comment by whalehe** [comment]
您好，进入后台，你可以stoplocalAudio，来停止推送音频流，进入前台，开启startLocalAudio
