### ISSUE TITLE
跪求Flutter版本的SDK

### ISSUE THREAD

**Issue by LvJson** [tencentyun/TRTCSDK#256]
现在Flutter使用的企业越来越多了，什么时候能支持下

**Comment by bishen** [comment]
我自己集成了一个。现在是debug可以正常视频（本机摄像头、远端摄像头、分享辅流），
不过一发布release的，一视频就会蹦

**Comment by bishen** [comment]
我这里集成了android版的。本机摄像头、远端摄像头、分享屏幕辅流，包括监听事件等。
可有尝提供服务

**Comment by whalehe** [comment]
duplicate：https://github.com/tencentyun/TRTCSDK/issues/200

**Comment by c1avie** [comment]
可参考接入flutter trtc文档：https://pub.dev/packages/tencent_trtc_cloud
