### ISSUE TITLE
【web】-【4.4.0】【32位谷歌浏览器83版本，获取摄像头及麦克风报错】

### ISSUE THREAD

**Issue by xiayefeng** [tencentyun/TRTCSDK#259]
【当前现象】
接通视屏后sdk报错，没有弹出授权弹框。视频无法正常进行。

【集成包】
专业版Professional 

【问题时间段】
2019-09-01 16:23~16:55

【机型】
window 7 32位

【之前版本有无此问题】
不知道

【复现概率】
必现

【复现途径】
安卓端发起视频咨询，web端接通后没有反应。

**Comment by CascadingSS** [comment]
麻烦在浏览器上手动授权摄像头和麦克风看下是否可以正常运行呢？

**Comment by xiayefeng** [comment]
> 麻烦在浏览器上手动授权摄像头和麦克风看下是否可以正常运行呢？

手动可以运行，每个机器都要手动，岂不是要累死了
