### ISSUE TITLE
About TRTCCloud.sharedInstance

### ISSUE THREAD

**Issue by eritpchy** [tencentyun/TRTCSDK#26]
为了用上最新版6.4.7108 看看代码都变成什么样了
之前版本: 6.1.6454

![image](https://user-images.githubusercontent.com/8630635/57469174-9de39f00-72b8-11e9-8bbe-18b3756602c2.png)

PS: README 说的最新版 6.4.7110 在哪? jcenter 只有 6.4.7108, 4月25发布, 现在5月9了

**Comment by tao-pu** [comment]
您好，6.2版本SDK调整了TRTCCloud实例对象为单例，做了接口调整。抱歉给您的使用带来不便。

Android的6.4正式版本号为6.4.7108
