### ISSUE TITLE
【小程序】- 【7.4】 ios无法进入房间，建立推拉流

### ISSUE THREAD

**Issue by fyang0728** [tencentyun/TRTCSDK#262]
【当前现象】
收不到远端进入房间的提示，错误码一直1102 -> 3002 -> -1307 

【集成包】
TRTC精简版 

【机型】
IOS系统手机 
微信版本7.0.14 
小程序基础库2.12.0

【复现概率】
必现

【相关附件】

**Comment by hyoutom** [comment]
这个直接强行关闭吗

**Comment by aboutmydreams** [comment]
今天的用户全都没进去房间...,官方能解释下吗
