### ISSUE TITLE
小程序 webrtc-room组件triggerEvent没完善

### ISSUE THREAD

**Issue by JunTaoChen** [tencentyun/TRTCSDK#27]
webrtc-room组件对有人加入房间，有人退出房间，通话开始，通话结束，重新连接没有可绑定事件的地方，postEvent只响应错误事件。

**Comment by gansidui** [comment]
可以根据 1020 事件错误码（定时下发）来判断成员进出情况，对应的msg是一个json文本，可以解析出当前房间成员列表。
通话开始和结束需要应用层自己做，为了减少复杂性，重连逻辑在内部做了。
