### ISSUE TITLE
【Electron】-【7.6.300】升级 7.0 失败。。。

### ISSUE THREAD

**Issue by rxliuli** [tencentyun/TRTCSDK#277]
【当前现象】

7.0 之后不支持 electron 32 位了么？

提示

```
Uncaught Error: Cannot open C:\Users\rxliuli\Text\Company\shishiPc\node_modules\trtc-electron-sdk\build\Release\trtc_electron_sdk.node: Error: C:\Users\rxliuli\Text\Company\shishiPc\node_modules\trtc-electron-sdk\build\Release\trtc_electron_sdk.node is not a valid Win32 application.
C:\Users\rxliuli\Text\Company\shishiPc\node_modules\trtc-electron-sdk\build\Release\trtc_electron_sdk.node
```

【集成包】
TRTC精简版 / 专业版Professional / 企业版Enterprise

【之前版本有无此问题】
如6.9之前没有

【复现概率】
必现

【相关附件】

![image](https://user-images.githubusercontent.com/24560368/91822961-1b2fe180-ec6b-11ea-87b3-8efd61c0ce60.png)

**Comment by suonian** [comment]
32位一直都是支持的。
请问是本地运行么，清一下node_module，然后重新npm install试试呢。如果还不行可以把install的打印贴出来看看

**Comment by rxliuli** [comment]
官方 demo 可复现，在工单里面沟通过了

**Comment by rxliuli** [comment]
![image](https://user-images.githubusercontent.com/24560368/91925591-e9208d00-ed07-11ea-9e3c-d3ef8ff93d3d.png)
