### ISSUE TITLE
小程序

### ISSUE THREAD

**Issue by ydCrazy** [tencentyun/TRTCSDK#278]
多人会议成员列表显示的用户id怎么换成自己输入的用户名

- [

**Comment by zy1260863199-web** [comment]
<view class="input-box">
    <input type="number" value="{{roomID}}" maxlength="10" bindinput='enterRoomID' placeholder="请输入房间号" placeholder-style="color:#ffffff;opacity: 0.55;"/>
  </view>可以参考demo里面的roomid/userid写法输入，参考链接：https://github.com/tencentyun/TRTCSDK/tree/master/WXMini
