### ISSUE TITLE
6.5什么时候更新啊 现在windows sdk直播 音频很不好的 像是没有处理 噪音很大 等更新啊

### ISSUE THREAD

**Issue by wsh9527** [tencentyun/TRTCSDK#28]

**Comment by tao-pu** [comment]
您好，噪声是什么样的，能否录制一段
是啸叫 还是 背景噪声很大
是否断断续续
是情况一windows端采集的声音，其他端播放有噪声，还是情况二其他端采集的声音在windows播放有噪声
是否是多个播放端同时都有噪声
正常说话时音量和噪音情况如何

**Comment by wsh9527** [comment]
没问题了，默认配置问题
