### ISSUE TITLE
建议分离各个端的源代码

### ISSUE THREAD

**Issue by monsterooo** [tencentyun/TRTCSDK#30]
在国内访问github本来就很慢，现在的方式将所有源代码放在一起。导致想要跑一个demo很久很久都下载不下来代码。 是不是可以将demo进行分离到不同的仓库？或者提供更快的下载地址呢？

**Comment by rexchang2016** [comment]
您好，感谢您的建议，我们已经在 github 的首页 readme 里防止了分流镜像下载地址，以后每个版本都会放置一份在上面

**Comment by wangzhenmax** [comment]
现在下载还是需要下载一整个包 很慢很慢 并没有将每个版本单独放置

**Comment by rexchang2016** [comment]
您好，我们最近清理了仓库里的二进制文件，git下载大小缩减到 36.2M，同时上线了 gitee.com 的镜象地址：https://gitee.com/cloudtencent/TRTCSDK/

**Comment by 815807765** [comment]
> 您好，我们最近清理了仓库里的二进制文件，git下载大小缩减到 36.2M，同时上线了 gitee.com 的镜象地址：https://gitee.com/cloudtencent/TRTCSDK/

镜像访问不了，你自己试过镜像地址能不能打开吗？

**Comment by shengcui2018** [comment]
@815807765 麻烦再试下，镜像地址是有内容的
