### ISSUE TITLE
小程序和H5增加混流功能

### ISSUE THREAD

**Issue by dragonimp** [tencentyun/TRTCSDK#32]
“微信小程序和 H5 上暂时还不支持移动和 PC 端的混流接口（setMixTranscodingConfig），不过您可以使用云直播的 REST API 实现该功能。"

有两个问题：

1、“微信小程序和 H5上的setMixTranscodingConfig 这个接口什么时间增加？
2、如果要自己弄这个api：https://cloud.tencent.com/document/product/267/8832
    这里面的输入流相关参数怎么获取到呢？

感觉我们这个TRTC很多东西还不完善，想要做成产品，还需要做很多工作的啊。

**Comment by rexchang2016** [comment]
您好，请问您是只用 h5 和 小程序吗？一个房间里只要有一个人掉用混流就可以了。

我们有后台的混流 api （https://cloud.tencent.com/document/product/267/8832）

**Comment by dragonimp** [comment]
是的，目前只有这两个。windows版本没clr版本，目前用的是浏览器插件打开web版本实现的pc端。
用这个api，sign一直检验不通过。

**Comment by dragonimp** [comment]
已实现接口调用验证

**Comment by daliang0222** [comment]
兄弟 你是实现了小程序多个连麦混流吗，我也遇到这个场景，不知道采用哪种解决方案

**Comment by daliang0222** [comment]
> 已实现接口调用验证
兄弟 你是实现了小程序多个连麦混流吗，我也遇到这个场景，不知道采用哪种解决方案，你是调用腾讯云接口解决吗

**Comment by daliang0222** [comment]
> 已实现接口调用验证

兄弟 你是实现了小程序多个连麦混流吗，我也遇到这个场景，不知道采用哪种解决方案，你是调用腾讯云接口解决吗
