### ISSUE TITLE
[ios] 打包失败

### ISSUE THREAD

**Issue by dd1891** [tencentyun/TRTCSDK#334]
【iOS】真机iOS编译失败
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RPScreenRecorder", referenced from:
      objc-class-ref in TXLiteAVSDK_TRTC(TXCCaptureAndEnc.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
【机型】xcode 11.2 || xcode 12.x macos 最新系统
【是否必现】：必现

**Comment by Lius1104** [comment]
【环境】
Xcode 12.2
macOS 10.15.7
【机型】
iphone5 10.3.4
【错误】
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_TCBeautyPanelTheme", referenced from:
      objc-class-ref in TCAnchorToolbarView.o
  "_OBJC_CLASS_$_TCBeautyPanel", referenced from:
      objc-class-ref in TCAnchorToolbarView.o
ld: symbol(s) not found for architecture armv7

**Comment by Jimmy-J** [comment]
【iOS】-【TXLiteAVSDK_TRTC (8.0.9642)】iOS 编译失败

【当前现象】：如：iOS 真机编译失败。
【集成包】：精简版本
【机型】：真机 iphone 7 ，iOS 13.3.1 ，xcode版本 12.2，Mac OS 11.01
【之前版本有无此问题】：7.x 的版没有这个问题
【是否必现】：必现
【日志或者截图】：
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RPScreenRecorder", referenced from:
      objc-class-ref in TXLiteAVSDK_TRTC(TXCCaptureAndEnc.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kihuizhang0001** [comment]
试下加Replaykit库能否解决，选择option
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/66675490/99362058-f0f6d300-28ed-11eb-9cdb-9b4e7e09e6a9.png">

**Comment by dd1891** [comment]
不能解决，要在这个sdk的pod里面做修改，添加这个replaykit。

**Comment by kihuizhang0001** [comment]
添加replaykit还是报一样的错误吗？我们这边验证添加之后是可以的呢

**Comment by Jimmy-J** [comment]
> 试下加Replaykit库能否解决，选择选项
> <img alt="图片" width="1339" src="https://user-images.githubusercontent.com/66675490/99362058-f0f6d300-28ed-11eb-9cdb-9b4e7e09e6a9.png">

添加 Replaykit 选择 optional 后编译正常了

**Comment by dd1891** [comment]
额， 你们理解错了，是修改完pod后就没问题了。不用他线上的podspec文件

**Comment by dd1891** [comment]
spec.ios.framework = ['AVFoundation', 'Accelerate', 'ReplayKit']
