### ISSUE TITLE
【Web】-【4.7.1】【相同网络下，trtc web 的上传质量比android 要差】

### ISSUE THREAD

**Issue by SamLuo835** [tencentyun/TRTCSDK#345]
【当前现象】
相同的网络（网络的上传速度不是很高）， web 的连麦非常卡 视频丢包几乎100%， android 的丢包率低很多， 从控制台看  web的码率不知道为什么比安卓会高很多   即使我在web代码里自定义了码率

【集成包】
TRTC精简版

【SDKAppID】
1400342624

【房间号】
60021

【useID】
5fcafc680127cd000838daf9，5fcaf5a1186d2a000838c9db

【问题时间段】
2020-12-15 10:14:05～2020-12-15 11:08:36

【复现概率】
必现 

【相关附件】
<img width="728" alt="Screen Shot 2020-12-15 at 11 55 49" src="https://user-images.githubusercontent.com/34040508/102246289-950f7200-3ecc-11eb-9b68-73246bcc341c.png">

**Comment by Tencent-Alice** [comment]
您好，很多头部用户反馈WEB端不是很友好，但不至于视频丢包几乎100%
SDK使用的是最新版吗

**Comment by SamLuo835** [comment]
> 您好，很多头部用户反馈WEB端不是很友好，但不至于视频丢包几乎100%
> SDK使用的是最新版吗

嗯 用的是4.7.1  上传速度是很慢是真的  只有0.5～ 0.6 mpbs   100%丢包可能我夸张了说吧   我把控制台截图了 ， 左上是web 的 右下是安卓端的， 都是一个网络。 web的是一发布本地流就不行了， android 起码还能用

<img width="1204" alt="Screen Shot 2020-12-16 at 02 13 03" src="https://user-images.githubusercontent.com/34040508/102316694-62a15b80-3f44-11eb-8eb3-8f3d06bc538b.png">

**Comment by Tencent-Alice** [comment]
OK， 具体需要收集日志具体排查了
技术问题，Q2562367495  备注来意
