### ISSUE TITLE
【Android】-【6.5.7272】【直播Activity闪退，Log显示回退到软解、Buffer分配失败等】

### ISSUE THREAD

**Issue by cyanlink** [tencentyun/TRTCSDK#350]
【当前现象】
长时间播放直播后，直播Activity闪退

【集成包】
TRTC精简版

【SDKAppID】
1400393094

【房间号】
TBD

【userID】
watch_xX0hHe

【问题时间段】
2020-12-23 14.00~16.00

【机型】

康佳Android TV平台
product:KKHi3751V551E_64bit_DMO_2layer model:Konka_Android_TV_551 device:KKHi3751V551E
SoC：海思  hi3751

【之前版本有无此问题】
不确定

【复现概率】
偶然出现

【复现途径】
简单的 mTRTCCloud.startRemoteView(userId, viewname); 场景

【Demo 复现途径】
在TV端一定时间（1小时-2小时），播放Activity会闪退，Log提示Buffer分配失败，硬件解码初始化失败回退到软解等信息。

【相关附件】

链接: https://pan.baidu.com/s/1C4O57HirwDq_098930QbuA 提取码: mxxz 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v4的分享

**Comment by Tencent-Alice** [comment]
您好，根据您的描述，需要收集下日志具体排查。技术问题，欢迎私信，Q2562367495 注明来意

**Comment by Tencent-Alice** [comment]
编解码能力问题，后续sdk我们做了大量优化和更新，也可以先更新SDK版本尝试下
