### ISSUE TITLE
Android版视频通话，免提功能无效

### ISSUE THREAD

**Issue by zlqscount** [tencentyun/TRTCSDK#36]
导入LiteAVSDK_TRTC_6.5.7272.aar，TRTCMainActivity下的：
private void enableAudioHandFree(boolean bEnable) {
        if (bEnable) {
            trtcCloud.setAudioRoute(TRTCCloudDef.TRTC_AUDIO_ROUTE_SPEAKER);
        } else {
            trtcCloud.setAudioRoute(TRTCCloudDef.TRTC_AUDIO_ROUTE_EARPIECE);
        }
    }
无法开启免提音。

“声音免提模式”取消勾选后：
06-19 18:57:57.558 15396-17533/com.zcql.zcql E/Unknow: [TXCTraeAudioEngine.cpp, SetAudioMode, 327]:AudioCenter:【TXSDK-TRAE-LOG】traeSetAudioOutputMode:1, return 0  

“声音免提模式”勾选后：
06-19 18:59:16.428 15396-17533/com.zcql.zcql E/Unknow: [TXCTraeAudioEngine.cpp, SetAudioMode, 327]:AudioCenter:【TXSDK-TRAE-LOG】traeSetAudioOutputMode:0, return 0

**Comment by pk2373** [comment]
兄弟 这个问题最后怎么解决了
