### ISSUE TITLE
【iOS】-【8.4】【微信内嵌网页 无法播放】

### ISSUE THREAD

**Issue by conghuiw** [tencentyun/TRTCSDK#370]
https://cloud.tencent.com/document/product/647/16863，文档中显示 iOS 12.1.4+ | 微信内嵌网页 | - | 支持播放

实际无法进入房间播放视频。

请确认trtc是否支持在微信内嵌网页播放？

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，我这边用ios 14.微信版本8.02是可以正常通话的，请先忽略设备检测的提示。
用户进入房间，能看到自己的画面即代表已成功进入房间。
要跟其他的用户通话，请确保双方加入的是同一个房间号。
![image](https://user-images.githubusercontent.com/74762384/108489616-b92c6c80-72dc-11eb-9835-5917d994d133.png)
如还有问题 欢迎交流 Q2562367495 注明来意

**Comment by conghuiw** [comment]
你好，可以把你的测试代码发一份给我吗？我这边用H5_latest压缩包里面的代码，把设备检测都去掉了还是不行。
我修改的代码为index.html,以下两行注释掉了。

    <script src="./js/rtc-detection.js"></script>
    <script src="./js/device-testing.js"></script>

**Comment by conghuiw** [comment]
问题解决了，是我这边没有注意到IOS微信端浏览器自动播放受限的问题。

stream.play('remote').catch(error => {});
stream.on('error', error => {
  const errorCode = error.getCode();
  if (errorCode === 0x4043) {
    **// PLAY_NOT_ALLOWED,引导用户手势操作并调用 stream.resume 恢复音视频播放**
    // stream.resume()
  }
})





> 您好，根据您的问题，我这边用ios 14.微信版本8.02是可以正常通话的，请先忽略设备检测的提示。
> 用户进入房间，能看到自己的画面即代表已成功进入房间。
> 要跟其他的用户通话，请确保双方加入的是同一个房间号。
> ![image](https://user-images.githubusercontent.com/74762384/108489616-b92c6c80-72dc-11eb-9835-5917d994d133.png)
> 如还有问题 欢迎交流 Q2562367495 注明来意
