### ISSUE TITLE
【Mac】-【8.3.9878】分享屏幕时，Qt获取WinId添加到排除列表中无法产生作用

### ISSUE THREAD

**Issue by coderlxn** [tencentyun/TRTCSDK#389]
【当前现象】：屏幕分享设置排除自定义的窗口，使用Qt获取WinId添加到排除列表中无法产生作用
【集成包】：TRTC精简版
【SDKAppID】：
【房间号】:
【useID】：
【问题时间段】：
【机型】：OSX 10.15.7
【之前版本有无此问题】：
【是否必现】：必现，
【复现方法】：

测试发现从sourcelist中获取到的TRTCScreenCaptureSourceInfo的sourceId和Qt中取到的WindId不相同。
```
trtc::TRTCScreenCaptureSourceInfo info = sourceList->getSourceInfo(i);
```
同一个窗口，从trtc中拿到的sourceId是`0x10198`，而从Qt中获取到的WinId是`0x7f99374dcfc0`
请问如何添加一个自定义的窗口

同样的逻辑在Windows上是正常的。

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，可以视频复现下，收集下日志具体看下
日志路径：
https://cloud.tencent.com/developer/article/1502366
技术问题 欢迎交流 q2562367495 注明来意

**Comment by coderlxn** [comment]
@autoreleasepool {

    // Get all the windows

    CFArrayRef windowListAll = CGWindowListCopyWindowInfo(kCGWindowListOptionOnScreenOnly, kCGNullWindowID);

    NSArray* arr = CFBridgingRelease(windowListAll);

    NSUInteger count = [arr count]; //CFArrayGetCount(arr);

    // Loop through the windows

    for (NSMutableDictionary* entry in arr){

        if (entry == nil){

            break;

        }

        NSLog(@"enter:%@",entry);

        NSString *wndName=[entry objectForKey:(id)kCGWindowName];

        NSInteger wndNumber=[[entry objectForKey:(id)kCGWindowNumber] intValue];

        NSLog(@"wndName:%@ number:%ld",wndName,wndNumber);

        if (![wndName isEqualToString: @"~/test.txt"]){

            //不是自己想要的窗口继续下一个循环

            continue;

        }

        //下面这个方法是手册中最先查到的，但仅对属于自己app的窗口有效，其它app的窗口无效，所以不能采用

        //NSWindow * wind=[NSApp windowWithWindowNumber: wndNumber];

        //NSLog(@"wnd:%@",wind);

        CGRect bounds;

        CGRectMakeWithDictionaryRepresentation((CFDictionaryRef)[entry objectForKey:@"kCGWindowBounds"], &bounds);

        NSLog(@"bounds: %@",NSStringFromRect(bounds));   

        //根据pid获取窗口所属的app

        pid_t pid = [[entry objectForKey:(id)kCGWindowOwnerPID] intValue];

        AXUIElementRef appRef = AXUIElementCreateApplication(pid);

        NSLog(@"Ref = %@",appRef);

        //获取app所有的窗口

        CFArrayRef windowList;

        AXUIElementCopyAttributeValue(appRef, kAXWindowsAttribute, (CFTypeRef *)&windowList);

        //NSLog(@"WindowList = %@", windowList);

        CFRelease(appRef);

        if (!windowList){

            //NSLog(@"windowList is nil");

            continue;

        }

        for (int i=0;i<CFArrayGetCount(windowList);i++){

            //遍历app所有窗口，查找跟全局遍历所获得窗口的实体

            AXUIElementRef windowRef = (AXUIElementRef) CFArrayGetValueAtIndex( windowList, i);

            NSLog(@"windowRef:%@",windowRef);

            CGWindowID application_window_id = 0;

            _AXUIElementGetWindow(windowRef, &application_window_id);

            if (application_window_id == wndNumber){

                //找到

                NSLog(@"Found a wnd that number is:%u",application_window_id);

                //根据需要来操作窗口的位置，仅用作示例，这里可以修改成其它操作

                CFTypeRef position;

                CGPoint newPoint;

                newPoint.x = 0;

                newPoint.y = 0;

                NSLog(@"Create new position");

                position = (CFTypeRef)(AXValueCreate(kAXValueCGPointType, (const void *)&newPoint));

                //setting new position

                AXUIElementSetAttributeValue(windowRef, kAXPositionAttribute, position);

            }

            CFRelease(windowRef);

        }

     NSLog(@"end a loop");

    } //for windowListAll

    } //autorelease
