### ISSUE TITLE
什么时候分离各个端的源码？ git下载太慢了导致下载失败 现在没办法下载到demo使用 求授方法

### ISSUE THREAD

**Issue by wangzhenmax** [tencentyun/TRTCSDK#39]
什么时候分离各个端的源码？ git下载太慢了导致下载失败 现在没办法下载到demo使用 求授方法

**Comment by jackbbhua** [comment]
文档里面有个下载地址呀 你找找

**Comment by lzcdev** [comment]
[如何从 GitHub 上下载单个文件夹？](https://www.zhihu.com/question/25369412)

**Comment by rexchang2016** [comment]
您好，腾讯云分流下载地址：https://github-1252463788.cos.ap-shanghai.myqcloud.com/trtcsdk/TRTCSDK-6.5.7272.zip

我们会进房在国内的 github 源码平台上放置镜像下载地址。

**Comment by rexchang2016** [comment]
您好，我们最近清理了仓库里的二进制文件，git下载大小缩减到 36.2M，同时上线了 gitee.com 的镜象地址：https://gitee.com/cloudtencent/TRTCSDK/

**Comment by rexchang2016** [comment]
已经所见文件大小到 38M
