### ISSUE TITLE
【web electron】-【8.2.8-beta.4】【web端使用electron的sdk找不到process.dlopen】

### ISSUE THREAD

**Issue by Goddywu** [tencentyun/TRTCSDK#398]
【当前现象】
![image](https://user-images.githubusercontent.com/29056050/115328642-7ba46c80-a1c3-11eb-9ae5-b3d808af153c.png)

【集成包】
TRTC精简版

【SDKAppID】
"trtc-electron-sdk": "^8.2.8-beta.4"

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，web端 使用electron sdk？ dlopen是客户端才有的方法 ，详情可以描述下
技术问题 欢迎交流 q2562367495 注明来意

**Comment by Goddywu** [comment]
@Tencent-Alice  

您好，electron是混合开发，理论应该web和app都支持的呢

**Comment by HungryFour** [comment]
@Goddywu 同样遇到这个问题  求问解决了吗

**Comment by Goddywu** [comment]
太久了，忘记有没有解决了🐷
