### ISSUE TITLE
【Android】-【8.5】Android编译失败

### ISSUE THREAD

**Issue by kangear** [tencentyun/TRTCSDK#399]
【Android】-【8.5】Android编译失败

【当前现象】：Demo编译失败
【集成包】：TRTC
【SDKAppID】：N/A
【机型】：Android Studio版本 4.1.2，Ubuntu 18.04
【之前版本有无此问题】：
【是否必现】：必现
【日志或者截图】：暂无日志（有日志附上日志），有截图附上问题截图
failed
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
:app:processDebugResources
../../../../../.gradle/caches/transforms-2/files-2.1/f000a2518fa4342df3e7805db7dd75b9/material-1.3.0/res/values/values.xml
Android resource linking failed
Android resource linking failed
Android resource linking failed
../../../../../.gradle/caches/transforms-2/files-2.1/8e37ae2aa36e65f98a34c0063d6da9be/appcompat-1.2.0/res/values-v28/values-v28.xml
Android resource linking failed
Android resource linking failed
app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Android resource linking failed
Android resource linking failed
Android resource linking failed
Android resource linking failed
Android resource linking failed

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，麻烦把报错截图提供下，方便进一步定位
具体问题 欢迎交流 q2562367495 注明来意

**Comment by kangear** [comment]
内部工单给解决了。
```
你把版本号写死到 8.5.10028
    liteavSdk="com.tencent.liteav:LiteAVSDK_TRTC:8.5.10028"
最新的那个版本有问题，有用到 androidx
```
