### ISSUE TITLE
windows版本sdk能提供一个CLR的版本吗，现在都只有c++原生的，其他开发语言项目无法使用，比如c#

### ISSUE THREAD

**Issue by yb12306** [tencentyun/TRTCSDK#4]

**Comment by rexchang2016** [comment]
您好，C#的版本还在规划中，SDK接口还需要彻底稳定下来，比如我们近期就发现部分客户提出了C++原生接口必须要支持dll动态加载能力，这个在设计支持疏忽了，正在调整。

等 API 完全稳定后（预期3月底），C#会进行相应的包装。

**Comment by dragonimp** [comment]
TRTCVideoViewLayout里面写的TRTCVideoViewLayout、TRTCNewViewController都还没实现吧？
还有前后叠加也没实现吧。

**Comment by dragonimp** [comment]
求c#

**Comment by MicroLightTech** [comment]
c# SDK 出来了么？

**Comment by yb12306** [comment]
c#版本还没有动静吗？

**Comment by dragonimp** [comment]
Clr版本能不能给一个可能的计划时间表，一直在等，如果不能提供我们需要考虑另外的方案了。

**Comment by dragonimp** [comment]
放弃了，用web版加个浏览器插件

**Comment by rexchang2016** [comment]
C# 版本终于抽出资源来开发了，已经基本完成了接口包装，还需要搞一个 UI ，继续努力，争取 6月底能跟各位见面。

**Comment by kamisBB** [comment]
windows C＃SDK已经开发出来，会跟下个大版本一起升级到github，如果继续，可以联系我QQ：543396998获取，谢谢大家支持

**Comment by qytc** [comment]
@rexchang2016  都7月底了，还没发出来啊。。。。

**Comment by rexchang2016** [comment]
您好，C# 版本已经发布，更新仓库即可看到，同时，api 文档见官网文档区：
https://cloud.tencent.com/document/product/647/36776
