### ISSUE TITLE
【小程序】-小程序 enterRoom(params) 可以传strRoomId吗？

### ISSUE THREAD

**Issue by xjr100419** [tencentyun/TRTCSDK#400]
https://github.com/tencentyun/qcloud-documents/issues/7129

**Comment by xjr100419** [comment]
https://github.com/tencentyun/TRTCSDK/issues/155

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，目前这边小程序暂时无法传入对应的strRoomId，非常抱歉 
技术问题，欢迎交流 ，q2562367495 注明来意
