### ISSUE TITLE
【iOS】-【6.5.7272】【使用RPSystemBroadcastPickerView做屏幕共享, 如何能使弹出来的系统的picker view自动关闭】

### ISSUE THREAD

**Issue by sr9999999** [tencentyun/TRTCSDK#405]
【当前现象】
使用RPSystemBroadcastPickerView做屏幕共享，在弹出来的系统UI点开始直播，如何能拿到这个系统UI然后在321直播开始后给他dismiss掉，大佬们救救我这个菜鸡吧

【集成包】
TRTC精简版 / 专业版Professional / 企业版Enterprise

【SDKAppID】
NA

【房间号】
NA

【useID】
NA

【问题时间段】
NA

【机型】
12以上

【之前版本有无此问题】
NA

【复现概率】
NA

【复现途径】
NA

【Demo 复现途径】
NA

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以提供相应的视频或者截图具体看下，方便进一步定位问题
技术问题 欢迎交流 q2562367495 注明来意
