### ISSUE TITLE
iOS Demo运行报错

### ISSUE THREAD

**Issue by tangbing** [tencentyun/TRTCSDK#409]
下载了TRTCSDK-master,中ios 文件夹下TRTCScenesDemo，编译运行报错如图

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/11678386/117996459-bfc6ff00-b374-11eb-94a4-4252f140a8f5.png">

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以通过pod导入一下，相关SDK，之后重新pod install 
技术问题 欢迎交流 q2562367495 注明来意
