### ISSUE TITLE
【Android】-【8.6.10097】【共享屏幕使用辅流推流时，推流时机不正确】

### ISSUE THREAD

**Issue by lhc-clover** [tencentyun/TRTCSDK#412]
【当前现象】
调用`TRTCCloud.startScreenCapture(TRTC_VIDEO_STREAM_TYPE_SUB, videoEncParams, screenShareParams)`进行屏幕分享推流，系统会弹出“将开始截取您的屏幕上显示的所有内容”弹窗，但此时SDK已经开始推流。应在点击弹窗确认后再推流

【集成包】
LiteAVSDK_TRTC

【SDKAppID】
1400395154

【房间号】
1999000123

【useID】
111111/222222

【问题时间段】
2021-05-18 11:20~11:30

【机型】
华为 Honor 8

【之前版本有无此问题】
没有。现版本使用`TRTC_VIDEO_STREAM_TYPE_BIG`共享推流也无问题，只有`TRTC_VIDEO_STREAM_TYPE_SUB`有问题

【复现概率】
必现

【复现途径】
调用`TRTCCloud.startScreenCapture(TRTC_VIDEO_STREAM_TYPE_SUB, videoEncParams, screenShareParams)`进行屏幕分享推流，停在“将开始截取您的屏幕上显示的所有内容”弹窗处

【Demo 复现途径】
可复现（多人视频会议）。停在弹窗处后会出现userId_sub的新item，5秒左右消失。且等消失后再点击弹窗的“立即开始”也无法正确推流

【相关附件】

![971621308823_ pic_hd](https://user-images.githubusercontent.com/4696605/118586257-01b8d080-b7cd-11eb-88c4-10b2c5778201.jpg)

![961621308820_ pic_hd](https://user-images.githubusercontent.com/4696605/118586272-0a110b80-b7cd-11eb-9efe-e54d57dcafac.jpg)

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，请问您是用的demo进行的测试吗，你可以在demo中搜索下是否有这类权限提醒
技术问题 欢迎交流 q2562367495 注明来意

**Comment by lhc-clover** [comment]
此为8.6的一个已知问题，工单回复将于8.7修复
