### ISSUE TITLE
【iOS】-【4.9.1】【编译问题】

### ISSUE THREAD

**Issue by wx-liubin** [tencentyun/TRTCSDK#415]
【当前现象】
在编译TRTCScenesDemo时，提示缺少
TRTCSDK/iOS/TRTCScenesDemo/VerifyPicture.html
TRTCSDK/iOS/TRTCScenesDemo/LoginCountryList.json

【集成包】
- TXIMSDK_iOS (4.9.1)

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，已和您在q沟通，建议先删除 
![77616A45-C6F9-4B92-8883-B7DFC6EDC586](https://user-images.githubusercontent.com/74762384/119338306-6d65d680-bcc2-11eb-8d61-fd0b858e92cf.jpeg)
后续有问题再反馈，技术交流 q2562367495

**Comment by wx-liubin** [comment]
移除了脚本中的2个copy文件，DONE。
