### ISSUE TITLE
【小程序-ios】-【8.7】【在多人会议页面点击右上角关闭按钮，小程序关闭了但是麦克风还在推流】

### ISSUE THREAD

**Issue by ponytony** [tencentyun/TRTCSDK#426]
【当前现象】
在多人会议页面点击右上角关闭按钮，小程序关闭了但是麦克风还在推流。这个时候房间里的另一个会发现视频已经停了，但是还能收到音频

【集成包】
TRTC精简版

【SDKAppID】
1400505272

【房间号】
9527

【useID】
4396

【问题时间段】
一直有问题，包括demo上也有一样的问题

【机型】
iphone 11

【之前版本有无此问题】
一直有问题，包括demo上也有一样的问题

【复现概率】
必现

【复现途径】
0. 微信扫一扫demo的二维码，就是readme里的那个
1. 点击多人会议
2. 输入房间号
3. 进入房间
4. 两个人以上开始聊天
5. 点击右上角的关闭按钮
6. 出现bug

【Demo 复现途径】
同上

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by sskingss** [comment]
这个是微信的策略，允许小程序在后台保活，如果希望退后台停止推流，可以在onhide中调用退房

**Comment by ponytony** [comment]
> 这个是微信的策略，允许小程序在后台保活，如果希望退后台停止推流，可以在onhide中调用退房

但其实在我看来就是个bug，因为进入后台后没法通过消息栏旁边的按钮进入小程序，后来我选择做的是在onhide时将live-pusher组件销毁掉
