### ISSUE TITLE
android  sdk版本6.5.7272 安卓机和安卓机视频 声音为什么很小 只有带耳机才能听到

### ISSUE THREAD

**Issue by ma422213631** [tencentyun/TRTCSDK#44]

**Comment by rexchang2016** [comment]
能否提供一下具体的机型信息，我们重现一下看看，可能是通话音量导致，也可能是缺少 AGC 导致

**Comment by whalehe** [comment]
可以按照这个模板提issue，https://github.com/tencentyun/TRTCSDK/issues/53，方便我们定位您的问题，然后解决您遇到的问题。
