### ISSUE TITLE
【Web】-【React Demo】【问题简述：打包build失败】

### ISSUE THREAD

**Issue by Readercyc** [tencentyun/TRTCSDK#444]
【当前现象】
新版的TRTC next +react 的demo，打包时会报错，dev可以正常跑

【集成包】
TRTC JS SDK

【复现途径】
npm run build 或者 yarn run build都会报错，看起来和webpack有关

【Demo 复现途径】
![image](https://user-images.githubusercontent.com/29268583/123933610-1dff7e00-d9c5-11eb-995c-060479c82d7d.png)
![image](https://user-images.githubusercontent.com/29268583/123933655-28ba1300-d9c5-11eb-8f4c-df8607b6cb54.png)

**Comment by Tencent-Alice** [comment]
您好，根据您的问题 react trtc这个demo工程是使用yarn管理的，如果通过 yarn，再yarn dev方式执行是正常的，请知悉
您可以使用rd /s/q node_modules 先删除npm下载的依赖，然后使用yarn install 去下载相应的依赖包，不支持使用npm去管理
在进行run或者build的操作 相关可以参考如下链接

https://github.com/tencentyun/TRTCSDK/tree/master/Web/base-react-next
技术问题 欢迎交流 q2562367495 注明来意
