### ISSUE TITLE
【Android】-【8.8.10254】【网络测速功能在断网情况下，没有错误回调】

### ISSUE THREAD

**Issue by s1rius** [tencentyun/TRTCSDK#445]
【当前现象】
运行sdk-demo中网络测速功能，断开网络连接，onSpeedTest，onError，onWarning方法都没有回调。

预期：
当网络差或者断网的情况下进行网络测试， 每个IP地址测速的结果都通过onSpeedTest回调，无论网络质量好坏。
在回调参数中，如果是断网情况，网路不通的，希望TRTCSpeedTestResult的quality为0，upLostRate，downLostRate为1
或者通过onError回调测速错误
[speedtest.log](https://github.com/tencentyun/TRTCSDK/files/6762407/speedtest.log)

当前：
没有方法回调

【机型】
Google Pixel 3

【Demo 复现途径】
可复现  
1. 点击Demo
2. 进入 TRTC网络测试
3. 等待 ...
4. 出现 Bug

**Comment by Tencent-Alice** [comment]
您好，根据您的问题 可以参考这个看下https://cloud.tencent.com/document/product/269/44477#.E4.BA.8B.E4.BB.B6.E7.9B.91.E5.90.AC.E5.99.A8  事件监听器  
![1625480665240_9996](https://user-images.githubusercontent.com/74762384/124529309-da7d9780-de3c-11eb-9596-6f6096d827cd.png)

 技术问题  欢迎交流   Q2562367495  注明来意

**Comment by s1rius** [comment]
> 您好，根据您的问题 可以参考这个看下https://cloud.tencent.com/document/product/269/44477#.E4.BA.8B.E4.BB.B6.E7.9B.91.E5.90.AC.E5.99.A8 事件监听器
> ![1625480665240_9996](https://user-images.githubusercontent.com/74762384/124529309-da7d9780-de3c-11eb-9596-6f6096d827cd.png)
> 
> 技术问题 欢迎交流 Q2562367495 注明来意

给出的链接是IMSDK的，这个问题是TRTCSDK的
