### ISSUE TITLE
【C#SDK Windows 10】TRTC 8.8.0

### ISSUE THREAD

**Issue by jingsong-liu** [tencentyun/TRTCSDK#446]
复现概率：必现
复现方法：用户使用主流推送桌面分享

问题描述：
用主流推送远程桌面，该用户不会出发onEnterRoom时间， 其他用户也感知不到它的进房事件；

` _trtcCloud.startScreenCapture(IntPtr.Zero, TRTCVideoStreamType.TRTCVideoStreamTypeBig, null);`

用TRTCVideoStreamTypeSub 子流推送桌面分享就没有问题。

 请问怎么解决?

日志：

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，您测试下demo看是否有这个问题，https://cloud.tencent.com/document/product/647/17021
技术问题 欢迎交流 q2562367495 注明来意

**Comment by jingsong-liu** [comment]
有这个问题， QQ加过了，不顶用啊

**Comment by Tencent-Alice** [comment]
您好，您在和我联系下，q信息有点多，辛苦

**Comment by Tencent-Alice** [comment]
您好，您和我在联系下，q信息有点多，辛苦

**Comment by jingsong-liu** [comment]
多谢帮忙解决问题
