### ISSUE TITLE
【Windows C# SDK】-【8.0.0】【桌面共享窗体高亮 - 最大化的窗体共享后无法看见边框高亮】

### ISSUE THREAD

**Issue by jingsong-liu** [tencentyun/TRTCSDK#448]
【当前现象】

 最大化的窗体共享后无法看见边框高亮

[期望现象]
能够看见边框（否则不知道什么窗体正在被分享）
【集成包】
TRTC精简版 
【SDKAppID】
1400XXXXXX

【房间号】
123456

【useID】
userNameA

【问题时间段】
2021-07-14 13:23~16:55

【机型】
Windows10 PC

【之前版本有无此问题】
一直有

【复现概率】
必现 

【复现途径】
1. 调用startScreenCapture

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，目前版本sdk是不会显示最大化窗口边框，这个需求可以业务侧绘制边框，请知悉
技术问题 欢迎交流 q2562367495 注明来意

**Comment by jingsong-liu** [comment]
业务侧不能优雅的判定是否需要绘制。
请考虑SDK评估下能否内置该功能

**Comment by Tencent-Alice** [comment]
您好，SDK目前暂时未支持当窗口全屏化后描边。后续sdk暂不会内置该功能，请知悉。您可以使用Windows的API判断窗口是否为最大化，参见第三方文档，https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-iszoomed
技术问题 欢迎交流 q2562367495 注明来意
