### ISSUE TITLE
【WEB】-【TRTC Web SDK v4.11.3】【进房失败 JOIN_ROOM_FAILED 0x4004】

### ISSUE THREAD

**Issue by sa0ChunLuyu** [tencentyun/TRTCSDK#472]
【当前现象】：进房失败 JOIN_ROOM_FAILED 0x4004
【集成包】：TRTC WEB
【SDKAppID】：1400528939
【房间号】: -
【useID】：15232310906
【问题时间段】：2021.08.06 15:00
【机型】：iPhone11
【是否必现】：必现
【复现方法】：发起视频，另一个用户接受时。

【相关附件】
运行DEMO后  登录了两个用户  一个用户发起视频后，另一个用户接受。 会出现这样的问题。
![WechatIMG234](https://user-images.githubusercontent.com/46621242/128473229-d514f523-b898-438a-98d5-aff5585f07f4.jpeg)

之后修改了 App.vue 232行的代码。
<img width="569" alt="WechatIMG233" src="https://user-images.githubusercontent.com/46621242/128473384-5fc3cd1d-3a01-4998-97f1-dde88c0360b7.png">

apply的报错没有了，JOIN_ROOM_FAILED 0x4004 还是存在。
![WechatIMG235](https://user-images.githubusercontent.com/46621242/128473483-ac78dabc-c519-439c-9b6b-f067c24711f3.jpeg)

是我在跑DEMO的时候 哪个环节遗漏了吗？

**Comment by Tencent-Alice** [comment]
您好，看您的报错，需要在im的控制台把trtc的权限开通试下，请知悉
技术问题 欢迎交流 q2562367495 注明来意

**Comment by sa0ChunLuyu** [comment]
问题解决了.感谢
