### ISSUE TITLE
web端 进入房间报-10014 error错误

### ISSUE THREAD

**Issue by chenwenxiu** [tencentyun/TRTCSDK#480]
【当前现象】
如进房失败，提示错误码xxxx

【集成包】
TRTC精简版 / 专业版Professional / 企业版Enterprise

【SDKAppID】
1400XXXXXX

【房间号】
123456

【useID】
userNameA

【问题时间段】
2019-09-01 16:23~16:55

【机型】
如iPhone 7 Plus

【之前版本有无此问题】
如6.4之前没有，6.6有

【复现概率】
必现 / 偶现(如有大约概率请标明)

【复现途径】
1. 调用 ... API
2. 调用 ... API
3. 在 ... 回调中调用 ...
4. 在 ... 回调中调用 ...
5. 出现 Bug

【Demo 复现途径】
可复现  / 不可复现
1. 点击 ...
2. 进入 ..
3. 等待 ...
4. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by Tencent-Alice** [comment]
您好，根据您的问题  可以先检查一下目前目前该房间是已进入人数过多，目前最多持30
![019B0CD2-91FA-45F0-B2DE-824074E29A21](https://user-images.githubusercontent.com/74762384/129648480-38b8173d-e6a6-4382-94c2-258e2a63dd51.jpeg)
人同时开启摄像头，您可以切换用户身份为观众角色进房进行测试没查看是否正常。
https://trtc-1252463788.file.myqcloud.com/web/docs/Client.html#join
技术问题 欢迎交流 q2562367495 注明来意
