### ISSUE TITLE
【TRTC-Web】-【3.3】【无法将视频流推送到另外一端，提示错误码getUserMedia error observed NotAllowedError: Failed due to shutdown】

### ISSUE THREAD

**Issue by lbp608** [tencentyun/TRTCSDK#485]
【当前现象】
实时音视频Demo（web）。微信内置浏览器，通过公众号，或者聊天窗口的连接打开的界面，只能显示对方视频界面，无法把本地视频推给对方。
通过微信开发者工具调试发现报错：
getUserMedia error observed NotAllowedError: Failed due to shutdown
TRTCCalling 19:57:37.690:TRTCClient.join - failed to initialize local stream - NotAllowedError: Failed due to shutdown
TRTCCalling 19:57:37.700:TRTCClient.join - join room failed! NotAllowedError: Failed due to shutdown

【集成包】
实时音视频->快速入门->跑通Demo(Web)

【复现概率】
必现 

【复现途径】
uniapp，集成实时音视频Web SDK，在微信内置浏览器访问。

【Demo 复现途径】
实时音视频Demo（web），TRTCScenesDemo项目。使用微信内置浏览器。

【相关附件】
![微信图片_20210901201239](https://user-images.githubusercontent.com/3361894/131669240-8ea8914e-5ab5-44a6-b20f-b6a5d626e391.png)

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，webrtc不支持微信内置浏览器，请知悉
![6C62723E-F625-4C2C-BC2B-E0C5B6FFBC75](https://user-images.githubusercontent.com/74762384/131943725-98184b5d-7eb4-4dd2-b16e-b99e92309311.jpeg)
技术问题 欢迎交流 q2562367495 注明来意

**Comment by Rychou** [comment]
WebRTC 支持手机微信内置浏览器，TRTCCalling 中实时音视频通话是基于 TRTC Web SDK 实现的，详情参考 [TRTC Web SDK 浏览器支持情况](https://web.sdk.qcloud.com/trtc/webrtc/doc/zh-cn/tutorial-05-info-browser.html)
