### ISSUE TITLE
【iOS】-【9.2.10637】getCustomAudioRenderingFrame无法获得音频数据

### ISSUE THREAD

**Issue by tctony** [tencentyun/TRTCSDK#498]
【当前现象】
getCustomAudioRenderingFrame接口设计的有问题，传入参数类型TRTCAudioFrame，其中的data字段类型为NSData，内部无法修改，也就无法把音频数据传出来。

即使在data字段传入一个NSMutableData，调用getCustomAudioRenderingFrame完成，data的内容也没有被修改。

【集成包】
TRTC精简版 

【复现途径】
1. 进入房间之前，调用-[TRTCCloud enableCustomAudioRendering:YES]
2. 进入房间
3. 调用getCustomAudioRenderingFrame获取音频数据帧，无法获得。

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，请提供下具体的trtc版本号，方便进一步定位问题 
技术问题 欢迎交流 q2562367495 注明来意

**Comment by tctony** [comment]
> 您好，关于您的问题，请提供下具体的trtc版本号，方便进一步定位问题 技术问题 欢迎交流 q2562367495 注明来意

... 

标题上有版本号呀 ：【iOS】-【9.2.10637】

另外这个QQ号也加不上。。。
