### ISSUE TITLE
android 安卓端SDK 进入房间的时候recordId参数怎么传进去？

### ISSUE THREAD

**Issue by joviqiao** [tencentyun/TRTCSDK#51]
android 安卓端SDK 进入房间的时候recordId参数怎么传进去？

web端可以直接传进去的，但是android找不到地方传啊！！！ 无语，视频回调也很奇葩，参数名完全不一致，不知道你们在干什么

**Comment by joviqiao** [comment]
@rexchang2016  帮忙看看咯...  实在没有我就换种方式区分环境。。。

**Comment by joviqiao** [comment]
什么玩意垃圾，日了狗，还没有阿里的好用

**Comment by WeiqiChenZY** [comment]
拜托，这是github，有人watch了这个项目，你发这些东西会广播到大家的邮箱里边的。文明用语好嘛。

**Comment by rexchang2016** [comment]
您好，可以通过 TRTCParams 中的 businessInfo 字段进行指定 "recordId: "，这个功能目前被咨询的不多，我们没有放在官方文档里，非常抱歉。

{
    "Str_uc_params":
    {
         "record_id": 43567, //可选字段,自动录制时业务自定义id，int32，录制回调时给到用户.注意:同一个房间中的成员,这个字段要么全带,要么不带.且值需要一致
        "pure_audio_push_mod": 0, //可选字段，如果是纯音频录制，需要设置为 2。
        "recordfile_storage_time":10000, //录制文件保存时长,单位秒
    }
}
