### ISSUE TITLE
【Web】-【6.5.7272】【发起语言公话类型错误应该为AUDIO_CALL】

### ISSUE THREAD

**Issue by SkyLandBeast** [tencentyun/TRTCSDK#510]
文件路径：Web/TRTCScenesDemo/trtc-calling-web/src/components/audio-call/index.vue
错误代码：
   handleCallUser: function({ param }) {
      this.callFlag = true
      this.$trtcCalling.call({
        userID: param,
        **type: this.TrtcCalling.CALL_TYPE.VIDEO_CALL**
      }).then(()=>{
        this.callFlag = false
        this.$store.commit("userJoinMeeting", this.loginUserInfo.userId);
        this.$store.commit("updateCallStatus", "calling");
        this.$store.commit("updateIsInviter", true);
      }) }
正确代码
   handleCallUser: function({ param }) {
      this.callFlag = true
      this.$trtcCalling.call({
        userID: param,
        **type: this.TrtcCalling.CALL_TYPE.AUDIO_CALL**
      }).then(()=>{
        this.callFlag = false
        this.$store.commit("userJoinMeeting", this.loginUserInfo.userId);
        this.$store.commit("updateCallStatus", "calling");
        this.$store.commit("updateIsInviter", true);
      })}

**Comment by Gintangible** [comment]
+1
