### ISSUE TITLE
【Electron】-【8.9.102】【m1pro macos trtc_electron_sdk.node 文件找不到】

### ISSUE THREAD

**Issue by AllenTom** [tencentyun/TRTCSDK#511]
【当前现象】
依赖安装完成后启动Electron控制台输出错误。

是否是文件仅支持x86_64不支持arm64e架构的问题。
```
trtc_electron_sdk.node:1 Uncaught Error: Cannot open node_modules/trtc-electron-sdk/build/Release/trtc_electron_sdk.node: Error: dlopen(node_modules/trtc-electron-sdk/build/Release/trtc_electron_sdk.node, 0x0001): tried: '/Users/duzhengheng/Desktop/project/msc22/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/node_modules/trtc-electron-sdk/build/Release/trtc_electron_sdk.node' (no such file), '/Users/duzhengheng/Desktop/project/msc22/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS/../../../node_modules/trtc-electron-sdk/build/Release/trtc_electron_sdk.node' (no such file), 'node_modules/trtc-electron-sdk/build/Release/trtc_electron_sdk.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/trtc_electron_sdk.node' (no such file), '/usr/lib/trtc_electron_sdk.node' (no such file), '/Users/duzhengheng/Desktop/project/msc22/node_modules/trtc-electron-sdk/build/Release/trtc_electron_sdk.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/trtc_electron_sdk.node' (no such file), '/usr/lib/trtc_electron_sdk.node' (no such file)
    at Object../node_modules/trtc-electron-sdk/build/Release/trtc_electron_sdk.node (trtc_electron_sdk.node:1)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../node_modules/trtc-electron-sdk/liteav/trtc.js (trtc.js:24)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Module../src/trtc.ts (main.js:103051)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Module../src/hooks/TRCTVideo.ts (main.js:97694)
```

【SDKAppID】
1400575330

【房间号】
无

【useID】
无

【问题时间段】
2021.11.22

【机型】
macbook m1pro

【之前版本有无此问题】
有
【复现概率】
必现

【复现途径】
按照教程导入SDK之后就会显示

【Demo 复现途径】

【相关附件】

**Comment by sophiezzhou** [comment]
可以参考下这个来解决问题   https://www.jurnalanas.com/node-js-mac-m1/

**Comment by sophiezzhou** [comment]
可以通过切换到x86_64环境来解决此问题，以上链接有详细步骤

**Comment by sophiezzhou** [comment]
首先，可以确认下你在arm64架构上
```
$ node -p process.arch
arm64
```

然后可以通过以下命令切换到 x64 架构环境上
`$ arch -x86_64 zsh`


可以查看下现在的架构环境是否正确

```
$ node -p process.arch
x64
```

再使用nvm安装node

 nvm install v14.15.4

接着，再次确认下现在的架构环境是否正确

$ n```
ode -p process.arch
x64
```

现在就可以进行依赖安装，并启动Electron控制台

后续也可以继续回到 arm64架构环境
`$ exit`
```

$ arch
arm64
```

**Comment by sophiezzhou** [comment]
首先，可以确认下你在arm64架构上
`$ node -p process.arch`
arm64

然后可以通过以下命令切换到 x64 架构环境上
`$ arch -x86_64 zsh`


可以查看下现在的架构环境是否正确

`$ node -p process.arch`
x64

再使用nvm安装node

 `nvm install v14.15.4`

接着，再次确认下现在的架构环境是否正确

`$ node -p process.arch`
x64

现在就可以进行依赖安装，并启动Electron控制台

后续也可以继续回到 arm64架构环境
`$ exit`
`$ arch`
arm64

**Comment by sophiezzhou** [comment]
> 首先，可以确认下你在arm64架构上 `$ node -p process.arch` arm64
> 
> 然后可以通过以下命令切换到 x64 架构环境上 `$ arch -x86_64 zsh`
> 
> 可以查看下现在的架构环境是否正确
> 
> `$ node -p process.arch` x64
> 
> 再使用nvm安装node
> 
> `nvm install v14.15.4`
> 
> 接着，再次确认下现在的架构环境是否正确
> 
> `$ node -p process.arch` x64
> 
> 现在就可以进行依赖安装，并启动Electron控制台
> 
> 后续也可以继续回到 arm64架构环境 `$ exit` `$ arch` arm64

目前我们的 electron sdk 是暂时没有支持 arm64 架构的 .node 文件的。

**Comment by AllenTom** [comment]
问题已经解决了，使用x64架构的Nodejs就可以了，Rosetta可以自动转译，目前没发现任何问题。

**Comment by szwang-wthealth** [comment]
你好，能详细说一下使用“x64架构的Nodejs”是什么意思嘛？我这边也遇到了这个问题，而且我用得应该就是x64架构的
![bdfb079f0608248af40e9a4dcc165e2](https://user-images.githubusercontent.com/43228022/210943366-4c32e976-1f62-40fb-a295-e64fbad2ea9c.jpg)
![7163705d38c2c74fd44fd83d3783862](https://user-images.githubusercontent.com/43228022/210943389-6a1ead6d-3a03-44eb-9d3a-5c4be01dcffe.png)
![24983cebc67dad559c18b599eee13d0](https://user-images.githubusercontent.com/43228022/210943396-78bec3b4-d1a0-450a-b5fe-25f512223510.png)

**Comment by sophiezzhou** [comment]
目前从electron 10.6.403 版本已经支持了双架构
<img width="1020" alt="Screen Shot 2023-01-11 at 11 46 56" src="https://user-images.githubusercontent.com/94435644/211713215-6457d6d6-b9a4-431d-b87f-71d7eb175e14.png">

**Comment by sophiezzhou** [comment]
> 目前从electron 10.6.403 版本已经支持了双架构 <img alt="Screen Shot 2023-01-11 at 11 46 56" width="1020" src="https://user-images.githubusercontent.com/94435644/211713215-6457d6d6-b9a4-431d-b87f-71d7eb175e14.png">
详细可看下腾讯云文档：https://cloud.tencent.com/document/product/647/62562#90d73165-fbbd-4aea-90d2-4a0a9bbf4d8a


> 你好，能详细说一下使用“x64架构的Nodejs”是什么意思嘛？我这边也遇到了这个问题，而且我用得应该就是x64架构的 ![bdfb079f0608248af40e9a4dcc165e2](https://user-images.githubusercontent.com/43228022/210943366-4c32e976-1f62-40fb-a295-e64fbad2ea9c.jpg) ![7163705d38c2c74fd44fd83d3783862](https://user-images.githubusercontent.com/43228022/210943389-6a1ead6d-3a03-44eb-9d3a-5c4be01dcffe.png) ![24983cebc67dad559c18b599eee13d0](https://user-images.githubusercontent.com/43228022/210943396-78bec3b4-d1a0-450a-b5fe-25f512223510.png)
