### ISSUE TITLE
请问C# ManageIM.dll的维护计划？

### ISSUE THREAD

**Issue by dujianxin** [tencentyun/TRTCSDK#52]
在之前使用移动直播C#SDK时，SDK中包含C#封装的ManageIM.dll用于信令消息通知，在使用TRTC时，SDK中已无该文件，但实际应用场景是呼叫方创建房间后仍然需要通过IM将房间号通知接听方，接听方才能加入指定房间，此问题目前可以继续使用原移动直播提供的ManageIM.dll暂缓解决，但后续TRTC提供x64版本时，ManageIM.dll将不再可用，现咨询ManageIM.dll的维护计划，今后是官方继续提供，还是需要开发者自行维护，如果是开发者自行维护，是否可以考虑开源，谢谢！

**Comment by Pmjin** [comment]
您好，如果您现在急需使用IM信令消息通知进房的话，可以考虑继续在TRTC中集成旧版的ManageIM.dll使用；如果现在暂时不着急的话，我们大概会在国庆后提供IM最新版的C# SDK x86和x64版本，由于新版IM接口会有部分改动，后续可能需要根据IM新版API修改相关接口调用。

**Comment by dujianxin** [comment]
C#x64版本已经发布，没有看到ManageIM.dll呢？
