### ISSUE TITLE
【Electron】-【7.9.348】【回音如何消除？】

### ISSUE THREAD

**Issue by johnlin0207** [tencentyun/TRTCSDK#543]
【当前现象】
B端iMac用的自带外放+外接的mic，房间比较小导致回音明显，A端iPhone 12 Pro Max说话B端先同步播放，不久后B端再次播放刚才同步播放时的音频

【集成包】
"trtc-electron-sdk": "7.9.348",

【机型】
iPhone 12 Pro Max & iMac

【复现概率】
必现

【复现途径】
开启本地麦克风采集 trtcCloud.startLocalAudio();不做音频其他设置

**Comment by johnlin0207** [comment]
web端有这些设置，没在electorn版看见？
echoCancellation：回声消除开关
noiseSuppression：噪声抑制开关
autoGainControl：自动增益开关

**Comment by Tencent-Alice** [comment]
您好 根据您的问题 可以参考https://web.sdk.qcloud.com/trtc/webrtc/doc/zh-cn/tutorial-02-info-webrtc-issues.html#h2-4  
技术问题 欢迎交流 Q2562367495 注明来意

**Comment by johnlin0207** [comment]
应该是使用不当导致
