### ISSUE TITLE
视频通话

### ISSUE THREAD

**Issue by wangwei0017** [tencentyun/TRTCSDK#55]
1、A和B两个人进行视频沟通，录制的视频是否可以达到以下效果。
（1）视频展示两个人的画面，两个人均有视频画面和声音。
（2）视频只展示A的画面，但两人都有声音。（B不展示画面只有声音）
2、视频是否可以等对方接通之后再开始录制？
3、视频录制的时效如何？挂断后多久能拿到视频？
4、一方中断，或者两方都中断之后再进入房间，会录制成几份视频？
5、房间号怎么生成？
6、是否可以一方开着摄像头，但不让另外一方看到自己的的画面，只能听到声音。

**Comment by 6e6e6e** [comment]
1、A和B两个人进行视频沟通，录制的视频是否可以达到以下效果。
（1）视频展示两个人的画面，两个人均有视频画面和声音。
（2）视频只展示A的画面，但两人都有声音。（B不展示画面只有声音）
----->这个需求有些定制，需要手动调用云端混流的restapi来实现。
第(1)个通过指定A+B混流，会自动录制混流后的画面；
第(2)项可以通过图层指定将A覆盖在B之上，或者是指定B的类型为纯音频来实现；
云端混流的接口参数说明在 https://cloud.tencent.com/document/product/267/8832

2、视频是否可以等对方接通之后再开始录制？
----->目前只有自动录制，有上行数据后就会开始录制，可以录制之后再配置云点播的处理剪裁

3、视频录制的时效如何？挂断后多久能拿到视频？
----->视频录制是通过腾讯云云直播和云点播服务来实现，时效上根据分片时间来定，大于分片时间的，按分片时间生成文件，小于分片时间的，结束后就会生成文件。
相关的说明可以参考云端录制：https://cloud.tencent.com/document/product/647/16823
（原理是利用云直播的录制，云直播的录制说明见https://cloud.tencent.com/document/product/267/32739）

4、一方中断，或者两方都中断之后再进入房间，会录制成几份视频？
----->看是否超时，TRTC的超时判断是30秒无数据。超时时间内，中断的视频会连接上保存成同一个，超时时间以外，会重新启动新的录制文件

5、房间号怎么生成？
------>房间号是开发者自定义的uint32类型的数字

6、是否可以一方开着摄像头，但不让另外一方看到自己的的画面，只能听到声音。
------>TRTC的SDK默认就是只接收音频。如需自定义音视频流的订阅，可以通过SDK的方法来实现，参看文档说明：
https://cloud.tencent.com/document/product/647/32267#.E8.A7.86.E9.A2.91.E7.9B.B8.E5.85.B3.E6.8E.A5.E5.8F.A3.E5.87.BD.E6.95.B0（这是Android端的API，其他端可自行查阅）

**Comment by wangwei0017** [comment]
好的，多谢，
在2019年09月26日 11:13，6e6e6e<notifications@github.com> 写道：

1、A和B两个人进行视频沟通，录制的视频是否可以达到以下效果。
（1）视频展示两个人的画面，两个人均有视频画面和声音。
（2）视频只展示A的画面，但两人都有声音。（B不展示画面只有声音）
----->这个需求有些定制，需要手动调用云端混流的restapi来实现。
第(1)个通过指定A+B混流，会自动录制混流后的画面；
第(2)项可以通过图层指定将A覆盖在B之上，或者是指定B的类型为纯音频来实现；
云端混流的接口参数说明在 https://cloud.tencent.com/document/product/267/8832

2、视频是否可以等对方接通之后再开始录制？
----->目前只有自动录制，有上行数据后就会开始录制，可以录制之后再配置云点播的处理剪裁

3、视频录制的时效如何？挂断后多久能拿到视频？
----->视频录制是通过腾讯云云直播和云点播服务来实现，时效上根据分片时间来定，大于分片时间的，按分片时间生成文件，小于分片时间的，结束后就会生成文件。
相关的说明可以参考云端录制：https://cloud.tencent.com/document/product/647/16823
（原理是利用云直播的录制，云直播的录制说明见https://cloud.tencent.com/document/product/267/32739）

4、一方中断，或者两方都中断之后再进入房间，会录制成几份视频？
----->看是否超时，TRTC的超时判断是30秒无数据。超时时间内，中断的视频会连接上保存成同一个，超时时间以外，会重新启动新的录制文件

5、房间号怎么生成？
------>房间号是开发者自定义的uint32类型的数字

6、是否可以一方开着摄像头，但不让另外一方看到自己的的画面，只能听到声音。
------>TRTC的SDK默认就是只接收音频。如需自定义音视频流的订阅，可以通过SDK的方法来实现，参看文档说明：
https://cloud.tencent.com/document/product/647/32267#.E8.A7.86.E9.A2.91.E7.9B.B8.E5.85.B3.E6.8E.A5.E5.8F.A3.E5.87.BD.E6.95.B0（这是Android端的API，其他端可自行查阅）
