### ISSUE TITLE
called unimplemented OpenGL ES API

### ISSUE THREAD

**Issue by TangHaifeng-John** [tencentyun/TRTCSDK#57]
报错，called unimplemented OpenGL ES API 这个问题该如何解决?

**Comment by 6e6e6e** [comment]
请参考issue格式，提供一下具体的接口调用及打印信息，我们看一下

**Comment by whalehe** [comment]
可以按照这个模板提issue，https://github.com/tencentyun/TRTCSDK/issues/53，方便我们定位您的问题，然后解决您遇到的问题。
