### ISSUE TITLE
Android 画面丢失

### ISSUE THREAD

**Issue by eritpchy** [tencentyun/TRTCSDK#6]
版本:
com.tencent.liteav:LiteAVSDK_TRTC:6.1.6454
3.0/WebRTCAPI.min.js

Android  <==> WebRTC 对接
为什么 WebRTC 刷新了一下网页Android 端画面就不显示了?
老版本的 1.96 SDK 并没有这个问题

正常的日志
D/TRTCCloudImpl: trtc_api onMemberEnter 144115205291927080, 1, 9

出现问题的日志
D/TRTCCloudImpl: trtc_api onMemberEnter 144115205291927080, 1, 8

**Comment by eritpchy** [comment]
![image](https://user-images.githubusercontent.com/8630635/53145306-a80bd080-35da-11e9-939c-69fd417263bd.png)

补充

**Comment by eritpchy** [comment]
已确认是WebRTC中的 RTC.getLocalStream 和 RTC.createRoom 调用先后顺序导致的,
1.96旧版本并没有这个现象

**Comment by rexchang2016** [comment]
收到，我们周一跟web组的同学一起跟进看一下

**Comment by anderlu** [comment]
1.96 旧版本 指的是 android sdk 还是 WebRTCAPI.min.js的版本？

> 已确认是WebRTC中的 RTC.getLocalStream 和 RTC.createRoom 调用先后顺序导致的,
> 1.96旧版本并没有这个现象

**Comment by eritpchy** [comment]
1.96 旧版本 指的是 android sdk的版本

**Comment by anderlu** [comment]
WebRTC 页面刷新后要重新进房间，再进行获取流和推流。 刷新页面后如果没有调用进房和推流的接口 ，Adnroid端是看不到画面的。

**Comment by eritpchy** [comment]
当然调用了, 音频过来了 画面没过来, 刷新页面阿, 初始化流程每次都是一样的!
