### ISSUE TITLE
苹果手机音视频使用bigsmall模板无法进行视频

### ISSUE THREAD

**Issue by raojie666** [tencentyun/TRTCSDK#62]
【当前现象】：音视频bigsmall模板在苹果手机上无法视频
【机型】：所有苹果手机
【日志或者描述、截图】：
音视频bigsmall模板在苹果手机上无法视频，但是安卓手机上此模板可以正常视频，以前苹果机上是好的，麻烦帮忙看看

**Comment by cqworker** [comment]
遇到相同问题

**Comment by anderlu** [comment]
请尝试在 小程序 app.json 的 window 配置项加上 ,
    "renderingMode": "seperated"
