### ISSUE TITLE
【Web】外接摄像头视频时无法调取摄像头

### ISSUE THREAD

**Issue by raojie666** [tencentyun/TRTCSDK#63]
【当前现象】：音视频web端使用外接摄像头无法调起摄像头
【机型】：所有windows7的电脑
【日志或者描述、截图】：
台式电脑上使用外接摄像头，在windows10上可以视频，但在windows7上无法调起摄像头

**Comment by anderlu** [comment]
这边无法重现该问题，是否有报错信息？

**Comment by raojie666** [comment]
errorCode: 10008
errorMsg: "get user media failed : error = NotFoundError global.constraints:{"audio":true,"video":true}"
extInfo: DOMException
code: 8
constraint: {audio: true, video: true}
message: "Requested device not found"
name: "NotFoundError"

**Comment by whalehe** [comment]
您好，可以升级到最新版本，试试~
