### ISSUE TITLE
Windows WPF MediaElement 可以显示视频流么？  URI 是什么

### ISSUE THREAD

**Issue by jingsong-liu** [tencentyun/TRTCSDK#64]
Demo上用的Win Form写的。 现在我们需要用WPF写客户端。   

如果有一套WPF 写的CSharp Demo就更好了。

**Comment by qytc** [comment]
MediaElement 不可以用。要用win32的控件。

**Comment by jingsong-liu** [comment]
最近项目在WPF集成上遇到问题， 在网上查找了一下，也有网友提出如下问题：
1.C#SDK提供了Winform程序的快速入门Demo，但是所有图像预览功能 皆采用 获取控件句柄的方式进行覆盖显示。

2.WPF程序不提供普通控件如Border等UIelement的控件句柄，所有控件句柄都和窗体句柄一致，如果使用startRemoteView方式，视频图像会绘制到整个窗体。

3.如果使用WindowsFormsHost承载winform普通控件，虽然可以正常显示图像，但是由于wpf实现winform的特殊方式，图像会一直显示在wpf窗体之上，且不支持各种动画。无法满足交互需求。

请问能否适配 WPF出一套Demo ？

摘自问题： https://cloud.tencent.com/developer/ask/227773

**Comment by Pmjin** [comment]
您好，非常抱歉那么久才回复您。首先，非常感谢您的反馈，目前 Windows C# 版已经使用 WPF 框架实现了自定义渲染功能的简单示例Demo，不过现在还在测试阶段，如有需要，可直接 +QQ 522469822 联系我，可以先提供 Demo 示例代码，我们后续也会把 WPF 示例 Demo 上传 Github。
