### ISSUE TITLE
【Web】-【3.1.0】macOS 更新至 10.15 Catalina 之后，屏幕分享无法工作

### ISSUE THREAD

**Issue by xro-maestera** [tencentyun/TRTCSDK#65]
【当前现象】：macOS 更新至 10.15 Catalina 之后，屏幕分享无法获取本地视频流，隐私设置中已给予 Google Chrome 屏幕录制权限
【集成包】：WebRTC
【机型】：macOS 10.15, Google Chrome 77.0.3865.90
【之前版本有无此问题】：所有版本都有此问题
【是否必现】：必现
【复现方法】：使用最新官方 Demo 测试开启屏幕分享，依旧有此问题

**Comment by anderlu** [comment]
感谢反馈，我们已经跟进该问题

**Comment by zhangyuiris** [comment]
@xro-maestera 请问您的mac有给Chrome开启权限吗
<img width="668" alt="截屏2019-10-17下午7 19 59(1)" src="https://user-images.githubusercontent.com/25410539/67004633-4cff8e80-f113-11e9-8174-9941e79d6299.png">

**Comment by xro-maestera** [comment]
_> @xro-maestera 请问您的mac有给Chrome开启权限吗
> <img alt="截屏2019-10-17下午7 19 59(1)" width="668" src="https://user-images.githubusercontent.com/25410539/67004633-4cff8e80-f113-11e9-8174-9941e79d6299.png">

有的，同时也试过取消勾选再选中以及重装 Chrome

**Comment by anderlu** [comment]
浏览器问题，暂时无法兼容
