### ISSUE TITLE
[Android] TRTC万人延时直播小视频窗口位置修改不了?急!急!急!

### ISSUE THREAD

**Issue by Fuge2008** [tencentyun/TRTCSDK#67]
Android端修改如下代码,不生效,请问是什么原因导致修改视频小窗口位置没有生效?

**Comment by tao-pu** [comment]
您好，请问你是如何修改小窗口位置的，代码可以贴一下

**Comment by whalehe** [comment]
可以按照这个模板提issue，https://github.com/tencentyun/TRTCSDK/issues/53

如有代码修改，需要您贴下代码，方便我们定位您的问题，然后解决您遇到的问题。
