### ISSUE TITLE
【Android】- 【v6.7.7754】 demo 语音通话播放出来的声音很小

### ISSUE THREAD

**Issue by Jimmy-J** [tencentyun/TRTCSDK#69]
【当前现象】：使用 demo 语音通话播放出来的声音很小
【集成包】：v6.7.7754 demo 
【房间号】: 1
【useID】：1
【问题时间段】：2019-10-18 19:10~19:30
【机型】：使用三星 S5P6818 开发板的硬件方案
【是否必现】：必现

**Comment by realing** [comment]
可以尝试关闭通话音量试一下
