### ISSUE TITLE
Android 切出后画面停住

### ISSUE THREAD

**Issue by eritpchy** [tencentyun/TRTCSDK#7]
多次切入切出(2次左右) Activity 均会出现画面停住的现象

系统会报告 这个日志
E/libEGL: eglSwapBuffersWithDamageKHR:1384 error 300d (EGL_BAD_SURFACE)

小米8(Android P) 和 三星8都会出现

**Comment by rexchang2016** [comment]
我们现在测试平台上用您说的型号的手机验证一下，感谢您的反馈，我们一般两周时间内可以修复本轮迭代提出的bug。

**Comment by rexchang2016** [comment]
您好，我们用三星s8,反复试验，没有发现您说的卡死问题，您是否方便提供一份log给我们分析一下？

**Comment by eritpchy** [comment]
切入切出应用哦, 不知道你们的操作过程跟我的一不一样

**Comment by rexchang2016** [comment]
嗯 SDK 的 enterroom 不需要再 onResume() 时再调用，因为 SDK 内部会自动处理 app 前后台切换的问题，再次调用 enterroom 会打乱正常的业务逻辑。
