### ISSUE TITLE
微信小程序 指定画面质量

### ISSUE THREAD

**Issue by SkyGrass** [tencentyun/TRTCSDK#70]
功能需求：微信小程序 手动指定画面质量。

**Comment by tingyuji** [comment]
目前不支持吗？

**Comment by SkyGrass** [comment]
> 目前不支持吗？

目前支持吗？

**Comment by 6e6e6e** [comment]
微信小程序的<live-pusher>和<live-player>是通过视频码率来确定分辨率级别，如果对于画面质量有要求，可以参考以下码率范围，尝试设置最小及最大码率以确定分辨率（注意：网络较差时，码率变化仍会造成画面分辨率变化）：
- 360P：400-600kbps
- 540P：500-1000kbps
- 720P：800-1200kbps

**Comment by SkyGrass** [comment]
> 微信小程序的和是通过视频码率来确定分辨率级别，如果对于画面质量有要求，可以参考以下码率范围，尝试设置最小及最大码率以确定分辨率（注意：网络较差时，码率变化仍会造成画面分辨率变化）：
> 
> * 360P：400-600kbps
> * 540P：500-1000kbps
> * 720P：800-1200kbps

已经设置了，感谢。
