### ISSUE TITLE
web调用了stop,close,leave方法摄像头资源还是占用

### ISSUE THREAD

**Issue by 285878535** [tencentyun/TRTCSDK#75]
【当前现象】：成功开启摄像头调用关闭方法，摄像头灯和地址栏摄像头标志依然显示启用状态
【集成包】：TRTC精简版
【机型】：web
【之前版本有无此问题】：不清楚
【是否必现】：必现 ，
【复现方法】：成功开启摄像头调用关闭方法，摄像头灯和地址栏摄像头标志依然显示启用状态
【日志或者描述、截图】：
` const videoTrack = this.localStream.getVideoTrack();
if (videoTrack) {
  console.log(videoTrack);  
  this.localStream.removeTrack(videoTrack).then(() => {
    // 关闭视频通话成功，停止videoTrack并释放摄像头资源
    console.log('/ 关闭视频通话成功，停止videoTrack并释放摄像头资源');    
    videoTrack.stop();
  }).catch((err)=>{
    console.log(err);
  });
}
    **this.localStream.stop()
    this.localStream.close()
    this.client.leave().then(() => {
      // leaving room success
    }).catch(error => {
      console.error('leaving room failed: ' + error);
    });**`
![image](https://user-images.githubusercontent.com/25810268/67742031-cec9b300-fa55-11e9-8a34-75dd6df814a8.png)
![image](https://user-images.githubusercontent.com/25810268/67742177-44358380-fa56-11e9-9f01-274e47118bce.png)
![image](https://user-images.githubusercontent.com/25810268/67742202-58798080-fa56-11e9-817f-a76d9e5399a7.png)

**Comment by 285878535** [comment]
在你们的官方在线demo里，已经退出房间了还是显示摄像头在占用
![image](https://user-images.githubusercontent.com/25810268/67742289-9b3b5880-fa56-11e9-9bb1-a8dc4ed3494c.png)

**Comment by MasterXS** [comment]
@285878535 地址栏的摄像头图标表明该页面已经授予摄像头或麦克风访问权限，tab栏的红点才代表当前摄像头或麦克风采集正在进行中。官网体验demo退房后已调用localStream.stop() 和 localStream.close()，页面退出到登录界面的状态是正常的。如果在调用localStream.close() 前已通过localStream.removeTrack()删除视频，则需要在removeTrack()的回调中自行调用videoTrack.stop()关闭视频轨道以释放摄像头资源。

**Comment by 285878535** [comment]
![image](https://user-images.githubusercontent.com/25810268/67747479-c5474780-fa63-11e9-98da-17ea9ec81d28.png)
所以只需要下面三个方法就可以释放摄像头了是吗？那为啥我的谷歌浏览器标签页还是在亮红灯。而且你们官网demo虽然是退出来房间了  但是为什么还在显示音频在启用状态？
` this.localStream.stop()
    this.localStream.close()
    this.client.leave().then(() => {
      console.log('leaving room success');
      
    }).catch(error => {
      console.error('leaving room failed: ' + error);
    });`

**Comment by tingyuji** [comment]
确实存在这个问题

**Comment by MasterXS** [comment]
> 你们官网demo虽然是退出来房间了 但是为什么还在显示音频在启用状态？
请参考我上面的回复，tab栏上有**红圈**才代表摄像头或麦克风处于采集状态.
![image](https://user-images.githubusercontent.com/8175839/67748311-93cf7b80-fa65-11e9-8754-9a3599a3de80.png)
tab栏上“小喇叭”在页面退回登录页面后会慢慢消失。

请参考我们的新手导引demo进行退房、关闭本地流操作。
https://github.com/tencentyun/TRTCSDK/blob/master/Web/js/rtc-client.js
先退房，再关闭本地流；或者先调用unpublish()再关闭本地流，最后退房。

![image](https://user-images.githubusercontent.com/8175839/67748549-26701a80-fa66-11e9-9f79-b330640d64d1.png)

**Comment by 285878535** [comment]
this.client.leave().then(() => {
      console.log('leaving room success');
      // // 取消发布本地流
    this.localStream.stop()
    this.localStream.close()
    this.localStream = null;
      
    }).catch(error => {
      console.error('leaving room failed: ' + error);
    });
好的。谢谢，已经可以了
