### ISSUE TITLE
这个版本，有没有纯音频通话的demo？

### ISSUE THREAD

**Issue by hold-my-hand** [tencentyun/TRTCSDK#79]
这个版本，有没有纯音频通话的demo？我看见其它厂商有纯音频通话的，请问你们的纯音频的通话是怎么处理的，看demo好像都是视频的

**Comment by rexchang2016** [comment]
您好，只需要不 startLocalPreview ，房间里的用户就不会开启视频上行， 也就是纯语音通话了，demo我们尽快加一下。

**Comment by hold-my-hand** [comment]
thanks a lot
