### ISSUE TITLE
trtc-js-sdk 有 es6 语法

### ISSUE THREAD

**Issue by winixt** [tencentyun/TRTCSDK#81]
![image](https://user-images.githubusercontent.com/20717402/68232097-4c358a80-0037-11ea-96f5-3a6024c4f750.png)
对于一些老的构建会出错

**Comment by winixt** [comment]
![image](https://user-images.githubusercontent.com/20717402/68232161-738c5780-0037-11ea-9e5f-45dfa08ec577.png)

**Comment by anderlu** [comment]
感谢反馈，请问是什么构建工具？webrtc 依赖现代浏览器提供能力支持，例如 chrome Safari 同时这些浏览器也是支持 ES6 的，另外建议使用现代构建工具

**Comment by winixt** [comment]
> 感谢反馈，请问是什么构建工具？webrtc 依赖现代浏览器提供能力支持，例如 chrome Safari 同时这些浏览器也是支持 ES6 的，另外建议使用现代构建工具

gulp + webpack3.x ，如果构建工具不对 node_modules 进行处理的的话，UglifyJs 发现 es6 语法就会报错
