### ISSUE TITLE
Android无法区分前后摄像头和华为手机无法指定前置摄像头

### ISSUE THREAD

**Issue by xuya227939** [tencentyun/TRTCSDK#82]
【Android】-【华为】
【当前现象】：华为p30、p20、Nova系列，h5页面在微信游览器环境下，facingMode指定为user不生效。谷歌游览器生效
【集成包】：无
【SDKAppID】：N/A
【机型】：华为p30、p20、Nova系列
【之前版本有无此问题】：无
【是否必现】：必现
【日志或者截图】：暂无日志

【Android】
【当前现象】：通过TRTC.getCameras()获取到的摄像头信息，无特别标注前后摄像头。
【集成包】：无
【SDKAppID】：N/A
【机型】：无
【之前版本有无此问题】：又
【是否必现】：必现
【日志或者截图】：
![E6F7155DD31F2B04AE6BC6EAF6B910C2](https://user-images.githubusercontent.com/16217324/68270634-e4b02700-0098-11ea-8004-c78d67f7fcf6.png)

**Comment by MasterXS** [comment]
在没有授予camera访问权限前，TRTC.getCamera() 返回的MediaDeviceInfo.label字段是无明显标识的，这是浏览器引擎的安全限制。可以在用户授予camera访问权限后再次getCamera()来获取有意义的label字段。

部分Android手机设备上 facingMode设置无效问题是由于浏览器跟手机设备的适配兼容性问题，此时若想成功切换前后摄像头，App需要针对不同的设备做适配，即通过cameraId来设置摄像头。

此外，为了获得更好的一致性体验，在微信环境下建议使用小程序通话方案。
