### ISSUE TITLE
【Web】-【4.2.0】Angular6.1从3.0.6版本sdk升级到4.2.0后本地流显示问题

### ISSUE THREAD

**Issue by xuye1991** [tencentyun/TRTCSDK#84]
【当前现象】：
显示本地流报错，trtc.js报错。
Cannot read property 'uint32_audio_real_recv_pkg' of undefined
Cannot read property 'bytesSent' of undefined

【集成包】：WebSDK 4.2.0
【SDKAppID】：1400238197
【房间号】: 528341
【useID】：系统测试账号
【机型】：Chorme 73
【之前版本有无此问题】：WebSDK 3.0.6 未出现该问题
【是否必现】：必现 
【复现方法】：
将trtc-sdk 4.2用npm方式安装。
在polyfile中引用trtc-sdk。
使用ts实现demo中RtcClient类。
在组件中引用RtcClient类，并调用join() 方法。
填写测试账号到指定参数。
启动项目。

【日志或者描述、截图】：
Cannot read property 'uint32_audio_real_recv_pkg' of undefined
Cannot read property 'bytesSent' of undefined

**Comment by xuye1991** [comment]
![image](https://user-images.githubusercontent.com/39071930/68402415-41edca80-01b6-11ea-84d1-e4b196a6a1e5.png)
![image](https://user-images.githubusercontent.com/39071930/68402481-5c27a880-01b6-11ea-982e-090a2ec4dc6e.png)

**Comment by anderlu** [comment]
感谢反馈，zone.js 会修改原型链上的一些方法，我们还在定位具体原因

**Comment by MasterXS** [comment]
@xuye1991 可否提供一个sample工程复现一下问题？

**Comment by xuye1991** [comment]
正在准备，稍后发出仓库地址，请稍等

**Comment by xuye1991** [comment]
请使用一下地址下载代码：
https://github.com/xuye1991/electronDemo.git
或  git@github.com:xuye1991/electronDemo.git

下载完成后请安装依赖包。

完成后请到src/app/routes/cameras/cameras.component.ts中补充APPId和UserSig。

包安装完成后在控制台输入 npm run dev 即可运行.

可以在Electron的窗口中刷新页面查看效果，或直接在浏览器的localhost：4200查看效果。

**Comment by xuye1991** [comment]
@MasterXS

**Comment by xuye1991** [comment]
有一个包需要单独安装  运行  npm install -g concurrently

**Comment by anderlu** [comment]
感谢反馈，问题已经定位清楚，由于zone.js 修改了 Object.prototype.toString 方法，导致SDK判断出错，SDK已经进行适配处理，下个版本会修复。

**Comment by xuye1991** [comment]
你好请问下个版本的SDK大概多久可以发出来，这样我这边可以有个计划，多谢

**Comment by anderlu** [comment]
https://trtc-1252463788.cos.ap-guangzhou.myqcloud.com/web/sdk/trtc.preview.js 可以用这个预览版测试一下，下个版本大概本周四发布。
