### ISSUE TITLE
可否提供web demo的源码

### ISSUE THREAD

**Issue by CHN-STUDENT** [tencentyun/TRTCSDK#86]
您好，我们想将trtc聊天集成到im聊天系统中，希望能够得到web demo源码供参考？

im聊天demo使用vue开发，https://github.com/tencentyun/TIMSDK/tree/master/H5， 我们想尝试修改聊天加入视频语音聊天功能。

另外问下，你们请问后期有和im聊天相结合的计划么？

感谢答复！

**Comment by anderlu** [comment]
感谢反馈，trtc web demo 源码在仓库中已经提供https://github.com/tencentyun/TRTCSDK/tree/master/Web。TRTC 和IM SDK 结合已经在进行中，我们会尽快推出demo，感谢关注

**Comment by CHN-STUDENT** [comment]
@anderlu 您好请问您们这个demo的addView方法实现逻辑是什么(添加远端视频画面)？
```
function addView(id) {
  if (!$('#' + id)[0]) {
    $('<div/>', {
      id,
      class: 'video-view'
    }).appendTo('#video_grid');
  }
}
```
我需要改写该部分以便在Vue中实现，现在发现有问题。
```
 if(!document.getElementById(id)[0]) {
       var div= document.createElement('div')
       div.className='video-view'
       div.id=id
       document.getElementById('video_grid').appendChild(div)
    }
```
![image](https://user-images.githubusercontent.com/21209416/69335382-cdc42400-0c97-11ea-852c-24be5f8c4b12.png)

错误日志
app.bd4e40bb.js:1 Uncaught TypeError: Cannot read property '0' of null
    at Object.addView (app.bd4e40bb.js:1)
    at s.<anonymous> (app.bd4e40bb.js:1)
    at s.emit (chunk-vendors.f36afea5.js:13)
    at s.<anonymous> (chunk-vendors.f36afea5.js:13)
    at s.emit (chunk-vendors.f36afea5.js:13)
    at e.value (chunk-vendors.f36afea5.js:13)
    at e.value (chunk-vendors.f36afea5.js:13)
    at s.<anonymous> (app.bd4e40bb.js:1)
    at s.emit (chunk-vendors.f36afea5.js:13)
    at s.<anonymous> (chunk-vendors.f36afea5.js:13)

**Comment by CHN-STUDENT** [comment]
我的思路是在IM聊天上加了一个el-dialog对话框，打开该对话框会建立房间并且推流，然后两个用户可以在本界面进行视频聊天。
现在问题是本地可以显示，远方加入但是无法插入div和显示。
![image](https://user-images.githubusercontent.com/21209416/69338918-2945e000-0c9f-11ea-8ee2-783863868ed0.png)

**Comment by anderlu** [comment]
addView 是在页面添加一个远端player的容器，远端加入时得保证该容器已经渲染到dom tree上了

**Comment by anderlu** [comment]
addView 是在页面添加一个远端player的容器，远端加入时得保证该容器已经渲染到dom tree上了

**Comment by CHN-STUDENT** [comment]
@anderlu 好的感谢您，我已经成功做到了视频聊天和文字聊天的结合，如果有需要我们再交流~
感谢！
