### ISSUE TITLE
【web】-【4.2.0】进房后立马退房会出现报错

### ISSUE THREAD

**Issue by zhangjya** [tencentyun/TRTCSDK#87]
【当前现象】：调用join（）后立马同步调用leave（），当获得join回调结果时，相关资源已释放，josin的后续操作出现报错
【集成包】：trtc-js-sdk  4.2.0
【SDKAppID】：N/A
【机型】：chrome  78.0.3904.70（正式版本） （64 位）
【是否必现】：必现
【预期】：join过程中，如果leave并释放资源，应该直接结束join过程，本地流初始化和播放过程同上
【日志或者截图】：
![image](https://user-images.githubusercontent.com/17448348/68937889-37e05300-07d8-11ea-9dae-aead91ed5d5f.png)

**Comment by MasterXS** [comment]
请在join()成功或失败后再调用leave()，leave()不是为了取消正在执行中的join()。请按demo或文档操作 https://trtc-1252463788.file.myqcloud.com/web/docs/tutorial-01-basic-video-call.html
