### ISSUE TITLE
【微信小程序】怎么设置大小画面切换呀?类似微信视频通话切换效果

### ISSUE THREAD

**Issue by Jane-shanli** [tencentyun/TRTCSDK#88]
就demo中选择float布局的时候,咋样设置大小画面切换呢,有啥思路呀

**Comment by anderlu** [comment]
目前小程序player 和pusher的同层渲染模式微信还未全量支持，在同层模式下可以通过 wxss 设置层级来实现。

**Comment by Jane-shanli** [comment]
好的,感谢
