### ISSUE TITLE
ios微信H5应用用引用WebRTCAPI.min.js会出错

### ISSUE THREAD

**Issue by yuzhougit** [tencentyun/TRTCSDK#9]
ios上，H5应用引用https://sqimg.qq.com/expert_qq/webrtc/3.0/WebRTCAPI.min.js，在safari或者微信内置浏览器中，会RTCPeerConnection引用不存在的错误

unction(e, t) {
    !function() {
        RTCPeerConnection && (RTCPeerConnection.prototype.getPeerStats = window.getStats)
    }()
}, function(e, t, n) {

**Comment by anderlu** [comment]
https://cloud.tencent.com/document/product/647/16863
![image](https://user-images.githubusercontent.com/1832616/53850504-78a38d80-3ff6-11e9-82d6-d4fd2b990326.png)
先确定当前环境是否支持webrtc的相关特性
https://www.qcloudtrtc.com/webrtc-samples/abilitytest/index.html
![image](https://user-images.githubusercontent.com/1832616/53850577-b30d2a80-3ff6-11e9-91a7-59e04488f98d.png)

**Comment by yuzhougit** [comment]
我的意思能不能在不支持的平台上引入脚本时也不要报脚本错误，这样可以通过WebRTCAPI.fn.detectRTC来友好的报告当前版本不支持，报了脚本错误后就导致网页中后续脚本无法执行了
Message: ReferenceError: Can't find variable: RTCPeerConnection - URL: https://sqimg.qq.com/expert_qq/webrtc/3.0/WebRTCAPI.min.js?v=1551838032620 - Line: 1 - Column: 127469 - Error object: undefined
