### ISSUE TITLE
请问实时音视频在web端可以设置码率吗，具体是怎么操作

### ISSUE THREAD

**Issue by ixiaofeiyang** [tencentyun/TRTCSDK#90]
请问实时音视频在web端可以设置码率吗，具体是怎么操作？
是在哪个api下面

**Comment by MasterXS** [comment]
setVideoProfile，请参考  - https://trtc-1252463788.file.myqcloud.com/web/docs/tutorial-04-advanced-set-video-profile.html?_ga=1.70962073.864549351.1557155865
