### ISSUE TITLE
web端 支不支持画中画？

### ISSUE THREAD

**Issue by xiayefeng** [tencentyun/TRTCSDK#91]
video.requestPictureInPicture()

**Comment by MasterXS** [comment]
感谢您的反馈，目前内置videoPlayer尚不支持PiP，后续我们会考虑增加这个功能，目前开发者可以通过自定义播放渲染的方式使能PiP。https://trtc-1252463788.file.myqcloud.com/web/docs/tutorial-08-advanced-customized-capture-rendering.html?_ga=1.97256598.864549351.1557155865

**Comment by xiayefeng** [comment]
thanks
