### ISSUE TITLE
请在说明中加入web版实际部署需要https

### ISSUE THREAD

**Issue by CHN-STUDENT** [tencentyun/TRTCSDK#97]
**如题，因为chrome的安全隐私策略，只有localhost和https的页面被允许使用摄像头和麦克风。**

测试发现本地Lan无法使用摄像头和麦克风

![image](https://user-images.githubusercontent.com/21209416/69898546-f2a25080-1395-11ea-9068-54b1982c7ffe.png)

**或者说明加入Chrome实验性功能白名单（危险）**
 访问 `chrome://flags/#unsafely-treat-insecure-origin-as-secure` 填写域名（含端口）

![image](https://user-images.githubusercontent.com/21209416/69898682-8294ca00-1397-11ea-8a69-3728c16a5f04.png)

![image](https://user-images.githubusercontent.com/21209416/69898753-634a6c80-1398-11ea-8e8a-859b7291c9ec.png)

> 参考链接：https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339

**Comment by MasterXS** [comment]
感谢反馈，webrtc现网部署确实是需要https的
