### ISSUE TITLE
Android 报错 Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCacheClassForNative() (tried Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative and Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative__)

### ISSUE THREAD

**Issue by baohexin** [tencentyun/TRTCSDK#99]
今天运行报错Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCacheClassForNative() (tried Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative and Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative__)
之前运行好好的，依赖最新版的6.8.7968   implementation 'com.tencent.liteav:LiteAVSDK_TRTC:latest.release'

**Comment by suonian** [comment]
麻烦参考这个 https://github.com/tencentyun/TRTCSDK/issues/93 清理缓存重新编译试试，如果还报错发一下完整的log。

**Comment by iotexplor** [comment]
依然报错，使用最新版的SDK，清理缓存也一样 ....

**Comment by 546669204** [comment]
同样的报错。
但是只出现在 华为 emui 10 android 10 上 ；
使用其他手机 平板没问题 。

**Comment by kiolygenius** [comment]
你把 arm64-v8a 去掉只用 armeabi-v7a 看看。我估计是64位原生库有问题。

**Comment by whalehe** [comment]
在build.gradle中可以指定下so，去掉 arm64-v8a ，使用如下
defaultConfig {
...
     ndk {
            abiFilters "armeabi", "armeabi-v7a"
     }
}

implementation "com.tencent.liteav:LiteAVSDK_TRTC:latest.release"

如还有问题，建议下载最新aar包本地集成。
